voogasalad_BitsPlease: gamePlayer.model.ZipHelper Class Reference
gamePlayer.model.ZipHelper Class Reference
Public Member Functions
File zipDir (String dirName) throws IOException
Private Member Functions
void addFolderToZip (String path, String srcFolder, ZipOutputStream zip) throws IOException
void addFileToZip (String path, String srcFile, ZipOutputStream zip, boolean flag) throws IOException
Detailed Description
Definition at line 15 of file ZipHelper.java.
Member Function Documentation
void gamePlayer.model.ZipHelper.addFileToZip (String path, String srcFile, ZipOutputStream zip, boolean flag) throws IOException private
Definition at line 46 of file ZipHelper.java.
References gamePlayer.model.ZipHelper.addFolderToZip().
Referenced by gamePlayer.model.ZipHelper.addFolderToZip().
void gamePlayer.model.ZipHelper.addFolderToZip (String path, String srcFolder, ZipOutputStream zip) throws IOException private
Definition at line 29 of file ZipHelper.java.
References gamePlayer.model.ZipHelper.addFileToZip().
Referenced by gamePlayer.model.ZipHelper.addFileToZip(), and gamePlayer.model.ZipHelper.zipDir().
File gamePlayer.model.ZipHelper.zipDir (String dirName) throws IOException
Definition at line 17 of file ZipHelper.java.
References gamePlayer.model.ZipHelper.addFolderToZip().
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/voogasalad_BitsPlease/repository/src/gamePlayer/model/ZipHelper.java