voogasalad_BitsPlease: engine.conditions.ButtonPressCondition Class Reference
engine.conditions.ButtonPressCondition Class Reference
Public Member Functions
ButtonPressCondition (List< Action > onPressActions, List< KeyCode > keyList, Double frameCount, Boolean keyRepeats)
void setOnReleaseActions (List< Action > onReleaseActions)
String getKeyIdentifier ()
List< KeyCode > getKeyList ()
void addKey (KeyCode kc)
void removeKey (KeyCode kc)
void setKeyIdentifier (String id)
void respondToFrameElapsed ()
Public Member Functions inherited from engine.conditions.Condition
Condition (List< Action > actions)
List< Action > getActions ()
void setEnabled (Boolean enabled)
boolean isEnabled ()
void setInputMap (Map< String, String > inputs)
Map< String, String > getInputMap ()
void frameElapsed ()
void setIdentifier (Identifier myId)
Identifier getIdentifier ()
void initialize (GameManager manager)
void addAction (Action a)
Protected Member Functions
void executeActions ()
Protected Member Functions inherited from engine.conditions.Condition
abstract void executeActions ()
abstract void respondToFrameElapsed ()
void initializeActions (GameManager manager)
GameManager getGameManager ()
Private Attributes
List< KeyCode > myKeyList
List< Action > myReleaseActions
Double myFramesElapsed
Double myTargetFrameCount
Boolean myKeyRepeats
Boolean myExpired = false
Boolean myButtonActive = false
Additional Inherited Members
Protected Attributes inherited from engine.conditions.Condition
List< Action > myActions = new ArrayList<Action>()
transient GameManager myGameManager
Identifier myId
Detailed Description
Definition at line 14 of file ButtonPressCondition.java.
Constructor & Destructor Documentation
engine.conditions.ButtonPressCondition.ButtonPressCondition (List< Action > onPressActions, List< KeyCode > keyList, Double frameCount, Boolean keyRepeats)
Definition at line 25 of file ButtonPressCondition.java.
Member Function Documentation
void engine.conditions.ButtonPressCondition.addKey (KeyCode kc)
Definition at line 47 of file ButtonPressCondition.java.
Referenced by gamePlayer.view.keyboardUtility.KeyboardView.setNewKey().
void engine.conditions.ButtonPressCondition.executeActions () protected
Definition at line 65 of file ButtonPressCondition.java.
References engine.conditions.Condition.getActions(), engine.conditions.ButtonConditionManager.getInstance(), engine.conditions.ButtonConditionManager.keyIsActive(), and engine.conditions.ButtonPressCondition.myKeyRepeats.
Referenced by engine.conditions.ButtonPressCondition.respondToFrameElapsed().
String engine.conditions.ButtonPressCondition.getKeyIdentifier ()
Definition at line 38 of file ButtonPressCondition.java.
References engine.gameObject.Identifier.getUniqueId(), and engine.conditions.Condition.myId.
Referenced by gamePlayer.view.keyboardUtility.KeyboardView.comboBoxForButton(), and gamePlayer.view.keyboardUtility.KeyboardView.setNewKey().
List<KeyCode> engine.conditions.ButtonPressCondition.getKeyList ()
Definition at line 42 of file ButtonPressCondition.java.
References engine.conditions.ButtonPressCondition.myKeyList.
Referenced by gamePlayer.view.keyboardUtility.KeyboardView.setNewKey().
void engine.conditions.ButtonPressCondition.removeKey (KeyCode kc)
Definition at line 55 of file ButtonPressCondition.java.
Referenced by gamePlayer.view.keyboardUtility.KeyboardView.setNewKey().
void engine.conditions.ButtonPressCondition.respondToFrameElapsed ()
Definition at line 98 of file ButtonPressCondition.java.
References engine.conditions.ButtonPressCondition.executeActions().
void engine.conditions.ButtonPressCondition.setKeyIdentifier (String id)
Definition at line 59 of file ButtonPressCondition.java.
References engine.conditions.Condition.myId, and engine.gameObject.Identifier.setUniqueId().
void engine.conditions.ButtonPressCondition.setOnReleaseActions (List< Action > onReleaseActions)
Definition at line 34 of file ButtonPressCondition.java.
Member Data Documentation
Boolean engine.conditions.ButtonPressCondition.myButtonActive = false private
Definition at line 21 of file ButtonPressCondition.java.
Boolean engine.conditions.ButtonPressCondition.myExpired = false private
Definition at line 20 of file ButtonPressCondition.java.
Double engine.conditions.ButtonPressCondition.myFramesElapsed private
Definition at line 17 of file ButtonPressCondition.java.
List<KeyCode> engine.conditions.ButtonPressCondition.myKeyList private
Definition at line 15 of file ButtonPressCondition.java.
Referenced by engine.conditions.ButtonPressCondition.getKeyList().
Boolean engine.conditions.ButtonPressCondition.myKeyRepeats private
Definition at line 19 of file ButtonPressCondition.java.
Referenced by engine.conditions.ButtonPressCondition.executeActions().
List<Action> engine.conditions.ButtonPressCondition.myReleaseActions private
Definition at line 16 of file ButtonPressCondition.java.
Double engine.conditions.ButtonPressCondition.myTargetFrameCount private
Definition at line 18 of file ButtonPressCondition.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/voogasalad_BitsPlease/repository/src/engine/conditions/ButtonPressCondition.java