voogasalad_BitsPlease: authoring.eventhandlers.GameObjectDragToLevelHandler Class Reference
authoring.eventhandlers.GameObjectDragToLevelHandler Class Reference
Public Member Functions
GameObjectDragToLevelHandler (LevelsView levelView, LevelsCollection data, PropertiesView props)
void handle (MouseEvent event)
EventType< MouseEvent > getEventType ()
Public Member Functions inherited from authoring.eventhandlers.GameHandler< MouseEvent >
void handle (T arg0)
EventType< T > getEventType ()
Private Member Functions
void updateName (Level level)
Private Attributes
LevelsView myLevelView
LevelsCollection myLevelsCollection
PropertiesView myProps
NameWizard myNameWizard
GameObject myNewGameObject
GameObjectsCollection myGameObjectCollection
Detailed Description
Handles user click on graphic objects. Projects graphic properties in PropertiesView and/or creates copy of selected graphic on the active level.
Author
Wesley Valentine
Chris Bernt
Kevin Li
Arjun Jain
Safkat Islam
Definition at line 31 of file GameObjectDragToLevelHandler.java.
Constructor & Destructor Documentation
authoring.eventhandlers.GameObjectDragToLevelHandler.GameObjectDragToLevelHandler (LevelsView levelView, LevelsCollection data, PropertiesView props)
Definition at line 39 of file GameObjectDragToLevelHandler.java.
Member Function Documentation
EventType<MouseEvent> authoring.eventhandlers.GameObjectDragToLevelHandler.getEventType ()
Definition at line 98 of file GameObjectDragToLevelHandler.java.
void authoring.eventhandlers.GameObjectDragToLevelHandler.handle (MouseEvent event)
Definition at line 47 of file GameObjectDragToLevelHandler.java.
References authoring.view.propertiesview.PropertiesView.displayProperties(), authoring.view.levelview.LevelsView.getCurrentLevel(), authoring.view.icons.GameObjectIcon.getGameObject(), authoring.view.levelview.SingleLevelView.getID(), engine.gameObject.GameObject.getIdentifier(), engine.gameObject.Identifier.getType(), engine.gameObject.GameObject.setIdentifier(), engine.gameObject.GameObject.setX(), engine.gameObject.GameObject.setY(), and authoring.eventhandlers.GameObjectDragToLevelHandler.updateName().
void authoring.eventhandlers.GameObjectDragToLevelHandler.updateName (Level level) private
Definition at line 85 of file GameObjectDragToLevelHandler.java.
References engine.level.Level.addGameObject(), errorsAndExceptions.ErrorPopUp.display(), engine.gameObject.GameObject.getIdentifier(), authoring.view.wizards.Wizard.getMap(), authoring.view.wizards.NameWizard.isDuplicated(), and engine.gameObject.Identifier.setUniqueId().
Referenced by authoring.eventhandlers.GameObjectDragToLevelHandler.handle().
Member Data Documentation
GameObjectsCollection authoring.eventhandlers.GameObjectDragToLevelHandler.myGameObjectCollection private
Definition at line 37 of file GameObjectDragToLevelHandler.java.
LevelsCollection authoring.eventhandlers.GameObjectDragToLevelHandler.myLevelsCollection private
Definition at line 33 of file GameObjectDragToLevelHandler.java.
LevelsView authoring.eventhandlers.GameObjectDragToLevelHandler.myLevelView private
Definition at line 32 of file GameObjectDragToLevelHandler.java.
NameWizard authoring.eventhandlers.GameObjectDragToLevelHandler.myNameWizard private
Definition at line 35 of file GameObjectDragToLevelHandler.java.
GameObject authoring.eventhandlers.GameObjectDragToLevelHandler.myNewGameObject private
Definition at line 36 of file GameObjectDragToLevelHandler.java.
PropertiesView authoring.eventhandlers.GameObjectDragToLevelHandler.myProps private
Definition at line 34 of file GameObjectDragToLevelHandler.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/voogasalad_BitsPlease/repository/src/authoring/eventhandlers/GameObjectDragToLevelHandler.java