voogasalad_BitsPlease: data.DataManager Class Reference
data.DataManager Class Reference
Public Member Functions
DataManager ()
boolean writeGameFile (GameData data, File dataPath) throws IOException
GameData readGameFile (File dataPath) throws FileNotFoundException
boolean writeProgressFile (GameData data, File dataPath, String progressName) throws IOException
GameData readProgressFile (File dataPath, String progressName) throws FileNotFoundException
Static Public Attributes
static final String IMAGES_FOLDER_NAME = "images"
static final String SOUNDS_FOLDER_NAME = "sounds"
static final String PROGRESS_FOLDER_NAME = "progress"
Private Member Functions
boolean writeFile (Object obj, File dataPath, String fileName) throws IOException
Object readFile (Class cl, File dataPath, String fileName) throws FileNotFoundException
boolean hasValidName (String fileName)
String checkForExtension (String fileName)
Private Attributes
GsonBuilder gson
Detailed Description
Responsible for loading and saving of all files within authoring environment and game engine.
Author
Eli Lichtenberg
Safkat Islam
Definition at line 28 of file DataManager.java.
Constructor & Destructor Documentation
data.DataManager.DataManager ()
Definition at line 35 of file DataManager.java.
Member Function Documentation
String data.DataManager.checkForExtension (String fileName) private
Definition at line 119 of file DataManager.java.
boolean data.DataManager.hasValidName (String fileName) private
Definition at line 111 of file DataManager.java.
Object data.DataManager.readFile (Class cl, File dataPath, String fileName) throws FileNotFoundException private
Definition at line 104 of file DataManager.java.
Referenced by data.DataManager.readGameFile(), and data.DataManager.readProgressFile().
GameData data.DataManager.readGameFile (File dataPath) throws FileNotFoundException
Gets an object representing a game from a Json file.
Parameters
dataPath Game folder location.
Returns
Exceptions
FileNotFoundException
Definition at line 62 of file DataManager.java.
References data.DataManager.readFile().
Referenced by authoring.view.ProgramMenu.loadData(), and gamePlayer.model.PlayerModel.loadGameFile().
GameData data.DataManager.readProgressFile (File dataPath, String progressName) throws FileNotFoundException
Gets an object representing a game at a certain progress state from a Json file.
Parameters
dataPath Game folder location.
progressName Name of progress state file.
Returns
Exceptions
FileNotFoundException
Definition at line 90 of file DataManager.java.
References data.DataManager.readFile().
Referenced by gamePlayer.model.PlayerModel.addFileNameChangeListener().
boolean data.DataManager.writeFile (Object obj, File dataPath, String fileName) throws IOException private
Definition at line 95 of file DataManager.java.
Referenced by data.DataManager.writeGameFile(), and data.DataManager.writeProgressFile().
boolean data.DataManager.writeGameFile (GameData data, File dataPath) throws IOException
Creates a Json file based on an object representing a game.
Parameters
data Game data being saved.
dataPath Game folder location.
Returns
Exceptions
IOException
Definition at line 51 of file DataManager.java.
References data.DataManager.writeFile().
Referenced by authoring.model.AuthoringModel.save().
boolean data.DataManager.writeProgressFile (GameData data, File dataPath, String progressName) throws IOException
Creates a Json file based on an object representing a game at a certain progress state.
Parameters
data Game progress data being saved.
dataPath Game folder location.
progressName Name of progress state file.
Returns
Exceptions
IOException
Definition at line 76 of file DataManager.java.
References data.DataManager.writeFile().
Referenced by gamePlayer.view.ProgressSelector.overwriteProgressEvent(), authoring.model.AuthoringModel.save(), and gamePlayer.view.ProgressSelector.saveProgressEvent().
Member Data Documentation
GsonBuilder data.DataManager.gson private
Definition at line 33 of file DataManager.java.
final String data.DataManager.IMAGES_FOLDER_NAME = "images" static
Definition at line 30 of file DataManager.java.
Referenced by authoring.view.ProgramMenu.makeFolders().
final String data.DataManager.PROGRESS_FOLDER_NAME = "progress" static
Definition at line 32 of file DataManager.java.
Referenced by authoring.view.ProgramMenu.makeFolders(), and gamePlayer.view.ProgressSelector.ProgressSelector().
final String data.DataManager.SOUNDS_FOLDER_NAME = "sounds" static
Definition at line 31 of file DataManager.java.
Referenced by authoring.view.ProgramMenu.makeFolders().
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/voogasalad_BitsPlease/repository/src/data/DataManager.java