voogasalad_BitsPlease: engine.collision.objects.CollisionComposition Class Reference
engine.collision.objects.CollisionComposition Class Reference
Public Member Functions
boolean isOnXAxis (GameObject one, GameObject two)
void fixedCollision (GameObject one, GameObject two)
void reverseVelocites (GameObject one, GameObject two)
Private Member Functions
double collisionHelper (double centerOne, double centerTwo, double measureOne, double measureTwo)
Static Private Attributes
static final double FRAMES_PER_SECOND = 60.0
Detailed Description
Author
Ben
Definition at line 13 of file CollisionComposition.java.
Member Function Documentation
double engine.collision.objects.CollisionComposition.collisionHelper (double centerOne, double centerTwo, double measureOne, double measureTwo) private
Definition at line 104 of file CollisionComposition.java.
void engine.collision.objects.CollisionComposition.fixedCollision (GameObject one, GameObject two)
Definition at line 64 of file CollisionComposition.java.
References engine.gameObject.components.PhysicsBody.getCollisionBodyHeight(), engine.gameObject.components.PhysicsBody.getCollisionBodyWidth(), engine.gameObject.GameObject.getPhysicsBody(), engine.gameObject.components.PhysicsBody.getScalar(), engine.gameObject.GameObject.getTranslateX(), engine.gameObject.GameObject.getTranslateY(), engine.gameObject.components.PhysicsBody.getVelocity(), engine.physics.Vector.getX(), engine.physics.Vector.getY(), engine.collision.objects.CollisionComposition.isOnXAxis(), engine.gameObject.GameObject.setTranslateX(), engine.gameObject.GameObject.setTranslateY(), engine.gameObject.components.PhysicsBody.setVelocity(), and engine.physics.PhysicsComponent.toString().
Referenced by engine.actions.FixedCollisionTypeAction.applyPhysics(), engine.actions.FixedCollisionAction.applyPhysics(), engine.collision.objects.FixedObjectCollisionObject.handleEnemyCollisionObject(), engine.collision.objects.FixedObjectCollisionObject.handleFixedObjectCollisionObject(), engine.collision.objects.HeroCollisionObject.handleFixedObjectCollisionObject(), engine.collision.objects.PowerupCollisionObject.handleFixedObjectCollisionObject(), engine.collision.objects.EnemyCollisionObject.handleFixedObjectCollisionObject(), engine.collision.objects.FixedObjectCollisionObject.handleHeroCollisionObject(), and engine.collision.objects.FixedObjectCollisionObject.handlePowerupCollisionObject().
boolean engine.collision.objects.CollisionComposition.isOnXAxis (GameObject one, GameObject two)
Definition at line 16 of file CollisionComposition.java.
References engine.gameObject.GameObject.getPhysicsBody(), engine.gameObject.GameObject.getRenderedNode(), engine.gameObject.components.PhysicsBody.getScalar(), engine.gameObject.GameObject.getTranslateX(), engine.gameObject.GameObject.getTranslateY(), engine.physics.Scalar.getValue(), engine.gameObject.components.PhysicsBody.getVelocity(), engine.physics.Vector.getX(), engine.physics.Vector.getY(), engine.render.RenderedNode.intersects(), engine.gameObject.GameObject.setTranslateX(), and engine.gameObject.GameObject.setTranslateY().
Referenced by engine.actions.ReverseVelocityIDAction.applyPhysics(), engine.collision.objects.CollisionComposition.fixedCollision(), and engine.collision.objects.CollisionComposition.reverseVelocites().
void engine.collision.objects.CollisionComposition.reverseVelocites (GameObject one, GameObject two)
Definition at line 111 of file CollisionComposition.java.
References engine.gameObject.GameObject.getPhysicsBody(), engine.collision.objects.CollisionComposition.isOnXAxis(), and engine.gameObject.components.PhysicsBody.reverseVelocity().
Referenced by engine.collision.objects.EnemyCollisionObject.handleEnemyCollisionObject(), engine.collision.objects.PowerupCollisionObject.handleEnemyCollisionObject(), engine.collision.objects.PowerupCollisionObject.handlePowerupCollisionObject(), and engine.collision.objects.EnemyCollisionObject.handlePowerupCollisionObject().
Member Data Documentation
final double engine.collision.objects.CollisionComposition.FRAMES_PER_SECOND = 60.0 static private
Definition at line 14 of file CollisionComposition.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/voogasalad_BitsPlease/repository/src/engine/collision/objects/CollisionComposition.java