voogasalad_BitsPlease: authoring.view.ProgramMenu Class Reference
authoring.view.ProgramMenu Class Reference
Public Member Functions
ProgramMenu (TabPane tab, Locale locale, double width, double height)
Package Attributes
TabPane myTabs
Map ControllerMap
Private Member Functions
Menu FileMenu ()
MenuItem newFile ()
MenuItem saveFile ()
void saveData ()
MenuItem loadFile ()
void loadData ()
void addNew ()
void setupGame (File gameLocation)
void makeFolders (File gameLocation)
Private Attributes
Locale myLocale
ResourceBundle myLanguage
double myWidth
double myHeight
FileChooser myFileChooser
DirectoryChooser myDirectoryChooser
DataManager myDataManager
Static Private Attributes
static final String DEFAULT_RESOURCE = "authoring.resources.languages/language"
Detailed Description
Class that contains the MenuBar for the authoring environments. Users can open new or saved files, save files, or change general settings such as language.
Author
Kevin Li
Definition at line 32 of file ProgramMenu.java.
Constructor & Destructor Documentation
authoring.view.ProgramMenu.ProgramMenu (TabPane tab, Locale locale, double width, double height)
Definition at line 45 of file ProgramMenu.java.
References authoring.view.ProgramMenu.FileMenu().
Member Function Documentation
void authoring.view.ProgramMenu.addNew () private
Method for adding a new tab.
Definition at line 130 of file ProgramMenu.java.
References authoring.view.ProgramMenu.makeFolders(), and authoring.view.ProgramMenu.setupGame().
Referenced by authoring.view.ProgramMenu.newFile().
Menu authoring.view.ProgramMenu.FileMenu () private
Method that creates the menu for all File related features such as open, save, new file, etc.
Returns
Menu containing MenuItems that allows the user to save, open, and generate new authoring environments.
Definition at line 66 of file ProgramMenu.java.
References authoring.view.ProgramMenu.loadFile(), authoring.view.ProgramMenu.newFile(), and authoring.view.ProgramMenu.saveFile().
Referenced by authoring.view.ProgramMenu.ProgramMenu().
void authoring.view.ProgramMenu.loadData () private
Definition at line 106 of file ProgramMenu.java.
References errorsAndExceptions.ErrorPopUp.display(), data.DataManager.readGameFile(), and authoring.view.ProgramMenu.setupGame().
Referenced by authoring.view.ProgramMenu.loadFile().
MenuItem authoring.view.ProgramMenu.loadFile () private
Definition at line 100 of file ProgramMenu.java.
References authoring.view.ProgramMenu.loadData().
Referenced by authoring.view.ProgramMenu.FileMenu().
void authoring.view.ProgramMenu.makeFolders (File gameLocation) private
Definition at line 151 of file ProgramMenu.java.
References data.DataManager.IMAGES_FOLDER_NAME, data.DataManager.PROGRESS_FOLDER_NAME, and data.DataManager.SOUNDS_FOLDER_NAME.
Referenced by authoring.view.ProgramMenu.addNew().
MenuItem authoring.view.ProgramMenu.newFile () private
Creates a menuItem that allows the user to open new instances of authoring environments. This is where the controller, view, and model are instantiated and connected with one another.
Returns
MenuItem that allows new files to be created.
Definition at line 80 of file ProgramMenu.java.
References authoring.view.ProgramMenu.addNew().
Referenced by authoring.view.ProgramMenu.FileMenu().
void authoring.view.ProgramMenu.saveData () private
Definition at line 93 of file ProgramMenu.java.
Referenced by authoring.view.ProgramMenu.saveFile().
MenuItem authoring.view.ProgramMenu.saveFile () private
Definition at line 87 of file ProgramMenu.java.
References authoring.view.ProgramMenu.saveData().
Referenced by authoring.view.ProgramMenu.FileMenu().
void authoring.view.ProgramMenu.setupGame (File gameLocation) private
Definition at line 139 of file ProgramMenu.java.
Referenced by authoring.view.ProgramMenu.addNew(), and authoring.view.ProgramMenu.loadData().
Member Data Documentation
Map authoring.view.ProgramMenu.ControllerMap package
Definition at line 42 of file ProgramMenu.java.
final String authoring.view.ProgramMenu.DEFAULT_RESOURCE = "authoring.resources.languages/language" static private
Definition at line 33 of file ProgramMenu.java.
DataManager authoring.view.ProgramMenu.myDataManager private
Definition at line 43 of file ProgramMenu.java.
DirectoryChooser authoring.view.ProgramMenu.myDirectoryChooser private
Definition at line 41 of file ProgramMenu.java.
FileChooser authoring.view.ProgramMenu.myFileChooser private
Definition at line 40 of file ProgramMenu.java.
double authoring.view.ProgramMenu.myHeight private
Definition at line 39 of file ProgramMenu.java.
ResourceBundle authoring.view.ProgramMenu.myLanguage private
Definition at line 35 of file ProgramMenu.java.
Locale authoring.view.ProgramMenu.myLocale private
Definition at line 34 of file ProgramMenu.java.
TabPane authoring.view.ProgramMenu.myTabs package
Definition at line 37 of file ProgramMenu.java.
double authoring.view.ProgramMenu.myWidth private
Definition at line 38 of file ProgramMenu.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/voogasalad_BitsPlease/repository/src/authoring/view/ProgramMenu.java