voogasalad_BitsPlease: authoring.eventhandlers.SaveAsNewHandler Class Reference
authoring.eventhandlers.SaveAsNewHandler Class Reference
Public Member Functions
SaveAsNewHandler (GameObjectsCollection coll, PropertiesView props)
void handle (Event arg0)
EventType< Event > getEventType ()
Public Member Functions inherited from authoring.eventhandlers.GameHandler< Event >
void handle (T arg0)
EventType< T > getEventType ()
Private Member Functions
void updateName ()
Private Attributes
GameObjectsCollection myGameObjectCollection
PropertiesView myProps
NameWizard myWizard
GameObject myNewGameObject
Detailed Description
Definition at line 13 of file SaveAsNewHandler.java.
Constructor & Destructor Documentation
authoring.eventhandlers.SaveAsNewHandler.SaveAsNewHandler (GameObjectsCollection coll, PropertiesView props)
Definition at line 20 of file SaveAsNewHandler.java.
Member Function Documentation
EventType<Event> authoring.eventhandlers.SaveAsNewHandler.getEventType ()
Definition at line 35 of file SaveAsNewHandler.java.
void authoring.eventhandlers.SaveAsNewHandler.handle (Event arg0)
Definition at line 26 of file SaveAsNewHandler.java.
References authoring.view.propertiesview.PropertiesView.getEditedGameObject(), and authoring.eventhandlers.SaveAsNewHandler.updateName().
void authoring.eventhandlers.SaveAsNewHandler.updateName () private
Definition at line 39 of file SaveAsNewHandler.java.
References authoring.model.collections.GeneralCollection< T >.add(), errorsAndExceptions.ErrorPopUp.display(), authoring.view.wizards.Wizard.getMap(), authoring.view.wizards.NameWizard.isDuplicated(), and engine.gameObject.GameObject.setIdentifier().
Referenced by authoring.eventhandlers.SaveAsNewHandler.handle().
Member Data Documentation
GameObjectsCollection authoring.eventhandlers.SaveAsNewHandler.myGameObjectCollection private
Definition at line 15 of file SaveAsNewHandler.java.
GameObject authoring.eventhandlers.SaveAsNewHandler.myNewGameObject private
Definition at line 18 of file SaveAsNewHandler.java.
PropertiesView authoring.eventhandlers.SaveAsNewHandler.myProps private
Definition at line 16 of file SaveAsNewHandler.java.
NameWizard authoring.eventhandlers.SaveAsNewHandler.myWizard private
Definition at line 17 of file SaveAsNewHandler.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/voogasalad_BitsPlease/repository/src/authoring/eventhandlers/SaveAsNewHandler.java