voogasalad_BitsPlease: engine.conditions.ButtonConditionManager Class Reference
engine.conditions.ButtonConditionManager Class Reference
Public Member Functions
void beginListeningToScene (Scene scene)
Static Public Member Functions
static ButtonConditionManager getInstance ()
Protected Member Functions
boolean keyIsActive (KeyCode key)
Private Member Functions
ButtonConditionManager ()
void keyReleased (KeyEvent event)
void keyPressed (KeyEvent event)
Private Attributes
Map< KeyCode, Integer > myActiveKeyBuffer
Static Private Attributes
static ButtonConditionManager sharedInstance
Detailed Description
Author
Davis
condition manager for conditions caused by a button press
Definition at line 17 of file ButtonConditionManager.java.
Constructor & Destructor Documentation
engine.conditions.ButtonConditionManager.ButtonConditionManager () private
Definition at line 30 of file ButtonConditionManager.java.
Referenced by engine.conditions.ButtonConditionManager.getInstance().
Member Function Documentation
void engine.conditions.ButtonConditionManager.beginListeningToScene (Scene scene)
tell the button condition manager to begin listening for key presses in a particular scene
Parameters
scene the scene to listen to
Definition at line 44 of file ButtonConditionManager.java.
References engine.conditions.ButtonConditionManager.keyPressed(), and engine.conditions.ButtonConditionManager.keyReleased().
Referenced by gamePlayer.view.PlayerView.initializeGUIComponents(), engine.tests.MainEngineTests.start(), and games.MarioGameTest.start().
static ButtonConditionManager engine.conditions.ButtonConditionManager.getInstance () static
Definition at line 23 of file ButtonConditionManager.java.
References engine.conditions.ButtonConditionManager.ButtonConditionManager(), and engine.conditions.ButtonConditionManager.sharedInstance.
Referenced by engine.conditions.ButtonReleaseCondition.executeActions(), engine.conditions.ButtonPressCondition.executeActions(), gamePlayer.view.PlayerView.initializeGUIComponents(), engine.tests.MainEngineTests.start(), and games.MarioGameTest.start().
boolean engine.conditions.ButtonConditionManager.keyIsActive (KeyCode key) protected
Definition at line 34 of file ButtonConditionManager.java.
Referenced by engine.conditions.ButtonReleaseCondition.executeActions(), and engine.conditions.ButtonPressCondition.executeActions().
void engine.conditions.ButtonConditionManager.keyPressed (KeyEvent event) private
Definition at line 53 of file ButtonConditionManager.java.
Referenced by engine.conditions.ButtonConditionManager.beginListeningToScene().
void engine.conditions.ButtonConditionManager.keyReleased (KeyEvent event) private
Definition at line 49 of file ButtonConditionManager.java.
Referenced by engine.conditions.ButtonConditionManager.beginListeningToScene().
Member Data Documentation
Map<KeyCode, Integer> engine.conditions.ButtonConditionManager.myActiveKeyBuffer private
Definition at line 18 of file ButtonConditionManager.java.
ButtonConditionManager engine.conditions.ButtonConditionManager.sharedInstance static private
Definition at line 20 of file ButtonConditionManager.java.
Referenced by engine.conditions.ButtonConditionManager.getInstance().
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/voogasalad_BitsPlease/repository/src/engine/conditions/ButtonConditionManager.java