voogasalad_BitsPlease: authoring.view.icons.GameObjectIcon Class Reference
authoring.view.icons.GameObjectIcon Class Reference
Public Member Functions
GameObjectIcon (GameObject gameObject, File location, GameHandler...event)
GameObject getGameObject ()
Public Member Functions inherited from authoring.view.icons.ImageBasedIcon
ImageBasedIcon (String name, File location, GameHandler...event)
void setDimensions (double width, double height, double rotation)
void scaleDimensions ()
Public Member Functions inherited from authoring.view.icons.FileIcon
FileIcon (File gameLoc, String label, GameHandler...handler)
Public Member Functions inherited from authoring.view.icons.BaseIcon
BaseIcon (String label, GameHandler...handler)
void addLabel ()
String getName ()
Private Attributes
GameObject myGameObject
Additional Inherited Members
Protected Member Functions inherited from authoring.view.icons.ImageBasedIcon
void makeIcon ()
Protected Member Functions inherited from authoring.view.icons.FileIcon
abstract void makeIcon ()
Protected Attributes inherited from authoring.view.icons.ImageBasedIcon
ImageView myImageView
double myWidth
double myHeight
double myRotation
Protected Attributes inherited from authoring.view.icons.FileIcon
File myGameLocation
Protected Attributes inherited from authoring.view.icons.BaseIcon
GameHandler[] myOnClick
String myLabel
Detailed Description
Definition at line 8 of file GameObjectIcon.java.
Constructor & Destructor Documentation
authoring.view.icons.GameObjectIcon.GameObjectIcon (GameObject gameObject, File location, GameHandler... event)
Definition at line 12 of file GameObjectIcon.java.
References engine.gameObject.GameObject.getCurrentImageName().
Member Function Documentation
GameObject authoring.view.icons.GameObjectIcon.getGameObject ()
Definition at line 18 of file GameObjectIcon.java.
References authoring.view.icons.GameObjectIcon.myGameObject.
Referenced by authoring.eventhandlers.GameObjectClickHandler.handle(), authoring.eventhandlers.GameObjectDragHandler.handle(), and authoring.eventhandlers.GameObjectDragToLevelHandler.handle().
Member Data Documentation
GameObject authoring.view.icons.GameObjectIcon.myGameObject private
Definition at line 10 of file GameObjectIcon.java.
Referenced by authoring.view.icons.GameObjectIcon.getGameObject().
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/voogasalad_BitsPlease/repository/src/authoring/view/icons/GameObjectIcon.java