voogasalad_BitsPlease: engine.actions.RotateImageTypeAction Class Reference
engine.actions.RotateImageTypeAction Class Reference
Public Member Functions
RotateImageTypeAction (String type, Double angle)
void initialize (GameManager manager)
void execute ()
Protected Attributes
transient GameObjectsCollection myGameObjects
transient Level myCurrentLevel
String myType
Double myAngle
Detailed Description
Definition at line 8 of file RotateImageTypeAction.java.
Constructor & Destructor Documentation
engine.actions.RotateImageTypeAction.RotateImageTypeAction (String type, Double angle)
Definition at line 15 of file RotateImageTypeAction.java.
Member Function Documentation
void engine.actions.RotateImageTypeAction.execute ()
Will execute the consequences resulting from applying an Action.
Parameters
action
Implements engine.actions.Action.
Definition at line 26 of file RotateImageTypeAction.java.
void engine.actions.RotateImageTypeAction.initialize (GameManager manager)
Implements engine.actions.Initializable.
Definition at line 21 of file RotateImageTypeAction.java.
References engine.level.LevelManager.getCurrentLevel(), engine.level.Level.getGameObjectsCollection(), and engine.GameManager.getLevelManager().
Member Data Documentation
Double engine.actions.RotateImageTypeAction.myAngle protected
Definition at line 13 of file RotateImageTypeAction.java.
transient Level engine.actions.RotateImageTypeAction.myCurrentLevel protected
Definition at line 11 of file RotateImageTypeAction.java.
transient GameObjectsCollection engine.actions.RotateImageTypeAction.myGameObjects protected
Definition at line 10 of file RotateImageTypeAction.java.
String engine.actions.RotateImageTypeAction.myType protected
Definition at line 12 of file RotateImageTypeAction.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/voogasalad_BitsPlease/repository/src/engine/actions/RotateImageTypeAction.java