voogasalad_BitsPlease: authoring.view.icons.LevelIcon Class Reference
authoring.view.icons.LevelIcon Class Reference
Public Member Functions
LevelIcon (String s, GameHandler[] events, Level l, GameHandler...levelEvents)
Level getLevel ()
GameHandler[] getLevelEvents ()
Properties makeProperties ()
Public Member Functions inherited from authoring.view.icons.TextIcon
TextIcon (String s, GameHandler...events)
void setupGraphic ()
abstract Properties makeProperties ()
Public Member Functions inherited from authoring.view.icons.BaseIcon
BaseIcon (String label, GameHandler...handler)
void addLabel ()
String getName ()
Static Public Attributes
static final int DEFAULT_FONT_SIZE = 20
Static Public Attributes inherited from authoring.view.icons.TextIcon
static final int DEFAULT_FONT_SIZE = 20
Private Attributes
Level myLevel
GameHandler[] myLevelEvents
Additional Inherited Members
Protected Attributes inherited from authoring.view.icons.BaseIcon
GameHandler[] myOnClick
String myLabel
Detailed Description
Author
Kevin Li
Chris Bernt
Wesley Valentine
Arjun Jain
Definition at line 16 of file LevelIcon.java.
Constructor & Destructor Documentation
authoring.view.icons.LevelIcon.LevelIcon (String s, GameHandler[] events, Level l, GameHandler... levelEvents)
Definition at line 22 of file LevelIcon.java.
Member Function Documentation
Level authoring.view.icons.LevelIcon.getLevel ()
Definition at line 29 of file LevelIcon.java.
References authoring.view.icons.LevelIcon.myLevel.
Referenced by authoring.eventhandlers.LevelToViewHandler.handle(), authoring.view.propertiesview.LevelProperties.initializeProperties(), and authoring.view.icons.LevelIcon.makeProperties().
GameHandler [] authoring.view.icons.LevelIcon.getLevelEvents ()
Definition at line 33 of file LevelIcon.java.
References authoring.view.icons.LevelIcon.myLevelEvents.
Referenced by authoring.eventhandlers.LevelToViewHandler.handle().
Properties authoring.view.icons.LevelIcon.makeProperties ()
Implements authoring.view.icons.IPropertiesMaker.
Definition at line 38 of file LevelIcon.java.
References authoring.view.icons.LevelIcon.getLevel().
Member Data Documentation
final int authoring.view.icons.LevelIcon.DEFAULT_FONT_SIZE = 20 static
Definition at line 18 of file LevelIcon.java.
Level authoring.view.icons.LevelIcon.myLevel private
Definition at line 19 of file LevelIcon.java.
Referenced by authoring.view.icons.LevelIcon.getLevel().
GameHandler [] authoring.view.icons.LevelIcon.myLevelEvents private
Definition at line 20 of file LevelIcon.java.
Referenced by authoring.view.icons.LevelIcon.getLevelEvents().
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/voogasalad_BitsPlease/repository/src/authoring/view/icons/LevelIcon.java