voogasalad_BitsPlease: engine.actions.MakeNewObjectFromObjectAction Class Reference
engine.actions.MakeNewObjectFromObjectAction Class Reference
Public Member Functions
MakeNewObjectFromObjectAction (String type, Identifier id)
void initialize (GameManager gameManager)
void execute ()
Public Member Functions inherited from engine.actions.MakeNewObjectAction
MakeNewObjectAction (String type)
void initialize (GameManager manager)
Private Attributes
Identifier objectID
transient GameObject myObject
Additional Inherited Members
Protected Attributes inherited from engine.actions.MakeNewObjectAction
transient Level myCurrentLevel
transient GameObjectsCollection myMasterList
transient GameObjectRenderer myRenderer
String myType
transient Random r
Detailed Description
Definition at line 10 of file MakeNewObjectFromObjectAction.java.
Constructor & Destructor Documentation
engine.actions.MakeNewObjectFromObjectAction.MakeNewObjectFromObjectAction (String type, Identifier id)
Definition at line 15 of file MakeNewObjectFromObjectAction.java.
Member Function Documentation
void engine.actions.MakeNewObjectFromObjectAction.execute ()
Will execute the consequences resulting from applying an Action.
Parameters
action
Implements engine.actions.Action.
Definition at line 28 of file MakeNewObjectFromObjectAction.java.
References engine.level.Level.addGameObject(), engine.render.GameObjectRenderer.createAndAssignRenderedNode(), engine.gameObject.GameObject.getOrientation(), engine.gameObject.GameObject.getTranslateX(), engine.gameObject.GameObject.getTranslateY(), engine.actions.MakeNewObjectAction.myCurrentLevel, engine.actions.MakeNewObjectAction.myMasterList, engine.actions.MakeNewObjectAction.myRenderer, engine.actions.MakeNewObjectAction.myType, engine.gameObject.GameObject.setIdentifier(), engine.gameObject.GameObject.setOrientation(), and engine.gameObject.GameObject.setPhysicsBody().
void engine.actions.MakeNewObjectFromObjectAction.initialize (GameManager gameManager)
Implements engine.actions.Initializable.
Definition at line 21 of file MakeNewObjectFromObjectAction.java.
References engine.GameManager.objectForIdentifier().
Member Data Documentation
transient GameObject engine.actions.MakeNewObjectFromObjectAction.myObject private
Definition at line 13 of file MakeNewObjectFromObjectAction.java.
Identifier engine.actions.MakeNewObjectFromObjectAction.objectID private
Definition at line 12 of file MakeNewObjectFromObjectAction.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/voogasalad_BitsPlease/repository/src/engine/actions/MakeNewObjectFromObjectAction.java