voogasalad_BitsPlease: authoring.view.wizards.ConditionChoicesVBox Class Reference
authoring.view.wizards.ConditionChoicesVBox Class Reference
Public Member Functions
ConditionChoicesVBox ()
void initializeGroup ()
String getSelected ()
Static Public Attributes
static final ResourceBundle CONDITIONS_PARAMETERS
Private Attributes
ToggleGroup myToggleGroup
Detailed Description
Author
Kevin Li
Chris Bernt
Wesley Valentine
Arjun Jain
Definition at line 15 of file ConditionChoicesVBox.java.
Constructor & Destructor Documentation
authoring.view.wizards.ConditionChoicesVBox.ConditionChoicesVBox ()
Definition at line 21 of file ConditionChoicesVBox.java.
References authoring.view.wizards.ConditionChoicesVBox.initializeGroup().
Member Function Documentation
String authoring.view.wizards.ConditionChoicesVBox.getSelected ()
Definition at line 37 of file ConditionChoicesVBox.java.
Referenced by authoring.view.wizards.ConditionSelectionWizard.getSelectedCondition().
void authoring.view.wizards.ConditionChoicesVBox.initializeGroup ()
Definition at line 25 of file ConditionChoicesVBox.java.
Referenced by authoring.view.wizards.ConditionChoicesVBox.ConditionChoicesVBox().
Member Data Documentation
final ResourceBundle authoring.view.wizards.ConditionChoicesVBox.CONDITIONS_PARAMETERS static
Initial value:
= ResourceBundle
            .getBundle("assets.conditionsParameters")
Definition at line 18 of file ConditionChoicesVBox.java.
ToggleGroup authoring.view.wizards.ConditionChoicesVBox.myToggleGroup private
Definition at line 17 of file ConditionChoicesVBox.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/voogasalad_BitsPlease/repository/src/authoring/view/wizards/ConditionChoicesVBox.java