voogasalad_BitsPlease: authoring.view.wizards.NameWizard Class Reference
authoring.view.wizards.NameWizard Class Reference abstract
Public Member Functions
NameWizard (String title, double width, double height, EventHandler< ActionEvent > event, GameObjectsCollection col)
VBox initializeWizard (EventHandler< ActionEvent > event)
boolean isDuplicated (String s)
Public Member Functions inherited from authoring.view.wizards.Wizard
Wizard (String title, double width, double height, EventHandler< ActionEvent > event)
abstract VBox initializeWizard (EventHandler< ActionEvent > event)
void addMapToWindow ()
Map< String, PropertyTextField > getMap ()
Protected Member Functions
abstract String getIdentifierComponent (GameObject g)
Private Attributes
GameObjectsCollection myCollection
Additional Inherited Members
Protected Attributes inherited from authoring.view.wizards.Wizard
Map< String, PropertyTextField > myMap
VBox myWindow
String myTitle
Group myRoot
Detailed Description
Author
Kevin Li
Chris Bernt
Wesley Valentine
Arjun Jain
Definition at line 17 of file NameWizard.java.
Constructor & Destructor Documentation
authoring.view.wizards.NameWizard.NameWizard (String title, double width, double height, EventHandler< ActionEvent > event, GameObjectsCollection col)
Definition at line 21 of file NameWizard.java.
Member Function Documentation
abstract String authoring.view.wizards.NameWizard.getIdentifierComponent (GameObject g) abstract protected
Gets the desired identifier component. Determines if the duplicate check is for the type or unique ID of the game object.
Parameters
g GameObject to be checked
Returns
The type ID or unique ID of the game object
Referenced by authoring.view.wizards.NameWizard.isDuplicated().
VBox authoring.view.wizards.NameWizard.initializeWizard (EventHandler< ActionEvent > event)
Definition at line 28 of file NameWizard.java.
References authoring.view.wizards.Wizard.myMap, authoring.view.wizards.Wizard.myTitle, and authoring.view.wizards.Wizard.myWindow.
boolean authoring.view.wizards.NameWizard.isDuplicated (String s)
Definition at line 41 of file NameWizard.java.
References authoring.view.wizards.NameWizard.getIdentifierComponent().
Referenced by authoring.eventhandlers.SaveAsNewHandler.updateName(), authoring.eventhandlers.AddObjectHandler.updateName(), and authoring.eventhandlers.GameObjectDragToLevelHandler.updateName().
Member Data Documentation
GameObjectsCollection authoring.view.wizards.NameWizard.myCollection private
Definition at line 19 of file NameWizard.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/voogasalad_BitsPlease/repository/src/authoring/view/wizards/NameWizard.java