voogasalad_BitsPlease: authoring.eventhandlers.AddConditionHandler Class Reference
authoring.eventhandlers.AddConditionHandler Class Reference
Public Member Functions
AddConditionHandler (ConditionsCollection conditions)
void handle (Event arg0)
EventType< Event > getEventType ()
Public Member Functions inherited from authoring.eventhandlers.GameHandler< Event >
void handle (T arg0)
EventType< T > getEventType ()
Private Member Functions
void createCondition ()
void fillConditionParameters ()
List< Object > convertInputParameters ()
void finishCondition ()
Private Attributes
ConditionSelectionWizard mySelectionWizard
ConditionParameterWizard myCPW
ActionChoiceWizard myActionChoiceWizard
List< String > myInputParameters
Map< String, String > displayMap
Parameter[] myParameterTypes
Class<?> classType
Constructor myConstructor
ConditionsCollection myConditionsCollection
Static Private Attributes
static final String CONDITION_PATH_START = "engine.conditions."
static final int WIZARD_WIDTH = 300
static final int WIZARD_HEIGHT = 600
Detailed Description
Definition at line 24 of file AddConditionHandler.java.
Constructor & Destructor Documentation
authoring.eventhandlers.AddConditionHandler.AddConditionHandler (ConditionsCollection conditions)
Definition at line 42 of file AddConditionHandler.java.
Member Function Documentation
List<Object> authoring.eventhandlers.AddConditionHandler.convertInputParameters () private
Definition at line 111 of file AddConditionHandler.java.
References errorsAndExceptions.ErrorPopUp.display().
Referenced by authoring.eventhandlers.AddConditionHandler.finishCondition().
void authoring.eventhandlers.AddConditionHandler.createCondition () private
Definition at line 57 of file AddConditionHandler.java.
References errorsAndExceptions.ErrorPopUp.display(), authoring.eventhandlers.AddConditionHandler.fillConditionParameters(), and authoring.view.wizards.ConditionSelectionWizard.getSelectedCondition().
Referenced by authoring.eventhandlers.AddConditionHandler.handle().
void authoring.eventhandlers.AddConditionHandler.fillConditionParameters () private
Definition at line 87 of file AddConditionHandler.java.
References authoring.view.wizards.ConditionSelectionWizard.disableSelection(), authoring.view.wizards.ConditionSelectionWizard.enableFinalize(), authoring.eventhandlers.AddConditionHandler.finishCondition(), and authoring.view.wizards.Wizard.getMap().
Referenced by authoring.eventhandlers.AddConditionHandler.createCondition().
void authoring.eventhandlers.AddConditionHandler.finishCondition () private
Definition at line 163 of file AddConditionHandler.java.
References authoring.model.collections.ConditionsCollection.add(), authoring.eventhandlers.AddConditionHandler.convertInputParameters(), errorsAndExceptions.ErrorPopUp.display(), authoring.view.wizards.Wizard.getMap(), engine.conditions.Condition.setIdentifier(), and engine.conditions.Condition.setInputMap().
Referenced by authoring.eventhandlers.AddConditionHandler.fillConditionParameters().
EventType<Event> authoring.eventhandlers.AddConditionHandler.getEventType ()
Definition at line 53 of file AddConditionHandler.java.
void authoring.eventhandlers.AddConditionHandler.handle (Event arg0)
Definition at line 47 of file AddConditionHandler.java.
References authoring.eventhandlers.AddConditionHandler.createCondition().
Member Data Documentation
Class<?> authoring.eventhandlers.AddConditionHandler.classType private
Definition at line 37 of file AddConditionHandler.java.
final String authoring.eventhandlers.AddConditionHandler.CONDITION_PATH_START = "engine.conditions." static private
Definition at line 26 of file AddConditionHandler.java.
Map<String,String> authoring.eventhandlers.AddConditionHandler.displayMap private
Definition at line 35 of file AddConditionHandler.java.
ActionChoiceWizard authoring.eventhandlers.AddConditionHandler.myActionChoiceWizard private
Definition at line 32 of file AddConditionHandler.java.
ConditionsCollection authoring.eventhandlers.AddConditionHandler.myConditionsCollection private
Definition at line 40 of file AddConditionHandler.java.
Constructor authoring.eventhandlers.AddConditionHandler.myConstructor private
Definition at line 38 of file AddConditionHandler.java.
ConditionParameterWizard authoring.eventhandlers.AddConditionHandler.myCPW private
Definition at line 31 of file AddConditionHandler.java.
List<String> authoring.eventhandlers.AddConditionHandler.myInputParameters private
Definition at line 34 of file AddConditionHandler.java.
Parameter [] authoring.eventhandlers.AddConditionHandler.myParameterTypes private
Definition at line 36 of file AddConditionHandler.java.
ConditionSelectionWizard authoring.eventhandlers.AddConditionHandler.mySelectionWizard private
Definition at line 30 of file AddConditionHandler.java.
final int authoring.eventhandlers.AddConditionHandler.WIZARD_HEIGHT = 600 static private
Definition at line 28 of file AddConditionHandler.java.
final int authoring.eventhandlers.AddConditionHandler.WIZARD_WIDTH = 300 static private
Definition at line 27 of file AddConditionHandler.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/voogasalad_BitsPlease/repository/src/authoring/eventhandlers/AddConditionHandler.java