voogasalad_BitsPlease: authoring.model.collections.ConditionsCollection Class Reference
authoring.model.collections.ConditionsCollection Class Reference
Public Member Functions
List< Identifier > getIdentifierList ()
void removeByID (String id)
void add (Condition a)
Public Member Functions inherited from authoring.model.collections.GeneralCollection< Condition >
GeneralCollection ()
Iterator< T > iterator ()
T get (int i)
boolean remove (T a)
void add (T a)
void addAll (GeneralCollection< T > collection)
String toString ()
int getSize ()
Additional Inherited Members
Protected Attributes inherited from authoring.model.collections.GeneralCollection< Condition >
List< T > myObjects
Detailed Description
Author
Kevin Li
Arjun Jain
Chris Bernt
Wesley Valentine
Definition at line 16 of file ConditionsCollection.java.
Member Function Documentation
void authoring.model.collections.ConditionsCollection.add (Condition a)
Definition at line 38 of file ConditionsCollection.java.
References authoring.model.collections.GeneralCollection< Condition >.myObjects.
Referenced by authoring.model.AuthoringModel.convertFromSerializable(), authoring.model.AuthoringModel.convertToSerializable(), engine.tests.MainEngineTests.createGameObject(), games.MarioGameTest.createGameObject(), gamePlayer.model.PlayerModel.extractButtonConditions(), and authoring.eventhandlers.AddConditionHandler.finishCondition().
List<Identifier> authoring.model.collections.ConditionsCollection.getIdentifierList ()
Definition at line 18 of file ConditionsCollection.java.
References engine.conditions.Condition.getIdentifier().
Referenced by engine.tests.MainEngineTests.createGameObject(), and games.MarioGameTest.createGameObject().
void authoring.model.collections.ConditionsCollection.removeByID (String id)
Definition at line 26 of file ConditionsCollection.java.
References authoring.model.collections.GeneralCollection< Condition >.myObjects.
Referenced by authoring.eventhandlers.DeleteConditionHandler.deleteCondition().
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/voogasalad_BitsPlease/repository/src/authoring/model/collections/ConditionsCollection.java