voogasalad_BitsPlease: application.SplashScreen Class Reference
application.SplashScreen Class Reference
Public Member Functions
SplashScreen ()
void show ()
Protected Attributes
Stage myStage
Private Member Functions
void initializeGUIElements ()
void author ()
void play () throws IOException
Private Attributes
Scene myScene
BorderPane myPane
Text myTitleText
Button myAuthorButton
Button myPlayButton
AuthoringScene myAuthoringScene
PlayerModel myPlayerModel
Static Private Attributes
static final double SCREEN_WIDTH
static final double SCREEN_HEIGHT
Detailed Description
Author
Abhishek B
Safkat Islam
Definition at line 23 of file SplashScreen.java.
Constructor & Destructor Documentation
application.SplashScreen.SplashScreen ()
Definition at line 38 of file SplashScreen.java.
References application.SplashScreen.initializeGUIElements().
Member Function Documentation
void application.SplashScreen.author () private
Definition at line 78 of file SplashScreen.java.
References authoring.view.AuthoringScene.getScene().
Referenced by application.SplashScreen.initializeGUIElements().
void application.SplashScreen.initializeGUIElements () private
Definition at line 51 of file SplashScreen.java.
References application.SplashScreen.author(), and application.SplashScreen.play().
Referenced by application.SplashScreen.SplashScreen().
void application.SplashScreen.play () throws IOException private
Definition at line 89 of file SplashScreen.java.
References gamePlayer.model.PlayerModel.initializeView().
Referenced by application.SplashScreen.initializeGUIElements().
void application.SplashScreen.show ()
Definition at line 47 of file SplashScreen.java.
Referenced by gamePlayer.model.PlayerModel.exitFromGame(), and application.Main.start().
Member Data Documentation
Button application.SplashScreen.myAuthorButton private
Definition at line 32 of file SplashScreen.java.
AuthoringScene application.SplashScreen.myAuthoringScene private
Definition at line 34 of file SplashScreen.java.
BorderPane application.SplashScreen.myPane private
Definition at line 30 of file SplashScreen.java.
Button application.SplashScreen.myPlayButton private
Definition at line 33 of file SplashScreen.java.
PlayerModel application.SplashScreen.myPlayerModel private
Definition at line 35 of file SplashScreen.java.
Scene application.SplashScreen.myScene private
Definition at line 25 of file SplashScreen.java.
Stage application.SplashScreen.myStage protected
Definition at line 36 of file SplashScreen.java.
Text application.SplashScreen.myTitleText private
Definition at line 31 of file SplashScreen.java.
final double application.SplashScreen.SCREEN_HEIGHT static private
Initial value:
= Screen.getPrimary()
            .getVisualBounds().getHeight() * 4 / 5
Definition at line 28 of file SplashScreen.java.
final double application.SplashScreen.SCREEN_WIDTH static private
Initial value:
= Screen.getPrimary()
            .getVisualBounds().getWidth() * 3 / 4
Definition at line 26 of file SplashScreen.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/voogasalad_BitsPlease/repository/src/application/SplashScreen.java