voogasalad_BitsPlease: engine.physics.Vector Class Reference
engine.physics.Vector Class Reference
Public Member Functions
Vector (double x, double y)
Vector ()
double getX ()
double getY ()
Vector getVector ()
void delta (double x, double y)
void delta (Vector vector)
double getMagnitude ()
void scalarMultiplication (double multiply)
void setX (double x)
void setY (double y)
Public Member Functions inherited from engine.physics.PhysicsComponent
String toString ()
Protected Member Functions
void calculateMagnitude ()
void constructionHelper (double x, double y)
Protected Attributes
double myXComponent
Package Attributes
double myYComponent
double myMagnitude
Detailed Description
super for vector valued components
Author
Ben
Definition at line 9 of file Vector.java.
Constructor & Destructor Documentation
engine.physics.Vector.Vector (double x, double y)
Definition at line 12 of file Vector.java.
References engine.physics.Vector.constructionHelper().
engine.physics.Vector.Vector ()
Definition at line 16 of file Vector.java.
Member Function Documentation
void engine.physics.Vector.calculateMagnitude () protected
calculates magnitude of a vector
Definition at line 23 of file Vector.java.
Referenced by engine.physics.Vector.constructionHelper(), engine.physics.Vector.delta(), engine.physics.Vector.scalarMultiplication(), engine.physics.Vector.setX(), and engine.physics.Vector.setY().
void engine.physics.Vector.constructionHelper (double x, double y) protected
used to overcome a problem with the constructor and super classes
Parameters
x
y
Definition at line 34 of file Vector.java.
References engine.physics.Vector.calculateMagnitude().
Referenced by engine.physics.Vector.Vector().
void engine.physics.Vector.delta (double x, double y)
adds two doubles to current x,y values
Parameters
x -add to x
y -add to y
Definition at line 75 of file Vector.java.
References engine.physics.Vector.calculateMagnitude().
Referenced by engine.gameObject.components.PhysicsBody.changeVelocity(), engine.physics.Vector.delta(), and engine.gameObject.components.PhysicsBody.doImpulses().
void engine.physics.Vector.delta (Vector vector)
same as other delta
Parameters
vector -same as other thing, just a vector instead of x and y doubles
Definition at line 88 of file Vector.java.
References engine.physics.Vector.delta(), engine.physics.Vector.getX(), and engine.physics.Vector.getY().
double engine.physics.Vector.getMagnitude ()
getter for magnitude of vector
Returns
magnitude of vector
Definition at line 97 of file Vector.java.
References engine.physics.Vector.myMagnitude.
Referenced by engine.gameObject.components.PhysicsBody.handleCollision(), and engine.tests.PhysicsBodyTesting.main().
Vector engine.physics.Vector.getVector ()
getter for the vector
Returns
this
Definition at line 63 of file Vector.java.
double engine.physics.Vector.getX ()
getter for x value
Returns
x value
Definition at line 45 of file Vector.java.
References engine.physics.Vector.myXComponent.
Referenced by engine.gameObject.components.PhysicsBody.changeAcceleration(), engine.gameObject.components.PhysicsBody.changeVelocity(), engine.physics.Vector.delta(), engine.collision.objects.CollisionComposition.fixedCollision(), engine.gameObject.components.PhysicsBody.handleCollision(), authoring.view.propertiesview.GameObjectProperties.initializeProperties(), engine.collision.objects.CollisionComposition.isOnXAxis(), engine.gameObject.components.PhysicsBody.reverseVelocity(), and engine.gameObject.components.PhysicsBody.updatePhysicalCharacteristics().
double engine.physics.Vector.getY ()
getter for y value
Returns
y value
Definition at line 54 of file Vector.java.
References engine.physics.Vector.myYComponent.
Referenced by engine.gameObject.components.PhysicsBody.changeAcceleration(), engine.gameObject.components.PhysicsBody.changeVelocity(), engine.physics.Vector.delta(), engine.collision.objects.CollisionComposition.fixedCollision(), engine.gameObject.components.PhysicsBody.handleCollision(), authoring.view.propertiesview.GameObjectProperties.initializeProperties(), engine.collision.objects.CollisionComposition.isOnXAxis(), engine.gameObject.components.PhysicsBody.reverseVelocity(), and engine.gameObject.components.PhysicsBody.updatePhysicalCharacteristics().
void engine.physics.Vector.scalarMultiplication (double multiply)
scalar multiplication
Parameters
multiply what scalar you're multiplying by
Definition at line 107 of file Vector.java.
References engine.physics.Vector.calculateMagnitude().
void engine.physics.Vector.setX (double x)
Definition at line 113 of file Vector.java.
References engine.physics.Vector.calculateMagnitude().
Referenced by engine.gameObject.components.PhysicsBody.balanceForces().
void engine.physics.Vector.setY (double y)
Definition at line 119 of file Vector.java.
References engine.physics.Vector.calculateMagnitude().
Referenced by engine.gameObject.components.PhysicsBody.balanceForces().
Member Data Documentation
double engine.physics.Vector.myMagnitude package
Definition at line 10 of file Vector.java.
Referenced by engine.physics.Force.calculateMagnitude(), and engine.physics.Vector.getMagnitude().
double engine.physics.Vector.myXComponent protected
Definition at line 10 of file Vector.java.
Referenced by engine.physics.Vector.getX(), and engine.physics.Force.getX().
double engine.physics.Vector.myYComponent package
Definition at line 10 of file Vector.java.
Referenced by engine.physics.Vector.getY(), and engine.physics.Force.getY().
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/voogasalad_BitsPlease/repository/src/engine/physics/Vector.java