voogasalad_BitsPlease: engine.tests.MainEngineTests Class Reference
engine.tests.MainEngineTests Class Reference
Public Member Functions
void start (Stage arg0) throws Exception
void createGameObject (Group group)
Static Public Member Functions
static void main (String[] args) throws Exception
Private Attributes
GameManager myGameManager
Stage myStage
Scene myScene
Group myRootGroup
Detailed Description
Definition at line 48 of file MainEngineTests.java.
Member Function Documentation
void engine.tests.MainEngineTests.createGameObject (Group group)
Definition at line 81 of file MainEngineTests.java.
References authoring.model.collections.LevelsCollection.add(), authoring.model.collections.ConditionsCollection.add(), authoring.model.collections.GeneralCollection< T >.add(), authoring.model.collections.GeneralCollection< T >.addAll(), engine.gameObject.components.PhysicsBody.addForce(), engine.gameObject.components.PhysicsBody.addScalar(), authoring.model.collections.GeneralCollection< T >.get(), engine.gameObject.GameObject.getIdentifier(), authoring.model.collections.ConditionsCollection.getIdentifierList(), authoring.model.collections.GameObjectsCollection.getIdentifierList(), engine.GameManager.initialize(), engine.level.Level.setBackgroundImage(), engine.level.Level.setBackgroundMusic(), engine.conditions.Condition.setIdentifier(), engine.level.Level.setIdentifier(), engine.gameObject.GameObject.setIdentifier(), engine.gameObject.GameObject.setLabel(), and engine.gameObject.GameObject.setPhysicsBody().
Referenced by engine.tests.MainEngineTests.start().
static void engine.tests.MainEngineTests.main (String[] args) throws Exception static
Definition at line 62 of file MainEngineTests.java.
void engine.tests.MainEngineTests.start (Stage arg0) throws Exception
Definition at line 67 of file MainEngineTests.java.
References engine.conditions.ButtonConditionManager.beginListeningToScene(), engine.tests.MainEngineTests.createGameObject(), and engine.conditions.ButtonConditionManager.getInstance().
Member Data Documentation
GameManager engine.tests.MainEngineTests.myGameManager private
Author
Davis
the sandbox for engine used to get stuff on the screen and keep engine team morale high
Definition at line 57 of file MainEngineTests.java.
Group engine.tests.MainEngineTests.myRootGroup private
Definition at line 60 of file MainEngineTests.java.
Scene engine.tests.MainEngineTests.myScene private
Definition at line 59 of file MainEngineTests.java.
Stage engine.tests.MainEngineTests.myStage private
Definition at line 58 of file MainEngineTests.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/voogasalad_BitsPlease/repository/src/engine/tests/MainEngineTests.java