voogasalad_BitsPlease: engine.actions.MakeNewObjectFromLocationAction Class Reference
engine.actions.MakeNewObjectFromLocationAction Class Reference
Public Member Functions
MakeNewObjectFromLocationAction (String type, Double x, Double y)
void execute ()
Public Member Functions inherited from engine.actions.MakeNewObjectAction
MakeNewObjectAction (String type)
void initialize (GameManager manager)
Private Attributes
Double myX
Double myY
Additional Inherited Members
Protected Attributes inherited from engine.actions.MakeNewObjectAction
transient Level myCurrentLevel
transient GameObjectsCollection myMasterList
transient GameObjectRenderer myRenderer
String myType
transient Random r
Detailed Description
Definition at line 8 of file MakeNewObjectFromLocationAction.java.
Constructor & Destructor Documentation
engine.actions.MakeNewObjectFromLocationAction.MakeNewObjectFromLocationAction (String type, Double x, Double y)
Definition at line 13 of file MakeNewObjectFromLocationAction.java.
Member Function Documentation
void engine.actions.MakeNewObjectFromLocationAction.execute ()
Will execute the consequences resulting from applying an Action.
Parameters
action
Implements engine.actions.Action.
Definition at line 21 of file MakeNewObjectFromLocationAction.java.
References authoring.model.collections.GeneralCollection< T >.add(), engine.render.GameObjectRenderer.createAndAssignRenderedNode(), engine.level.Level.getGameObjectsCollection(), engine.actions.MakeNewObjectAction.myCurrentLevel, engine.actions.MakeNewObjectAction.myMasterList, engine.actions.MakeNewObjectAction.myRenderer, engine.actions.MakeNewObjectAction.myType, engine.gameObject.GameObject.setIdentifier(), and engine.gameObject.GameObject.setPhysicsBody().
Member Data Documentation
Double engine.actions.MakeNewObjectFromLocationAction.myX private
Definition at line 10 of file MakeNewObjectFromLocationAction.java.
Double engine.actions.MakeNewObjectFromLocationAction.myY private
Definition at line 11 of file MakeNewObjectFromLocationAction.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/voogasalad_BitsPlease/repository/src/engine/actions/MakeNewObjectFromLocationAction.java