voogasalad_BitsPlease: authoring.eventhandlers.GameObjectDragHandler Class Reference
authoring.eventhandlers.GameObjectDragHandler Class Reference
Public Member Functions
GameObjectDragHandler (LevelsView levelView, LevelsCollection data, PropertiesView props)
void handle (MouseEvent event)
EventType< MouseEvent > getEventType ()
Public Member Functions inherited from authoring.eventhandlers.GameHandler< MouseEvent >
void handle (T arg0)
EventType< T > getEventType ()
Private Attributes
LevelsView myLevelView
LevelsCollection myLevelsCollection
PropertiesView myProperties
Detailed Description
Event handler for dragging graphics on the level view. Fills properties view with status and allows user to drag objects to adjust the level.
Author
Kevin Li
Arjun Jain
Chris Bernt
Wesley Valentine
Safkat Islam
Eli Lichtenberg
Definition at line 27 of file GameObjectDragHandler.java.
Constructor & Destructor Documentation
authoring.eventhandlers.GameObjectDragHandler.GameObjectDragHandler (LevelsView levelView, LevelsCollection data, PropertiesView props)
Definition at line 33 of file GameObjectDragHandler.java.
Member Function Documentation
EventType<MouseEvent> authoring.eventhandlers.GameObjectDragHandler.getEventType ()
Definition at line 88 of file GameObjectDragHandler.java.
void authoring.eventhandlers.GameObjectDragHandler.handle (MouseEvent event)
Definition at line 41 of file GameObjectDragHandler.java.
References authoring.view.propertiesview.PropertiesView.displayProperties(), authoring.view.levelview.LevelsView.getCurrentLevel(), authoring.view.icons.GameObjectIcon.getGameObject(), authoring.view.levelview.SingleLevelView.getID(), authoring.view.levelview.SingleLevelView.getPaneHeight(), authoring.view.levelview.SingleLevelView.getPaneWidth(), authoring.view.levelview.SingleLevelView.getViewHeight(), authoring.view.levelview.SingleLevelView.getViewWidth(), engine.gameObject.GameObject.setX(), and engine.gameObject.GameObject.setY().
Member Data Documentation
LevelsCollection authoring.eventhandlers.GameObjectDragHandler.myLevelsCollection private
Definition at line 30 of file GameObjectDragHandler.java.
LevelsView authoring.eventhandlers.GameObjectDragHandler.myLevelView private
Definition at line 29 of file GameObjectDragHandler.java.
PropertiesView authoring.eventhandlers.GameObjectDragHandler.myProperties private
Definition at line 31 of file GameObjectDragHandler.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/voogasalad_BitsPlease/repository/src/authoring/eventhandlers/GameObjectDragHandler.java