voogasalad_BitsPlease: authoring.model.AuthoringModel Class Reference
authoring.model.AuthoringModel Class Reference
Public Member Functions
AuthoringModel ()
GameData getData ()
void save (File dataPath)
void load (GameData input)
void importData (GameData gd)
ImagesCollection getImages ()
GameObjectsCollection getGameObjectCollection ()
LevelsCollection getLevels ()
ConditionsCollection getConditions ()
SoundsCollection getSounds ()
Private Member Functions
GameData convertToSerializable ()
void convertFromSerializable (GameData input)
Private Attributes
GameData myGame
DataManager myDataManager
Detailed Description
The Model of the MVC, gets changes in information from the controller and directly updates the view. Individual components observed by the view.
Author
Arjun Jain
Definition at line 24 of file AuthoringModel.java.
Constructor & Destructor Documentation
authoring.model.AuthoringModel.AuthoringModel ()
Definition at line 28 of file AuthoringModel.java.
Member Function Documentation
void authoring.model.AuthoringModel.convertFromSerializable (GameData input) private
Definition at line 90 of file AuthoringModel.java.
References authoring.model.collections.GeneralCollection< T >.add(), authoring.model.GameData.getConditions(), authoring.model.GameData.getGameObjects(), authoring.model.GameData.getImages(), authoring.model.GameData.getLevels(), authoring.model.GameData.getSounds(), authoring.model.collections.GeneralCollection< T >.remove(), engine.level.Level.setConditionIds(), engine.level.Level.setIdentifier(), and engine.level.Level.setStartIndicator().
Referenced by authoring.model.AuthoringModel.load().
GameData authoring.model.AuthoringModel.convertToSerializable () private
Identifier i = new Identifier(g.getID(),Integer.toString(IDcounter)); g.setIdentifier(i); IDcounter++;
Definition at line 52 of file AuthoringModel.java.
References authoring.model.collections.GeneralCollection< T >.add(), authoring.model.GameData.getConditions(), authoring.model.GameData.getGameObjects(), authoring.model.GameData.getImages(), authoring.model.GameData.getLevels(), authoring.model.GameData.getSounds(), engine.level.Level.setConditionIds(), engine.level.Level.setIdentifier(), and engine.level.Level.setStartIndicator().
Referenced by authoring.model.AuthoringModel.save().
ConditionsCollection authoring.model.AuthoringModel.getConditions ()
Definition at line 152 of file AuthoringModel.java.
References authoring.model.GameData.getConditions().
Referenced by authoring.controller.AuthoringController.initializeGameHandlers(), and authoring.controller.AuthoringController.initializeView().
GameData authoring.model.AuthoringModel.getData ()
Definition at line 33 of file AuthoringModel.java.
References authoring.model.AuthoringModel.myGame.
GameObjectsCollection authoring.model.AuthoringModel.getGameObjectCollection ()
Definition at line 144 of file AuthoringModel.java.
References authoring.model.GameData.getGameObjects().
Referenced by authoring.controller.AuthoringController.initializeGameHandlers(), and authoring.controller.AuthoringController.initializeView().
ImagesCollection authoring.model.AuthoringModel.getImages ()
Definition at line 140 of file AuthoringModel.java.
References authoring.model.GameData.getImages().
Referenced by authoring.controller.AuthoringController.initializeGameHandlers(), and authoring.controller.AuthoringController.initializeView().
LevelsCollection authoring.model.AuthoringModel.getLevels ()
Definition at line 148 of file AuthoringModel.java.
References authoring.model.GameData.getLevels().
Referenced by authoring.controller.AuthoringController.initializeGameHandlers(), and authoring.controller.AuthoringController.initializeView().
SoundsCollection authoring.model.AuthoringModel.getSounds ()
Definition at line 156 of file AuthoringModel.java.
References authoring.model.GameData.getSounds().
Referenced by authoring.controller.AuthoringController.initializeGameHandlers(), and authoring.controller.AuthoringController.initializeView().
void authoring.model.AuthoringModel.importData (GameData gd)
Allows the user to extract certain elements from a GameData object to import into their current project
Parameters
gd Represents the GameData object from which we want to extract elements
Definition at line 135 of file AuthoringModel.java.
void authoring.model.AuthoringModel.load (GameData input)
Replaces the current GameData file with a new file that is loaded in
Definition at line 127 of file AuthoringModel.java.
References authoring.model.AuthoringModel.convertFromSerializable().
Referenced by authoring.controller.AuthoringController.loadData().
void authoring.model.AuthoringModel.save (File dataPath)
Save the current GameData using serialization
Definition at line 40 of file AuthoringModel.java.
References authoring.model.AuthoringModel.convertToSerializable(), data.DataManager.writeGameFile(), and data.DataManager.writeProgressFile().
Referenced by authoring.controller.AuthoringController.saveData().
Member Data Documentation
DataManager authoring.model.AuthoringModel.myDataManager private
Definition at line 26 of file AuthoringModel.java.
GameData authoring.model.AuthoringModel.myGame private
Definition at line 25 of file AuthoringModel.java.
Referenced by authoring.model.AuthoringModel.getData().
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/voogasalad_BitsPlease/repository/src/authoring/model/AuthoringModel.java