voogasalad_BitsPlease: errorsAndExceptions.ErrorPopUp Class Reference
errorsAndExceptions.ErrorPopUp Class Reference
Public Member Functions
ErrorPopUp ()
ErrorPopUp (Exception e)
void display (String errorMessage, boolean throwException) throws VoogaException
Private Member Functions
double chooseStageWidth (double buttonWidth)
Button createButton (VBox vbox, String message, double x, double y, EventHandler< ActionEvent > event)
String getStackTrace ()
Private Attributes
VBox root
Stage popUpStage
Scene myScene
Exception myException
EventHandler< ActionEvent > closePopUp
EventHandler< ActionEvent > viewErrorTrace
Static Private Attributes
static final int MAX_BUTTON_WIDTH = 250
static final int POP_UP_HEIGHT = 200
static final int POP_UP_WIDTH = 300
static final int TEXT_Y_COORD = POP_UP_HEIGHT/2
static final int TEXT_X_COORD = POP_UP_WIDTH/4
static final int BUTTON_Y_COORD = POP_UP_HEIGHT*4/8
static final int BUTTON_X_COORD = POP_UP_WIDTH/2
static final String ERROR_TITLE = "User Error"
static final String BUTTON_TEXT = "OK"
Detailed Description
This class creates a PopUp message used for displaying error messages to the user.
Author
Chris Bernt
Eli Lichtenberg
Safkat Islam
Abhishek Balakrishnan
Definition at line 27 of file ErrorPopUp.java.
Constructor & Destructor Documentation
errorsAndExceptions.ErrorPopUp.ErrorPopUp ()
Constructor without an exception.
Definition at line 47 of file ErrorPopUp.java.
errorsAndExceptions.ErrorPopUp.ErrorPopUp (Exception e)
Constructor with an exception.
Definition at line 59 of file ErrorPopUp.java.
Member Function Documentation
double errorsAndExceptions.ErrorPopUp.chooseStageWidth (double buttonWidth) private
Definition at line 131 of file ErrorPopUp.java.
References errorsAndExceptions.ErrorPopUp.MAX_BUTTON_WIDTH.
Referenced by errorsAndExceptions.ErrorPopUp.display().
Button errorsAndExceptions.ErrorPopUp.createButton (VBox vbox, String message, double x, double y, EventHandler< ActionEvent > event) private
Definition at line 136 of file ErrorPopUp.java.
Referenced by errorsAndExceptions.ErrorPopUp.display().
void errorsAndExceptions.ErrorPopUp.display (String errorMessage, boolean throwException) throws VoogaException
Displays the actual PopUp and throws an exception if needed.
Parameters
errorMessage The message to be displayed.
throwException Whether an exception needed to be thrown.
Exceptions
SLogoException The type of exception to throw.
Definition at line 101 of file ErrorPopUp.java.
References errorsAndExceptions.ErrorPopUp.chooseStageWidth(), and errorsAndExceptions.ErrorPopUp.createButton().
Referenced by gamePlayer.model.PlayerModel.addFileNameChangeListener(), authoring.eventhandlers.AddActionHandler.convertInputParameters(), authoring.eventhandlers.AddConditionHandler.convertInputParameters(), authoring.eventhandlers.AddActionHandler.createAction(), authoring.eventhandlers.AddConditionHandler.createCondition(), authoring.eventhandlers.AddActionHandler.finishAction(), authoring.eventhandlers.AddConditionHandler.finishCondition(), authoring.eventhandlers.FileDropHandler.handle(), authoring.eventhandlers.AddFileHandler.handle(), application.SplashScreen.initializeGUIElements(), authoring.view.ProgramMenu.loadData(), gamePlayer.model.PlayerModel.loadGameFile(), authoring.view.icons.ImageBasedIcon.makeIcon(), authoring.model.AuthoringModel.save(), errorsAndExceptions.ErrorMain.start(), authoring.eventhandlers.SaveAsNewHandler.updateName(), authoring.eventhandlers.AddObjectHandler.updateName(), and authoring.eventhandlers.GameObjectDragToLevelHandler.updateName().
String errorsAndExceptions.ErrorPopUp.getStackTrace () private
Definition at line 147 of file ErrorPopUp.java.
Member Data Documentation
final String errorsAndExceptions.ErrorPopUp.BUTTON_TEXT = "OK" static private
Definition at line 37 of file ErrorPopUp.java.
final int errorsAndExceptions.ErrorPopUp.BUTTON_X_COORD = POP_UP_WIDTH/2 static private
Definition at line 35 of file ErrorPopUp.java.
final int errorsAndExceptions.ErrorPopUp.BUTTON_Y_COORD = POP_UP_HEIGHT*4/8 static private
Definition at line 34 of file ErrorPopUp.java.
EventHandler<ActionEvent> errorsAndExceptions.ErrorPopUp.closePopUp private
Initial value:
= new EventHandler<ActionEvent>() {
        @Override
        public void handle(ActionEvent evt){
            popUpStage.close();
        }
    }
EventHandler to close the PopUp window.
Definition at line 68 of file ErrorPopUp.java.
final String errorsAndExceptions.ErrorPopUp.ERROR_TITLE = "User Error" static private
Definition at line 36 of file ErrorPopUp.java.
final int errorsAndExceptions.ErrorPopUp.MAX_BUTTON_WIDTH = 250 static private
Definition at line 29 of file ErrorPopUp.java.
Referenced by errorsAndExceptions.ErrorPopUp.chooseStageWidth().
Exception errorsAndExceptions.ErrorPopUp.myException private
Definition at line 42 of file ErrorPopUp.java.
Scene errorsAndExceptions.ErrorPopUp.myScene private
Definition at line 40 of file ErrorPopUp.java.
final int errorsAndExceptions.ErrorPopUp.POP_UP_HEIGHT = 200 static private
Definition at line 30 of file ErrorPopUp.java.
final int errorsAndExceptions.ErrorPopUp.POP_UP_WIDTH = 300 static private
Definition at line 31 of file ErrorPopUp.java.
Stage errorsAndExceptions.ErrorPopUp.popUpStage private
Definition at line 39 of file ErrorPopUp.java.
VBox errorsAndExceptions.ErrorPopUp.root private
Definition at line 38 of file ErrorPopUp.java.
final int errorsAndExceptions.ErrorPopUp.TEXT_X_COORD = POP_UP_WIDTH/4 static private
Definition at line 33 of file ErrorPopUp.java.
final int errorsAndExceptions.ErrorPopUp.TEXT_Y_COORD = POP_UP_HEIGHT/2 static private
Definition at line 32 of file ErrorPopUp.java.
EventHandler<ActionEvent> errorsAndExceptions.ErrorPopUp.viewErrorTrace private
Initial value:
= new EventHandler<ActionEvent>() {
        @Override
        public void handle(ActionEvent evt) {
            Stage errorTraceStage = new Stage();
            VBox errorBox = new VBox();
            ScrollPane sp = new ScrollPane();
            Label errorTrace = new Label(getStackTrace());
            errorTrace.setId("error");
            sp.setContent(errorTrace);
            errorBox.getChildren().add(sp);
            errorBox.setVgrow(sp, Priority.ALWAYS);
            Scene scene = new Scene(errorBox, POP_UP_WIDTH*2, POP_UP_HEIGHT*3, Color.LIGHTGRAY);
            scene.getStylesheets().add(getClass().getResource("ErrorStyle.css").toExternalForm());
            errorTraceStage.setScene(scene);
            errorTraceStage.centerOnScreen();
            errorTraceStage.show();
        }
    }
Definition at line 75 of file ErrorPopUp.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/voogasalad_BitsPlease/repository/src/errorsAndExceptions/ErrorPopUp.java