voogasalad_BitsPlease: authoring.eventhandlers.DeleteGameObjectHandler Class Reference
authoring.eventhandlers.DeleteGameObjectHandler Class Reference
Public Member Functions
DeleteGameObjectHandler (LevelsView lv, LevelsCollection levelsCol, PropertiesView props)
void handle (Event arg0)
EventType< Event > getEventType ()
Public Member Functions inherited from authoring.eventhandlers.GameHandler< Event >
void handle (T arg0)
EventType< T > getEventType ()
Private Attributes
LevelsView myLevelsView
LevelsCollection myLevelsCol
PropertiesView myPropertiesView
Detailed Description
Definition at line 10 of file DeleteGameObjectHandler.java.
Constructor & Destructor Documentation
authoring.eventhandlers.DeleteGameObjectHandler.DeleteGameObjectHandler (LevelsView lv, LevelsCollection levelsCol, PropertiesView props)
Definition at line 16 of file DeleteGameObjectHandler.java.
Member Function Documentation
EventType<Event> authoring.eventhandlers.DeleteGameObjectHandler.getEventType ()
Definition at line 36 of file DeleteGameObjectHandler.java.
void authoring.eventhandlers.DeleteGameObjectHandler.handle (Event arg0)
Definition at line 24 of file DeleteGameObjectHandler.java.
References authoring.view.propertiesview.PropertiesView.getCurrentGameObject(), authoring.view.levelview.LevelsView.getCurrentLevel(), and authoring.view.levelview.SingleLevelView.getID().
Member Data Documentation
LevelsCollection authoring.eventhandlers.DeleteGameObjectHandler.myLevelsCol private
Definition at line 13 of file DeleteGameObjectHandler.java.
LevelsView authoring.eventhandlers.DeleteGameObjectHandler.myLevelsView private
Definition at line 12 of file DeleteGameObjectHandler.java.
PropertiesView authoring.eventhandlers.DeleteGameObjectHandler.myPropertiesView private
Definition at line 14 of file DeleteGameObjectHandler.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/voogasalad_BitsPlease/repository/src/authoring/eventhandlers/DeleteGameObjectHandler.java