voogasalad_BitsPlease: authoring.view.icons.BaseIcon Class Reference
authoring.view.icons.BaseIcon Class Reference
Public Member Functions
BaseIcon (String label, GameHandler...handler)
void addLabel ()
String getName ()
Protected Attributes
GameHandler[] myOnClick
String myLabel
Detailed Description
Definition at line 7 of file BaseIcon.java.
Constructor & Destructor Documentation
authoring.view.icons.BaseIcon.BaseIcon (String label, GameHandler... handler)
Definition at line 11 of file BaseIcon.java.
Member Function Documentation
void authoring.view.icons.BaseIcon.addLabel ()
Definition at line 16 of file BaseIcon.java.
Referenced by authoring.view.icons.ImageIcon.ImageIcon(), and authoring.view.icons.SoundIcon.SoundIcon().
String authoring.view.icons.BaseIcon.getName ()
Definition at line 20 of file BaseIcon.java.
References authoring.view.icons.BaseIcon.myLabel.
Referenced by authoring.view.propertiesview.FileProperties.initializeProperties(), authoring.view.propertiesview.LevelProperties.initializeProperties(), and authoring.view.propertiesview.ConditionProperties.initializeProperties().
Member Data Documentation
String authoring.view.icons.BaseIcon.myLabel protected
Definition at line 9 of file BaseIcon.java.
Referenced by authoring.view.icons.SoundIcon.generateMedia(), authoring.view.icons.BaseIcon.getName(), authoring.view.icons.ImageBasedIcon.makeIcon(), and authoring.view.icons.TextIcon.setupGraphic().
GameHandler [] authoring.view.icons.BaseIcon.myOnClick protected
Definition at line 8 of file BaseIcon.java.
Referenced by authoring.view.icons.SoundIcon.makeIcon(), authoring.view.icons.ImageBasedIcon.makeIcon(), and authoring.view.icons.TextIcon.setupGraphic().
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/voogasalad_BitsPlease/repository/src/authoring/view/icons/BaseIcon.java