voogasalad_BitsPlease: gamePlayer.view.keyboardUtility.KeyboardView Class Reference
gamePlayer.view.keyboardUtility.KeyboardView Class Reference
Public Member Functions
KeyboardView (ConditionsCollection buttonConditions)
void createKeyboardView ()
void buildKeyboard ()
void setNewKey (String button, String keyFunction)
Private Member Functions
int buildButton (int num, int i, int j)
ComboBox< String > comboBoxForButton ()
Private Attributes
GridPane myGrid
Stage myStage
ConditionsCollection myButtonConditions
Map< KeyCode, String > myButtonConditionsMap
KeyMapForm myKeyMapForm
MappedKeys myMappedKeys
Static Private Attributes
static final int NUM_KEYS_IN_ROW = 14
static final int NUM_KEYS_IN_COLUMN = 5
static final double KEY_WIDTH = 100
static final double KEY_HEIGHT = 100
static final double WIDTH = KEY_WIDTH * NUM_KEYS_IN_ROW
static final double HEIGHT = KEY_HEIGHT * NUM_KEYS_IN_COLUMN
Detailed Description
Author
Abhishek B
Safkat Islam
Definition at line 26 of file KeyboardView.java.
Constructor & Destructor Documentation
gamePlayer.view.keyboardUtility.KeyboardView.KeyboardView (ConditionsCollection buttonConditions)
Definition at line 41 of file KeyboardView.java.
Member Function Documentation
int gamePlayer.view.keyboardUtility.KeyboardView.buildButton (int num, int i, int j) private
Definition at line 71 of file KeyboardView.java.
References gamePlayer.view.keyboardUtility.KeyMapForm.createKeyMapForm(), and gamePlayer.view.keyboardUtility.MappedKeys.getKey().
Referenced by gamePlayer.view.keyboardUtility.KeyboardView.buildKeyboard().
void gamePlayer.view.keyboardUtility.KeyboardView.buildKeyboard ()
Definition at line 59 of file KeyboardView.java.
References gamePlayer.view.keyboardUtility.KeyboardView.buildButton(), gamePlayer.view.keyboardUtility.KeyboardView.NUM_KEYS_IN_COLUMN, and gamePlayer.view.keyboardUtility.KeyboardView.NUM_KEYS_IN_ROW.
Referenced by gamePlayer.view.keyboardUtility.KeyboardView.createKeyboardView().
ComboBox<String> gamePlayer.view.keyboardUtility.KeyboardView.comboBoxForButton () private
Definition at line 87 of file KeyboardView.java.
References engine.conditions.ButtonPressCondition.getKeyIdentifier(), and authoring.model.collections.GeneralCollection< T >.iterator().
Referenced by gamePlayer.view.keyboardUtility.KeyboardView.createKeyboardView().
void gamePlayer.view.keyboardUtility.KeyboardView.createKeyboardView ()
Definition at line 47 of file KeyboardView.java.
References gamePlayer.view.keyboardUtility.KeyboardView.buildKeyboard(), and gamePlayer.view.keyboardUtility.KeyboardView.comboBoxForButton().
Referenced by gamePlayer.view.MenuBarController.keyCombos().
void gamePlayer.view.keyboardUtility.KeyboardView.setNewKey (String button, String keyFunction)
Definition at line 96 of file KeyboardView.java.
References engine.conditions.ButtonPressCondition.addKey(), gamePlayer.view.keyboardUtility.MappedKeys.getKeyCode(), engine.conditions.ButtonPressCondition.getKeyIdentifier(), engine.conditions.ButtonPressCondition.getKeyList(), and engine.conditions.ButtonPressCondition.removeKey().
Member Data Documentation
final double gamePlayer.view.keyboardUtility.KeyboardView.HEIGHT = KEY_HEIGHT * NUM_KEYS_IN_COLUMN static private
Definition at line 33 of file KeyboardView.java.
final double gamePlayer.view.keyboardUtility.KeyboardView.KEY_HEIGHT = 100 static private
Definition at line 31 of file KeyboardView.java.
final double gamePlayer.view.keyboardUtility.KeyboardView.KEY_WIDTH = 100 static private
Definition at line 30 of file KeyboardView.java.
ConditionsCollection gamePlayer.view.keyboardUtility.KeyboardView.myButtonConditions private
Definition at line 36 of file KeyboardView.java.
Map<KeyCode, String> gamePlayer.view.keyboardUtility.KeyboardView.myButtonConditionsMap private
Definition at line 37 of file KeyboardView.java.
GridPane gamePlayer.view.keyboardUtility.KeyboardView.myGrid private
Definition at line 34 of file KeyboardView.java.
KeyMapForm gamePlayer.view.keyboardUtility.KeyboardView.myKeyMapForm private
Definition at line 38 of file KeyboardView.java.
MappedKeys gamePlayer.view.keyboardUtility.KeyboardView.myMappedKeys private
Definition at line 39 of file KeyboardView.java.
Stage gamePlayer.view.keyboardUtility.KeyboardView.myStage private
Definition at line 35 of file KeyboardView.java.
final int gamePlayer.view.keyboardUtility.KeyboardView.NUM_KEYS_IN_COLUMN = 5 static private
Definition at line 29 of file KeyboardView.java.
Referenced by gamePlayer.view.keyboardUtility.KeyboardView.buildKeyboard().
final int gamePlayer.view.keyboardUtility.KeyboardView.NUM_KEYS_IN_ROW = 14 static private
Definition at line 28 of file KeyboardView.java.
Referenced by gamePlayer.view.keyboardUtility.KeyboardView.buildKeyboard().
final double gamePlayer.view.keyboardUtility.KeyboardView.WIDTH = KEY_WIDTH * NUM_KEYS_IN_ROW static private
Definition at line 32 of file KeyboardView.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/voogasalad_BitsPlease/repository/src/gamePlayer/view/keyboardUtility/KeyboardView.java