voogasalad_BitsPlease: engine.actions.VelocityTypeAction Class Reference
engine.actions.VelocityTypeAction Class Reference abstract
Classes
interface TwoArgInterface
Public Member Functions
VelocityTypeAction (String type, Double value)
void execute ()
void applyPhysics (Collection< GameObject > myObjects)
Public Member Functions inherited from engine.actions.TypeAction
TypeAction (String type)
void initialize (GameManager manager)
Protected Member Functions
TwoArgInterface determineOperation (Collection< GameObject > myObjects, Object value)
abstract Vector determineVector (GameObject object, double value, Vector vector)
void forHelper (Collection< GameObject > myObjects, TwoArgInterface myOperation, Object value)
Protected Attributes
Double myValue
Protected Attributes inherited from engine.actions.TypeAction
transient Level myCurrentLevel
String myType
Detailed Description
Definition at line 13 of file VelocityTypeAction.java.
Constructor & Destructor Documentation
engine.actions.VelocityTypeAction.VelocityTypeAction (String type, Double value)
Definition at line 17 of file VelocityTypeAction.java.
Member Function Documentation
void engine.actions.VelocityTypeAction.applyPhysics (Collection< GameObject > myObjects)
Definition at line 35 of file VelocityTypeAction.java.
References engine.actions.VelocityTypeAction.determineOperation(), and engine.actions.VelocityTypeAction.forHelper().
Referenced by engine.actions.VelocityTypeAction.execute().
TwoArgInterface engine.actions.VelocityTypeAction.determineOperation (Collection< GameObject > myObjects, Object value) protected
Definition at line 39 of file VelocityTypeAction.java.
References engine.actions.VelocityTypeAction.determineVector().
Referenced by engine.actions.VelocityTypeAction.applyPhysics().
abstract Vector engine.actions.VelocityTypeAction.determineVector (GameObject object, double value, Vector vector) abstract protected
Referenced by engine.actions.VelocityTypeAction.determineOperation().
void engine.actions.VelocityTypeAction.execute ()
Will execute the consequences resulting from applying an Action.
Parameters
action
Implements engine.actions.Action.
Definition at line 24 of file VelocityTypeAction.java.
References engine.actions.VelocityTypeAction.applyPhysics(), engine.level.Level.getGameObjectsCollection(), engine.actions.TypeAction.myCurrentLevel, and engine.actions.TypeAction.myType.
void engine.actions.VelocityTypeAction.forHelper (Collection< GameObject > myObjects, TwoArgInterface myOperation, Object value) protected
Definition at line 49 of file VelocityTypeAction.java.
References engine.actions.VelocityTypeAction.TwoArgInterface.operation().
Referenced by engine.actions.VelocityTypeAction.applyPhysics().
Member Data Documentation
Double engine.actions.VelocityTypeAction.myValue protected
Definition at line 15 of file VelocityTypeAction.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/voogasalad_BitsPlease/repository/src/engine/actions/VelocityTypeAction.java