voogasalad_BitsPlease: engine.render.GameObjectRenderer Class Reference
engine.render.GameObjectRenderer Class Reference
Public Member Functions
GameObjectRenderer (Group canvas, String relativePath)
void renderGameObjects (Level level)
void createAndAssignRenderedNode (GameObject obj)
void removeRenderedNode (Identifier nodeID)
void setCameraFocus (GameObject obj)
Private Member Functions
ImageView createImageAndView (GameObject obj)
Label createLabel (GameObject obj)
Node createCollisionBody (GameObject obj)
void setBackGroundImage (Level level)
Private Attributes
Group myCanvas
Map< Identifier, RenderedNode > myRenderedNodes
Level myCurrentLevel
FilePathUtility myFilePathUtility
Static Private Attributes
static final String IMAGES = "images"
static final String BACKGROUND = "background"
Detailed Description
Renders GameObjects on a given Canvas by generating JavaFX nodes and Images from state information
Author
Will Chang
Davis
Definition at line 27 of file GameObjectRenderer.java.
Constructor & Destructor Documentation
engine.render.GameObjectRenderer.GameObjectRenderer (Group canvas, String relativePath)
Constructor takes in a group as the Canvas of the game
Parameters
canvas
relativePath
Definition at line 39 of file GameObjectRenderer.java.
Member Function Documentation
void engine.render.GameObjectRenderer.createAndAssignRenderedNode (GameObject obj)
Generates the JavaFX Node for a GameObject, giving it its image and CollisionBody
Parameters
obj
Definition at line 66 of file GameObjectRenderer.java.
References engine.render.GameObjectRenderer.createCollisionBody(), engine.render.GameObjectRenderer.createImageAndView(), engine.render.GameObjectRenderer.createLabel(), engine.gameObject.GameObject.getID(), engine.gameObject.GameObject.getIdentifier(), engine.gameObject.GameObject.getX(), engine.gameObject.GameObject.getY(), engine.render.RenderedNode.setCollisionBody(), engine.render.RenderedNode.setImageView(), engine.render.RenderedNode.setLabel(), and engine.gameObject.GameObject.setRenderedNode().
Referenced by engine.actions.render.PaintCanvas.applyRender(), engine.actions.MakeNewObjectFromLocationAction.execute(), engine.actions.MakeNewObjectFromObjectAction.execute(), engine.actions.MakeNewRandomObjectAction.makeRandomObject(), and engine.render.GameObjectRenderer.renderGameObjects().
Node engine.render.GameObjectRenderer.createCollisionBody (GameObject obj) private
Creates the CollisionBody of the GameObject
Parameters
sprite
Returns
Definition at line 132 of file GameObjectRenderer.java.
References engine.gameObject.components.PhysicsBody.getCollisionBodyHeight(), engine.gameObject.components.PhysicsBody.getCollisionBodyWidth(), and engine.gameObject.GameObject.getPhysicsBody().
Referenced by engine.render.GameObjectRenderer.createAndAssignRenderedNode().
ImageView engine.render.GameObjectRenderer.createImageAndView (GameObject obj) private
Creates the Image and ImageView for the RenderedNode if specified
Parameters
obj
Returns
Definition at line 86 of file GameObjectRenderer.java.
References engine.gameObject.GameObject.getCurrentImageName(), engine.FilePathUtility.getFilePath(), engine.gameObject.GameObject.getHeight(), and engine.gameObject.GameObject.getWidth().
Referenced by engine.render.GameObjectRenderer.createAndAssignRenderedNode().
Label engine.render.GameObjectRenderer.createLabel (GameObject obj) private
Creates the Label for a given RenderedNode
Parameters
obj
Returns
Definition at line 115 of file GameObjectRenderer.java.
References engine.gameObject.GameObject.getHeight(), engine.gameObject.GameObject.getLabel(), and engine.gameObject.GameObject.getWidth().
Referenced by engine.render.GameObjectRenderer.createAndAssignRenderedNode().
void engine.render.GameObjectRenderer.removeRenderedNode (Identifier nodeID)
Removes a rendered Node from the list of currently rendered Nodes
Parameters
nodeID
Definition at line 147 of file GameObjectRenderer.java.
Referenced by engine.actions.render.EraseCanvas.applyRender(), and engine.actions.DeleteTypeAction.execute().
void engine.render.GameObjectRenderer.renderGameObjects (Level level)
Renders all GameObjects within a Level
Parameters
level
Definition at line 49 of file GameObjectRenderer.java.
References engine.render.GameObjectRenderer.createAndAssignRenderedNode(), engine.level.Level.getGameObjectIterator(), engine.gameObject.GameObject.getIdentifier(), engine.gameObject.Identifier.getUniqueId(), and engine.render.GameObjectRenderer.setBackGroundImage().
Referenced by engine.level.LevelManager.initializeCurrentLevel().
void engine.render.GameObjectRenderer.setBackGroundImage (Level level) private
Definition at line 153 of file GameObjectRenderer.java.
References engine.level.Level.getBackgroundImage(), and engine.FilePathUtility.getFilePath().
Referenced by engine.render.GameObjectRenderer.renderGameObjects().
void engine.render.GameObjectRenderer.setCameraFocus (GameObject obj)
Definition at line 178 of file GameObjectRenderer.java.
Member Data Documentation
final String engine.render.GameObjectRenderer.BACKGROUND = "background" static private
Definition at line 32 of file GameObjectRenderer.java.
final String engine.render.GameObjectRenderer.IMAGES = "images" static private
Definition at line 31 of file GameObjectRenderer.java.
Group engine.render.GameObjectRenderer.myCanvas private
Definition at line 28 of file GameObjectRenderer.java.
Level engine.render.GameObjectRenderer.myCurrentLevel private
Definition at line 30 of file GameObjectRenderer.java.
FilePathUtility engine.render.GameObjectRenderer.myFilePathUtility private
Definition at line 33 of file GameObjectRenderer.java.
Map<Identifier, RenderedNode> engine.render.GameObjectRenderer.myRenderedNodes private
Definition at line 29 of file GameObjectRenderer.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/voogasalad_BitsPlease/repository/src/engine/render/GameObjectRenderer.java