voogasalad_BitsPlease: engine.FilePathUtility Class Reference
engine.FilePathUtility Class Reference
Public Member Functions
FilePathUtility (String folder, String relativePath)
String getFilePath ()
Private Attributes
final String SLASH = "/"
String myPath
Detailed Description
Sets up the filepath
Author
Will
Definition at line 9 of file FilePathUtility.java.
Constructor & Destructor Documentation
engine.FilePathUtility.FilePathUtility (String folder, String relativePath)
Definition at line 13 of file FilePathUtility.java.
References engine.FilePathUtility.SLASH.
Member Function Documentation
String engine.FilePathUtility.getFilePath ()
Definition at line 17 of file FilePathUtility.java.
References engine.FilePathUtility.myPath.
Referenced by engine.render.GameObjectRenderer.createImageAndView(), engine.sound.SoundUtility.makeAudioClip(), engine.sound.SoundUtility.makeMediaPlayer(), and engine.render.GameObjectRenderer.setBackGroundImage().
Member Data Documentation
String engine.FilePathUtility.myPath private
Definition at line 11 of file FilePathUtility.java.
Referenced by engine.FilePathUtility.getFilePath().
final String engine.FilePathUtility.SLASH = "/" private
Definition at line 10 of file FilePathUtility.java.
Referenced by engine.FilePathUtility.FilePathUtility().
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/voogasalad_BitsPlease/repository/src/engine/FilePathUtility.java