voogasalad_BitsPlease: authoring.view.wizards.Wizard Class Reference
authoring.view.wizards.Wizard Class Reference abstract
Public Member Functions
Wizard (String title, double width, double height, EventHandler< ActionEvent > event)
abstract VBox initializeWizard (EventHandler< ActionEvent > event)
void addMapToWindow ()
Map< String, PropertyTextField > getMap ()
Protected Attributes
Map< String, PropertyTextField > myMap
VBox myWindow
String myTitle
Group myRoot
Detailed Description
Author
Kevin Li
Chris Bernt
Wesley Valentine
Arjun Jain
Definition at line 22 of file Wizard.java.
Constructor & Destructor Documentation
authoring.view.wizards.Wizard.Wizard (String title, double width, double height, EventHandler< ActionEvent > event)
Definition at line 29 of file Wizard.java.
References authoring.view.wizards.Wizard.initializeWizard().
Member Function Documentation
void authoring.view.wizards.Wizard.addMapToWindow ()
Definition at line 49 of file Wizard.java.
Map<String, PropertyTextField> authoring.view.wizards.Wizard.getMap ()
Definition at line 55 of file Wizard.java.
References authoring.view.wizards.Wizard.myMap.
Referenced by authoring.eventhandlers.AddConditionIDHandler.addNewCondition(), authoring.eventhandlers.AddObjectHandler.createGameObject(), authoring.eventhandlers.AddLevelHandler.createLevel(), authoring.eventhandlers.DeleteConditionHandler.deleteCondition(), authoring.eventhandlers.DeleteConditionFromLevelHandler.deleteCondition(), authoring.eventhandlers.DeleteLevelHandler.deleteLevel(), authoring.eventhandlers.AddConditionHandler.fillConditionParameters(), authoring.eventhandlers.AddActionHandler.finishAction(), authoring.eventhandlers.AddLevelHandler.getPrompt(), authoring.eventhandlers.SaveAsNewHandler.updateName(), authoring.eventhandlers.AddObjectHandler.updateName(), and authoring.eventhandlers.GameObjectDragToLevelHandler.updateName().
abstract VBox authoring.view.wizards.Wizard.initializeWizard (EventHandler< ActionEvent > event) abstract
Referenced by authoring.view.wizards.Wizard.Wizard().
Member Data Documentation
Map<String, PropertyTextField> authoring.view.wizards.Wizard.myMap protected
Definition at line 24 of file Wizard.java.
Referenced by authoring.view.wizards.Wizard.getMap(), authoring.view.wizards.GameObjectWizard.initializeWizard(), authoring.view.wizards.AddConditionIDWizard.initializeWizard(), authoring.view.wizards.LevelWizard.initializeWizard(), authoring.view.wizards.NameWizard.initializeWizard(), authoring.view.wizards.ConditionSelectionWizard.initializeWizard(), and authoring.view.wizards.ConditionParameterWizard.showParameters().
Group authoring.view.wizards.Wizard.myRoot protected
Definition at line 27 of file Wizard.java.
Referenced by authoring.view.wizards.ActionChoiceWizard.ActionChoiceWizard().
String authoring.view.wizards.Wizard.myTitle protected
Definition at line 26 of file Wizard.java.
Referenced by authoring.view.wizards.AddConditionIDWizard.initializeWizard(), and authoring.view.wizards.NameWizard.initializeWizard().
VBox authoring.view.wizards.Wizard.myWindow protected
Definition at line 25 of file Wizard.java.
Referenced by authoring.view.wizards.ActionChoiceWizard.ActionChoiceWizard(), authoring.view.wizards.AddConditionIDWizard.initializeWizard(), authoring.view.wizards.GameObjectWizard.initializeWizard(), authoring.view.wizards.LevelWizard.initializeWizard(), authoring.view.wizards.NameWizard.initializeWizard(), authoring.view.wizards.ConditionSelectionWizard.initializeWizard(), authoring.view.wizards.ActionChoiceWizard.initializeWizard(), authoring.view.wizards.ConditionParameterWizard.initializeWizard(), and authoring.view.wizards.ConditionParameterWizard.showParameters().
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/voogasalad_BitsPlease/repository/src/authoring/view/wizards/Wizard.java