voogasalad_BitsPlease: engine.gameObject.DefaultData Class Reference
engine.gameObject.DefaultData Class Reference
Public Member Functions
DefaultData (List< Component > defaultComponents, String imagename, double x, double y, double height, double width, double rotation)
List< Component > getComponents ()
String getImageName ()
double getXCoordinate ()
double getYCoordinate ()
double getHeight ()
double getWidth ()
double getRotation ()
Private Attributes
double myRotation
double myHeight
double myWidth
double myXCoord
double myYCoord
String myCurrentImageName
List< Component > myComponents
Detailed Description
Definition at line 8 of file DefaultData.java.
Constructor & Destructor Documentation
engine.gameObject.DefaultData.DefaultData (List< Component > defaultComponents, String imagename, double x, double y, double height, double width, double rotation)
Definition at line 22 of file DefaultData.java.
Member Function Documentation
List<Component> engine.gameObject.DefaultData.getComponents ()
Definition at line 36 of file DefaultData.java.
References engine.gameObject.DefaultData.myComponents.
Referenced by engine.gameObject.GameObject.reset().
double engine.gameObject.DefaultData.getHeight ()
Definition at line 52 of file DefaultData.java.
References engine.gameObject.DefaultData.myHeight.
String engine.gameObject.DefaultData.getImageName ()
Definition at line 40 of file DefaultData.java.
References engine.gameObject.DefaultData.myCurrentImageName.
Referenced by engine.gameObject.GameObject.reset().
double engine.gameObject.DefaultData.getRotation ()
Definition at line 60 of file DefaultData.java.
References engine.gameObject.DefaultData.myRotation.
Referenced by engine.gameObject.GameObject.reset().
double engine.gameObject.DefaultData.getWidth ()
Definition at line 56 of file DefaultData.java.
References engine.gameObject.DefaultData.myWidth.
double engine.gameObject.DefaultData.getXCoordinate ()
Definition at line 44 of file DefaultData.java.
References engine.gameObject.DefaultData.myXCoord.
Referenced by engine.gameObject.GameObject.reset().
double engine.gameObject.DefaultData.getYCoordinate ()
Definition at line 48 of file DefaultData.java.
References engine.gameObject.DefaultData.myYCoord.
Referenced by engine.gameObject.GameObject.reset().
Member Data Documentation
List<Component> engine.gameObject.DefaultData.myComponents private
Definition at line 20 of file DefaultData.java.
Referenced by engine.gameObject.DefaultData.getComponents().
String engine.gameObject.DefaultData.myCurrentImageName private
Definition at line 18 of file DefaultData.java.
Referenced by engine.gameObject.DefaultData.getImageName().
double engine.gameObject.DefaultData.myHeight private
Definition at line 12 of file DefaultData.java.
Referenced by engine.gameObject.DefaultData.getHeight().
double engine.gameObject.DefaultData.myRotation private
Definition at line 10 of file DefaultData.java.
Referenced by engine.gameObject.DefaultData.getRotation().
double engine.gameObject.DefaultData.myWidth private
Definition at line 13 of file DefaultData.java.
Referenced by engine.gameObject.DefaultData.getWidth().
double engine.gameObject.DefaultData.myXCoord private
Definition at line 15 of file DefaultData.java.
Referenced by engine.gameObject.DefaultData.getXCoordinate().
double engine.gameObject.DefaultData.myYCoord private
Definition at line 16 of file DefaultData.java.
Referenced by engine.gameObject.DefaultData.getYCoordinate().
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/voogasalad_BitsPlease/repository/src/engine/gameObject/DefaultData.java