voogasalad_BitsPlease: authoring.eventhandlers.AddLevelHandler Class Reference
authoring.eventhandlers.AddLevelHandler Class Reference
Public Member Functions
AddLevelHandler (LevelsCollection levelsCollection, LevelsView levelView)
void handle (Event arg0)
EventType< Event > getEventType ()
Public Member Functions inherited from authoring.eventhandlers.GameHandler< Event >
void handle (T arg0)
EventType< T > getEventType ()
Private Member Functions
void createLevel ()
void promptLevelID ()
void getPrompt ()
Private Attributes
LevelsView myLevels
LevelsCollection myLevelsCollection
String myLevelID
boolean isFirstLevel
LevelWizard myWizard
Detailed Description
Definition at line 14 of file AddLevelHandler.java.
Constructor & Destructor Documentation
authoring.eventhandlers.AddLevelHandler.AddLevelHandler (LevelsCollection levelsCollection, LevelsView levelView)
Parameters
levelsCollection
levelView WE CAN REMOVE THIS AND PUT IT IN THE UPDATE
Definition at line 28 of file AddLevelHandler.java.
Member Function Documentation
void authoring.eventhandlers.AddLevelHandler.createLevel () private
Definition at line 39 of file AddLevelHandler.java.
References authoring.model.collections.GeneralCollection< T >.add(), authoring.view.levelview.LevelsView.addNewLevel(), data.Observable.addObserver(), authoring.view.wizards.Wizard.getMap(), engine.level.Level.setBackgroundImage(), engine.level.Level.setBackgroundMusic(), authoring.view.levelview.SingleLevelView.setID(), and engine.level.Level.setIdentifier().
Referenced by authoring.eventhandlers.AddLevelHandler.getPrompt().
EventType<Event> authoring.eventhandlers.AddLevelHandler.getEventType ()
Definition at line 55 of file AddLevelHandler.java.
void authoring.eventhandlers.AddLevelHandler.getPrompt () private
Definition at line 63 of file AddLevelHandler.java.
References authoring.eventhandlers.AddLevelHandler.createLevel(), authoring.view.wizards.LevelWizard.getIsFirst(), and authoring.view.wizards.Wizard.getMap().
Referenced by authoring.eventhandlers.AddLevelHandler.promptLevelID().
void authoring.eventhandlers.AddLevelHandler.handle (Event arg0)
Definition at line 35 of file AddLevelHandler.java.
References authoring.eventhandlers.AddLevelHandler.promptLevelID().
void authoring.eventhandlers.AddLevelHandler.promptLevelID () private
Definition at line 59 of file AddLevelHandler.java.
References authoring.eventhandlers.AddLevelHandler.getPrompt().
Referenced by authoring.eventhandlers.AddLevelHandler.handle().
Member Data Documentation
boolean authoring.eventhandlers.AddLevelHandler.isFirstLevel private
Definition at line 19 of file AddLevelHandler.java.
String authoring.eventhandlers.AddLevelHandler.myLevelID private
Definition at line 18 of file AddLevelHandler.java.
LevelsView authoring.eventhandlers.AddLevelHandler.myLevels private
Definition at line 16 of file AddLevelHandler.java.
LevelsCollection authoring.eventhandlers.AddLevelHandler.myLevelsCollection private
Definition at line 17 of file AddLevelHandler.java.
LevelWizard authoring.eventhandlers.AddLevelHandler.myWizard private
Definition at line 20 of file AddLevelHandler.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/voogasalad_BitsPlease/repository/src/authoring/eventhandlers/AddLevelHandler.java