voogasalad_BitsPlease: engine.GameManager Class Reference
engine.GameManager Class Reference
Public Member Functions
GameManager (ConditionsCollection myGameConditions, GameObjectsCollection myGameObjects, LevelsCollection myLevels, Group myRootGroup, String relativePath)
void initialize ()
void clear ()
void setGameSpeed (double speed, boolean play)
void togglePause ()
void processFrame ()
void load (GameData data)
GameObject objectForIdentifier (Identifier Id)
GameData getGameData ()
String getRelativePath ()
GameObjectsCollection getAllGameObjects ()
ConditionsCollection getAllConditions ()
GameObjectRenderer getRenderer ()
LevelManager getLevelManager ()
SoundUtility getSoundUtility ()
Group getGroup ()
Private Member Functions
void addFramesToGroup ()
void createLevelManager ()
void initializeConditions ()
Private Attributes
ConditionsCollection myGameConditions
GameObjectsCollection myGameObjects
GameObjectRenderer myGameObjectRenderer
SoundUtility mySoundUtility
Group myRootGroup
Timeline myAnimation
LevelManager myLevelManager
LevelsCollection myLevels
String myRelativePath
EventHandler< ActionEvent > oneFrame
Static Private Attributes
static final double DEFAULT_SPEED = 60.0
Detailed Description
central game manager responsible for holding game data, setting the timeline speed and processing each game frame
Author
Davis
Definition at line 28 of file GameManager.java.
Constructor & Destructor Documentation
engine.GameManager.GameManager (ConditionsCollection myGameConditions, GameObjectsCollection myGameObjects, LevelsCollection myLevels, Group myRootGroup, String relativePath)
Definition at line 40 of file GameManager.java.
References engine.GameManager.createLevelManager(), engine.GameManager.initializeConditions(), engine.GameManager.myGameConditions, engine.GameManager.myGameObjects, engine.GameManager.myLevels, and engine.GameManager.myRootGroup.
Member Function Documentation
void engine.GameManager.addFramesToGroup () private
Definition at line 70 of file GameManager.java.
Referenced by engine.GameManager.initialize().
void engine.GameManager.clear ()
remove and cleanup the existing game
Definition at line 65 of file GameManager.java.
Referenced by gamePlayer.model.PlayerModel.exitFromGame().
void engine.GameManager.createLevelManager () private
Definition at line 130 of file GameManager.java.
Referenced by engine.GameManager.GameManager().
ConditionsCollection engine.GameManager.getAllConditions ()
Definition at line 163 of file GameManager.java.
References engine.GameManager.myGameConditions.
GameObjectsCollection engine.GameManager.getAllGameObjects ()
Definition at line 159 of file GameManager.java.
References engine.GameManager.myGameObjects.
Referenced by engine.actions.IDAction.initialize().
GameData engine.GameManager.getGameData ()
Definition at line 151 of file GameManager.java.
Group engine.GameManager.getGroup ()
Definition at line 179 of file GameManager.java.
References engine.GameManager.myRootGroup.
LevelManager engine.GameManager.getLevelManager ()
Definition at line 171 of file GameManager.java.
References engine.GameManager.myLevelManager.
Referenced by engine.actions.ResetLevelAction.initialize(), engine.actions.TypeAction.initialize(), engine.actions.ChangeLevelAction.initialize(), engine.actions.DeleteIdAction.initialize(), engine.actions.RotateImageTypeAction.initialize(), engine.actions.TranslateTypeAction.initialize(), engine.actions.PhysicsTypeAction.initialize(), engine.actions.MakeNewObjectAction.initialize(), and engine.conditions.TypeCollisionCondition.initialize().
String engine.GameManager.getRelativePath ()
Definition at line 155 of file GameManager.java.
References engine.GameManager.myRelativePath.
GameObjectRenderer engine.GameManager.getRenderer ()
Definition at line 167 of file GameManager.java.
References engine.GameManager.myGameObjectRenderer.
Referenced by engine.actions.render.ChangeImageTypeAction.initialize(), engine.actions.DeleteTypeAction.initialize(), engine.actions.render.ChangeImageIDAction.initialize(), and engine.actions.MakeNewObjectAction.initialize().
SoundUtility engine.GameManager.getSoundUtility ()
Definition at line 175 of file GameManager.java.
References engine.GameManager.mySoundUtility.
Referenced by engine.actions.AudioClipAction.initialize(), and engine.actions.SoundAction.initialize().
void engine.GameManager.initialize ()
initialize the game
Definition at line 57 of file GameManager.java.
References engine.GameManager.addFramesToGroup(), and engine.GameManager.setGameSpeed().
Referenced by engine.tests.MainEngineTests.createGameObject(), games.MarioGameTest.createGameObject(), and gamePlayer.model.PlayerModel.loadGameData().
void engine.GameManager.initializeConditions () private
Definition at line 140 of file GameManager.java.
Referenced by engine.GameManager.GameManager().
void engine.GameManager.load (GameData data)
Definition at line 134 of file GameManager.java.
References authoring.model.GameData.getConditions(), authoring.model.GameData.getGameObjects(), and authoring.model.GameData.getLevels().
GameObject engine.GameManager.objectForIdentifier (Identifier Id)
Definition at line 146 of file GameManager.java.
References engine.level.LevelManager.objectForIdentifier().
Referenced by engine.actions.MakeNewObjectFromObjectAction.initialize(), engine.actions.ChangeComponentIDAction.initialize(), engine.conditions.GameObjectCondition.initialize(), engine.actions.TranslateIDAction.initialize(), and engine.actions.PhysicsIDAction.initialize().
void engine.GameManager.processFrame ()
run updates on the level
Definition at line 126 of file GameManager.java.
References engine.level.LevelManager.update().
void engine.GameManager.setGameSpeed (double speed, boolean play)
change the game speed
Parameters
speed speed of the simulation
play whether the animation should play after the speed change
Definition at line 85 of file GameManager.java.
References engine.GameManager.oneFrame.
Referenced by engine.actions.render.FrameRateAction.execute(), and engine.GameManager.initialize().
void engine.GameManager.togglePause ()
toggle the play/pause state of the game timeline
Definition at line 103 of file GameManager.java.
Referenced by gamePlayer.model.PlayerModel.pauseGame().
Member Data Documentation
final double engine.GameManager.DEFAULT_SPEED = 60.0 static private
Definition at line 38 of file GameManager.java.
Timeline engine.GameManager.myAnimation private
Definition at line 34 of file GameManager.java.
ConditionsCollection engine.GameManager.myGameConditions private
Definition at line 29 of file GameManager.java.
Referenced by engine.GameManager.GameManager(), and engine.GameManager.getAllConditions().
GameObjectRenderer engine.GameManager.myGameObjectRenderer private
Definition at line 31 of file GameManager.java.
Referenced by engine.GameManager.getRenderer().
GameObjectsCollection engine.GameManager.myGameObjects private
Definition at line 30 of file GameManager.java.
Referenced by engine.GameManager.GameManager(), and engine.GameManager.getAllGameObjects().
LevelManager engine.GameManager.myLevelManager private
Definition at line 35 of file GameManager.java.
Referenced by engine.GameManager.getLevelManager().
LevelsCollection engine.GameManager.myLevels private
Definition at line 36 of file GameManager.java.
Referenced by engine.GameManager.GameManager().
String engine.GameManager.myRelativePath private
Definition at line 37 of file GameManager.java.
Referenced by engine.GameManager.getRelativePath().
Group engine.GameManager.myRootGroup private
Definition at line 33 of file GameManager.java.
Referenced by engine.GameManager.GameManager(), and engine.GameManager.getGroup().
SoundUtility engine.GameManager.mySoundUtility private
Definition at line 32 of file GameManager.java.
Referenced by engine.GameManager.getSoundUtility().
EventHandler<ActionEvent> engine.GameManager.oneFrame private
Initial value:
= new EventHandler<ActionEvent>() {
       @Override
       public void handle(ActionEvent evt) {
           processFrame();
       }
   }
Function to do each game frame
Definition at line 116 of file GameManager.java.
Referenced by engine.GameManager.setGameSpeed().
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/voogasalad_BitsPlease/repository/src/engine/GameManager.java