voogasalad_BitsPlease: games.MarioGameTest Class Reference
games.MarioGameTest Class Reference
Public Member Functions
void start (Stage arg0) throws Exception
void createGameObject (Group group)
Static Public Member Functions
static void main (String[] args) throws Exception
Private Attributes
GameManager myGameManager
Stage myStage
Scene myScene
Group myRootGroup
Detailed Description
Definition at line 52 of file MarioGameTest.java.
Member Function Documentation
void games.MarioGameTest.createGameObject (Group group)
Definition at line 87 of file MarioGameTest.java.
References authoring.model.collections.LevelsCollection.add(), authoring.model.collections.ConditionsCollection.add(), authoring.model.collections.GeneralCollection< T >.add(), authoring.model.collections.GeneralCollection< T >.addAll(), engine.gameObject.components.PhysicsBody.addForce(), engine.gameObject.components.PhysicsBody.addScalar(), authoring.model.collections.GeneralCollection< T >.get(), engine.gameObject.GameObject.getIdentifier(), authoring.model.collections.ConditionsCollection.getIdentifierList(), authoring.model.collections.GameObjectsCollection.getIdentifierList(), engine.GameManager.initialize(), engine.level.Level.setBackgroundMusic(), engine.conditions.Condition.setIdentifier(), engine.gameObject.GameObject.setIdentifier(), engine.gameObject.GameObject.setPhysicsBody(), and games.MarioGameTest.start().
Referenced by games.MarioGameTest.start().
static void games.MarioGameTest.main (String[] args) throws Exception static
Definition at line 68 of file MarioGameTest.java.
void games.MarioGameTest.start (Stage arg0) throws Exception
Definition at line 73 of file MarioGameTest.java.
References engine.conditions.ButtonConditionManager.beginListeningToScene(), games.MarioGameTest.createGameObject(), and engine.conditions.ButtonConditionManager.getInstance().
Referenced by games.MarioGameTest.createGameObject().
Member Data Documentation
GameManager games.MarioGameTest.myGameManager private
Author
Davis
the sandbox for engine used to get stuff on the screen and keep engine team morale high
Definition at line 61 of file MarioGameTest.java.
Group games.MarioGameTest.myRootGroup private
Definition at line 64 of file MarioGameTest.java.
Scene games.MarioGameTest.myScene private
Definition at line 63 of file MarioGameTest.java.
Stage games.MarioGameTest.myStage private
Definition at line 62 of file MarioGameTest.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/voogasalad_BitsPlease/repository/src/games/MarioGameTest.java