voogasalad_BitsPlease: authoring.view.icons.SoundIcon Class Reference
authoring.view.icons.SoundIcon Class Reference
Public Member Functions
SoundIcon (File gameLoc, String label, GameHandler...handler)
void play ()
Properties makeProperties ()
Public Member Functions inherited from authoring.view.icons.FileIcon
FileIcon (File gameLoc, String label, GameHandler...handler)
Public Member Functions inherited from authoring.view.icons.BaseIcon
BaseIcon (String label, GameHandler...handler)
void addLabel ()
String getName ()
Protected Member Functions
void makeIcon ()
Protected Member Functions inherited from authoring.view.icons.FileIcon
abstract void makeIcon ()
Package Attributes
FileChooser myFileChooser = new FileChooser()
Private Member Functions
void generateMedia ()
Private Attributes
Image mySoundIcon
MediaPlayer myAudioPlayer
Static Private Attributes
static final int DEFAULT_SOUND_ICON_SIZE = 60
Additional Inherited Members
Protected Attributes inherited from authoring.view.icons.FileIcon
File myGameLocation
Protected Attributes inherited from authoring.view.icons.BaseIcon
GameHandler[] myOnClick
String myLabel
Detailed Description
Author
Kevin Li
Chris Bernt
Wesley Valentine
Arjun Jain
Definition at line 20 of file SoundIcon.java.
Constructor & Destructor Documentation
authoring.view.icons.SoundIcon.SoundIcon (File gameLoc, String label, GameHandler... handler)
Definition at line 27 of file SoundIcon.java.
References authoring.view.icons.BaseIcon.addLabel(), authoring.view.icons.SoundIcon.generateMedia(), and authoring.view.icons.SoundIcon.makeIcon().
Member Function Documentation
void authoring.view.icons.SoundIcon.generateMedia () private
Definition at line 37 of file SoundIcon.java.
References authoring.view.icons.FileIcon.myGameLocation, and authoring.view.icons.BaseIcon.myLabel.
Referenced by authoring.view.icons.SoundIcon.SoundIcon().
void authoring.view.icons.SoundIcon.makeIcon () protected
Definition at line 45 of file SoundIcon.java.
References authoring.view.icons.BaseIcon.myOnClick.
Referenced by authoring.view.icons.SoundIcon.SoundIcon().
Properties authoring.view.icons.SoundIcon.makeProperties ()
Implements authoring.view.icons.IPropertiesMaker.
Definition at line 65 of file SoundIcon.java.
void authoring.view.icons.SoundIcon.play ()
Definition at line 56 of file SoundIcon.java.
Referenced by authoring.eventhandlers.SoundsDoubleClickHandler.handle().
Member Data Documentation
final int authoring.view.icons.SoundIcon.DEFAULT_SOUND_ICON_SIZE = 60 static private
Definition at line 21 of file SoundIcon.java.
MediaPlayer authoring.view.icons.SoundIcon.myAudioPlayer private
Definition at line 23 of file SoundIcon.java.
FileChooser authoring.view.icons.SoundIcon.myFileChooser = new FileChooser() package
Definition at line 25 of file SoundIcon.java.
Image authoring.view.icons.SoundIcon.mySoundIcon private
Definition at line 22 of file SoundIcon.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/voogasalad_BitsPlease/repository/src/authoring/view/icons/SoundIcon.java