voogasalad_BitsPlease: authoring.eventhandlers.DeleteLevelHandler Class Reference
authoring.eventhandlers.DeleteLevelHandler Class Reference
Public Member Functions
DeleteLevelHandler (LevelsCollection collection, LevelsView lv)
void handle (Event arg0)
EventType< Event > getEventType ()
Public Member Functions inherited from authoring.eventhandlers.GameHandler< Event >
void handle (T arg0)
EventType< T > getEventType ()
Private Member Functions
void deleteLevel ()
Private Attributes
LevelsCollection myLevelsCollection
Wizard myDeleteLevelWizard
LevelsView myLevelsTabs
Detailed Description
Author
Kevin Li
Arjun Jain
Chris Bernt
Wesley Valentine
Safkat Islam
Definition at line 19 of file DeleteLevelHandler.java.
Constructor & Destructor Documentation
authoring.eventhandlers.DeleteLevelHandler.DeleteLevelHandler (LevelsCollection collection, LevelsView lv)
Definition at line 25 of file DeleteLevelHandler.java.
Member Function Documentation
void authoring.eventhandlers.DeleteLevelHandler.deleteLevel () private
Definition at line 43 of file DeleteLevelHandler.java.
References authoring.view.wizards.Wizard.getMap(), and authoring.model.collections.LevelsCollection.removeByID().
Referenced by authoring.eventhandlers.DeleteLevelHandler.handle().
EventType<Event> authoring.eventhandlers.DeleteLevelHandler.getEventType ()
Definition at line 39 of file DeleteLevelHandler.java.
void authoring.eventhandlers.DeleteLevelHandler.handle (Event arg0)
Definition at line 31 of file DeleteLevelHandler.java.
References authoring.eventhandlers.DeleteLevelHandler.deleteLevel().
Member Data Documentation
Wizard authoring.eventhandlers.DeleteLevelHandler.myDeleteLevelWizard private
Definition at line 22 of file DeleteLevelHandler.java.
LevelsCollection authoring.eventhandlers.DeleteLevelHandler.myLevelsCollection private
Definition at line 21 of file DeleteLevelHandler.java.
LevelsView authoring.eventhandlers.DeleteLevelHandler.myLevelsTabs private
Definition at line 23 of file DeleteLevelHandler.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/voogasalad_BitsPlease/repository/src/authoring/eventhandlers/DeleteLevelHandler.java