voogasalad_BitsPlease: engine.actions.PhysicsIDAction Class Reference
engine.actions.PhysicsIDAction Class Reference abstract
Classes
interface ThreeArgInterface
interface TwoArgInterface
Public Member Functions
PhysicsIDAction (List< Identifier > id, Double value)
void execute ()
void initialize (GameManager manager)
abstract void applyPhysics (Collection< GameObject > myObjects)
Protected Member Functions
void forHelper (Collection< GameObject > myObjects, TwoArgInterface myOperation, Object value)
Protected Attributes
Double myValue
CollisionComposition myCollision
Collection< GameObject > myObjects
List< Identifier > myID
Detailed Description
Author
Ben
Definition at line 18 of file PhysicsIDAction.java.
Constructor & Destructor Documentation
engine.actions.PhysicsIDAction.PhysicsIDAction (List< Identifier > id, Double value)
Definition at line 25 of file PhysicsIDAction.java.
Member Function Documentation
abstract void engine.actions.PhysicsIDAction.applyPhysics (Collection< GameObject > myObjects) abstract
Referenced by engine.actions.PhysicsIDAction.execute().
void engine.actions.PhysicsIDAction.execute ()
Will execute the consequences resulting from applying an Action.
Parameters
action
Implements engine.actions.Action.
Definition at line 33 of file PhysicsIDAction.java.
References engine.actions.PhysicsIDAction.applyPhysics().
void engine.actions.PhysicsIDAction.forHelper (Collection< GameObject > myObjects, TwoArgInterface myOperation, Object value) protected
Definition at line 45 of file PhysicsIDAction.java.
References engine.actions.PhysicsIDAction.TwoArgInterface.operation().
Referenced by engine.actions.ReverseVelocityIDAction.applyPhysics(), and engine.actions.PhysicsComponentAction.applyPhysics().
void engine.actions.PhysicsIDAction.initialize (GameManager manager)
Implements engine.actions.Initializable.
Definition at line 37 of file PhysicsIDAction.java.
References engine.GameManager.objectForIdentifier().
Member Data Documentation
CollisionComposition engine.actions.PhysicsIDAction.myCollision protected
Definition at line 21 of file PhysicsIDAction.java.
Referenced by engine.actions.ReverseVelocityIDAction.applyPhysics(), and engine.actions.FixedCollisionAction.applyPhysics().
List<Identifier> engine.actions.PhysicsIDAction.myID protected
Definition at line 23 of file PhysicsIDAction.java.
Collection<GameObject> engine.actions.PhysicsIDAction.myObjects protected
Definition at line 22 of file PhysicsIDAction.java.
Referenced by engine.actions.ReverseVelocityIDAction.applyPhysics(), and engine.actions.FixedCollisionAction.applyPhysics().
Double engine.actions.PhysicsIDAction.myValue protected
Definition at line 20 of file PhysicsIDAction.java.
Referenced by engine.actions.PhysicsComponentAction.applyPhysics().
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/voogasalad_BitsPlease/repository/src/engine/actions/PhysicsIDAction.java