voogasalad_BitsPlease: authoring.view.propertiesview.GameObjectProperties Class Reference
authoring.view.propertiesview.GameObjectProperties Class Reference
Public Member Functions
GameObjectProperties (GameObject gObj, double width, double height, GameHandler...handler)
GameObjectProperties ()
void initializeProperties (Object g)
GameObject edit (GameObject g)
Button setUpForNewObject ()
void saveAsNew ()
Map< String, PropertyTextField > getWizardMap ()
Public Member Functions inherited from authoring.view.propertiesview.Properties
abstract void initializeProperties (Object o)
void addMapToView ()
Private Attributes
AccordionContainer myAccordion
Map< String, PropertyTextField > inherentTextProperties
Map< String, PropertyTextField > concreteTextProperties
Map< String, CheckBox > booleanProperties
Map< String, PropertyTextField > physicsProperties
Map< String, PropertyTextField > wizardProperties
GameHandler myEditHandler
GameHandler myDeleteHandler
GameHandler mySaveAsNewHandler
Additional Inherited Members
Protected Attributes inherited from authoring.view.propertiesview.Properties
Map< String, PropertyField > myMap = new LinkedHashMap<String, PropertyField>()
Detailed Description
Definition at line 26 of file GameObjectProperties.java.
Constructor & Destructor Documentation
authoring.view.propertiesview.GameObjectProperties.GameObjectProperties (GameObject gObj, double width, double height, GameHandler... handler)
Definition at line 42 of file GameObjectProperties.java.
References authoring.view.propertiesview.GameObjectProperties.initializeProperties().
authoring.view.propertiesview.GameObjectProperties.GameObjectProperties ()
Definition at line 54 of file GameObjectProperties.java.
Member Function Documentation
GameObject authoring.view.propertiesview.GameObjectProperties.edit (GameObject g)
Definition at line 154 of file GameObjectProperties.java.
References engine.gameObject.components.PhysicsBody.addScalar(), engine.gameObject.GameObject.getComponents(), engine.gameObject.GameObject.getID(), engine.gameObject.GameObject.getIdentifier(), engine.gameObject.GameObject.setIdentifier(), engine.gameObject.GameObject.setPhysicsBody(), and engine.gameObject.components.PhysicsBody.setVelocity().
Referenced by authoring.view.propertiesview.PropertiesView.getEditedGameObject().
Map<String, PropertyTextField> authoring.view.propertiesview.GameObjectProperties.getWizardMap ()
Definition at line 205 of file GameObjectProperties.java.
References authoring.view.propertiesview.GameObjectProperties.wizardProperties.
void authoring.view.propertiesview.GameObjectProperties.initializeProperties (Object g)
Definition at line 72 of file GameObjectProperties.java.
References engine.gameObject.GameObject.getCurrentImageName(), engine.gameObject.GameObject.getHeight(), engine.gameObject.GameObject.getIdentifier(), engine.gameObject.GameObject.getPhysicsBody(), engine.gameObject.GameObject.getRotation(), engine.gameObject.components.PhysicsBody.getScalar(), engine.gameObject.Identifier.getType(), engine.gameObject.Identifier.getUniqueId(), engine.physics.Scalar.getValue(), engine.gameObject.components.PhysicsBody.getVelocity(), engine.gameObject.GameObject.getWidth(), engine.physics.Vector.getX(), engine.gameObject.GameObject.getX(), engine.physics.Vector.getY(), engine.gameObject.GameObject.getY(), and authoring.view.propertiesview.GameObjectProperties.saveAsNew().
Referenced by authoring.view.propertiesview.GameObjectProperties.GameObjectProperties().
void authoring.view.propertiesview.GameObjectProperties.saveAsNew ()
Definition at line 201 of file GameObjectProperties.java.
Referenced by authoring.view.propertiesview.GameObjectProperties.initializeProperties().
Button authoring.view.propertiesview.GameObjectProperties.setUpForNewObject ()
Definition at line 184 of file GameObjectProperties.java.
References authoring.view.propertiesview.PropertyTextField.setString().
Member Data Documentation
Map<String, CheckBox> authoring.view.propertiesview.GameObjectProperties.booleanProperties private
Definition at line 33 of file GameObjectProperties.java.
Map<String, PropertyTextField> authoring.view.propertiesview.GameObjectProperties.concreteTextProperties private
Definition at line 32 of file GameObjectProperties.java.
Map<String, PropertyTextField> authoring.view.propertiesview.GameObjectProperties.inherentTextProperties private
Definition at line 31 of file GameObjectProperties.java.
AccordionContainer authoring.view.propertiesview.GameObjectProperties.myAccordion private
Definition at line 29 of file GameObjectProperties.java.
GameHandler authoring.view.propertiesview.GameObjectProperties.myDeleteHandler private
Definition at line 39 of file GameObjectProperties.java.
GameHandler authoring.view.propertiesview.GameObjectProperties.myEditHandler private
Definition at line 38 of file GameObjectProperties.java.
GameHandler authoring.view.propertiesview.GameObjectProperties.mySaveAsNewHandler private
Definition at line 40 of file GameObjectProperties.java.
Map<String, PropertyTextField> authoring.view.propertiesview.GameObjectProperties.physicsProperties private
Definition at line 34 of file GameObjectProperties.java.
Map<String, PropertyTextField> authoring.view.propertiesview.GameObjectProperties.wizardProperties private
Definition at line 36 of file GameObjectProperties.java.
Referenced by authoring.view.propertiesview.GameObjectProperties.getWizardMap().
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/voogasalad_BitsPlease/repository/src/authoring/view/propertiesview/GameObjectProperties.java