voogasalad_BitsPlease: engine.conditions.ButtonReleaseCondition Class Reference
engine.conditions.ButtonReleaseCondition Class Reference
Public Member Functions
ButtonReleaseCondition (List< Action > onReleaseActions, List< KeyCode > keyList)
void respondToFrameElapsed ()
String getKeyIdentifier ()
List< KeyCode > getKeyList ()
void addKey (KeyCode kc)
void removeKey (KeyCode kc)
void setKeyIdentifier (String id)
Public Member Functions inherited from engine.conditions.Condition
Condition (List< Action > actions)
List< Action > getActions ()
void setEnabled (Boolean enabled)
boolean isEnabled ()
void setInputMap (Map< String, String > inputs)
Map< String, String > getInputMap ()
void frameElapsed ()
void setIdentifier (Identifier myId)
Identifier getIdentifier ()
void initialize (GameManager manager)
void addAction (Action a)
Protected Member Functions
void executeActions ()
Protected Member Functions inherited from engine.conditions.Condition
abstract void executeActions ()
abstract void respondToFrameElapsed ()
void initializeActions (GameManager manager)
GameManager getGameManager ()
Private Attributes
Map< KeyCode, Boolean > myKeyMap
Additional Inherited Members
Protected Attributes inherited from engine.conditions.Condition
List< Action > myActions = new ArrayList<Action>()
transient GameManager myGameManager
Identifier myId
Detailed Description
Definition at line 10 of file ButtonReleaseCondition.java.
Constructor & Destructor Documentation
engine.conditions.ButtonReleaseCondition.ButtonReleaseCondition (List< Action > onReleaseActions, List< KeyCode > keyList)
Definition at line 14 of file ButtonReleaseCondition.java.
Member Function Documentation
void engine.conditions.ButtonReleaseCondition.addKey (KeyCode kc)
Definition at line 58 of file ButtonReleaseCondition.java.
void engine.conditions.ButtonReleaseCondition.executeActions () protected
Definition at line 23 of file ButtonReleaseCondition.java.
References engine.conditions.Condition.getActions(), engine.conditions.ButtonConditionManager.getInstance(), and engine.conditions.ButtonConditionManager.keyIsActive().
Referenced by engine.conditions.ButtonReleaseCondition.respondToFrameElapsed().
String engine.conditions.ButtonReleaseCondition.getKeyIdentifier ()
Definition at line 45 of file ButtonReleaseCondition.java.
References engine.gameObject.Identifier.getUniqueId(), and engine.conditions.Condition.myId.
List<KeyCode> engine.conditions.ButtonReleaseCondition.getKeyList ()
Definition at line 49 of file ButtonReleaseCondition.java.
void engine.conditions.ButtonReleaseCondition.removeKey (KeyCode kc)
Definition at line 63 of file ButtonReleaseCondition.java.
void engine.conditions.ButtonReleaseCondition.respondToFrameElapsed ()
Definition at line 41 of file ButtonReleaseCondition.java.
References engine.conditions.ButtonReleaseCondition.executeActions().
void engine.conditions.ButtonReleaseCondition.setKeyIdentifier (String id)
Definition at line 67 of file ButtonReleaseCondition.java.
References engine.conditions.Condition.myId, and engine.gameObject.Identifier.setUniqueId().
Member Data Documentation
Map<KeyCode,Boolean> engine.conditions.ButtonReleaseCondition.myKeyMap private
Definition at line 12 of file ButtonReleaseCondition.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/voogasalad_BitsPlease/repository/src/engine/conditions/ButtonReleaseCondition.java