voogasalad_BitsPlease: authoring.model.GameData Class Reference
authoring.model.GameData Class Reference
Public Member Functions
GameData ()
GameData (LevelsCollection levels, ConditionsCollection conditions, GameObjectsCollection gameObjects)
LevelsCollection getLevels ()
GameObjectsCollection getGameObjects ()
ConditionsCollection getConditions ()
ImagesCollection getImages ()
SoundsCollection getSounds ()
Private Member Functions
void addAllToMyCollections (GeneralCollection...collection)
Private Attributes
Map< String, GeneralCollection > myCollections
LevelsCollection myLevels
ConditionsCollection myConditions
GameObjectsCollection myGameObjects
ImagesCollection myImages
SoundsCollection mySounds
Detailed Description
Passive data object that holds onto all of the data that represents an authored game.
Author
Chris Bernt
Wesley Valentine
Arjun Jain
Kevin Li
Definition at line 26 of file GameData.java.
Constructor & Destructor Documentation
authoring.model.GameData.GameData ()
Definition at line 39 of file GameData.java.
authoring.model.GameData.GameData (LevelsCollection levels, ConditionsCollection conditions, GameObjectsCollection gameObjects)
Definition at line 52 of file GameData.java.
References authoring.model.GameData.addAllToMyCollections().
Member Function Documentation
void authoring.model.GameData.addAllToMyCollections (GeneralCollection... collection) private
Changing collections to be a map, so that the get method duplication is removed.
Parameters
collection
Definition at line 71 of file GameData.java.
Referenced by authoring.model.GameData.GameData().
ConditionsCollection authoring.model.GameData.getConditions ()
Condition Methods
Definition at line 97 of file GameData.java.
References authoring.model.GameData.myConditions.
Referenced by authoring.model.AuthoringModel.convertFromSerializable(), authoring.model.AuthoringModel.convertToSerializable(), gamePlayer.model.PlayerModel.extractButtonConditions(), authoring.model.AuthoringModel.getConditions(), engine.GameManager.load(), and gamePlayer.model.PlayerModel.loadGameData().
GameObjectsCollection authoring.model.GameData.getGameObjects ()
GameObject Methods
Definition at line 88 of file GameData.java.
References authoring.model.GameData.myGameObjects.
Referenced by authoring.model.AuthoringModel.convertFromSerializable(), authoring.model.AuthoringModel.convertToSerializable(), authoring.model.AuthoringModel.getGameObjectCollection(), engine.GameManager.load(), and gamePlayer.model.PlayerModel.loadGameData().
ImagesCollection authoring.model.GameData.getImages ()
Graphic Methods
Definition at line 106 of file GameData.java.
References authoring.model.GameData.myImages.
Referenced by authoring.model.AuthoringModel.convertFromSerializable(), authoring.model.AuthoringModel.convertToSerializable(), and authoring.model.AuthoringModel.getImages().
LevelsCollection authoring.model.GameData.getLevels ()
Definition at line 79 of file GameData.java.
References authoring.model.GameData.myLevels.
Referenced by authoring.model.AuthoringModel.convertFromSerializable(), authoring.model.AuthoringModel.convertToSerializable(), authoring.model.AuthoringModel.getLevels(), engine.GameManager.load(), and gamePlayer.model.PlayerModel.loadGameData().
SoundsCollection authoring.model.GameData.getSounds ()
Sound Methods
Definition at line 114 of file GameData.java.
References authoring.model.GameData.mySounds.
Referenced by authoring.model.AuthoringModel.convertFromSerializable(), authoring.model.AuthoringModel.convertToSerializable(), and authoring.model.AuthoringModel.getSounds().
Member Data Documentation
Map<String, GeneralCollection> authoring.model.GameData.myCollections private
Maybe put in properties file?
Definition at line 32 of file GameData.java.
ConditionsCollection authoring.model.GameData.myConditions private
Definition at line 34 of file GameData.java.
Referenced by authoring.model.GameData.getConditions().
GameObjectsCollection authoring.model.GameData.myGameObjects private
Definition at line 35 of file GameData.java.
Referenced by authoring.model.GameData.getGameObjects().
ImagesCollection authoring.model.GameData.myImages private
Definition at line 36 of file GameData.java.
Referenced by authoring.model.GameData.getImages().
LevelsCollection authoring.model.GameData.myLevels private
Definition at line 33 of file GameData.java.
Referenced by authoring.model.GameData.getLevels().
SoundsCollection authoring.model.GameData.mySounds private
Definition at line 37 of file GameData.java.
Referenced by authoring.model.GameData.getSounds().
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/voogasalad_BitsPlease/repository/src/authoring/model/GameData.java