voogasalad_BitsPlease: authoring.eventhandlers.AddActionHandler Class Reference
authoring.eventhandlers.AddActionHandler Class Reference
Public Member Functions
void handle (Event arg0)
EventType< Event > getEventType ()
void setCondition (Condition c)
Public Member Functions inherited from authoring.eventhandlers.GameHandler< Event >
void handle (T arg0)
EventType< T > getEventType ()
Private Member Functions
void createAction ()
void finishAction ()
List< Object > convertInputParameters ()
Private Attributes
ActionChoiceWizard myActionSelectionWizard
ConditionParameterWizard myCPW
List< String > myInputParameters
Parameter[] myParameterTypes
Class<?> classType
Constructor myConstructor
Condition myCondition
Static Private Attributes
static final String CONDITION_PATH_START = "engine.actions."
static final int WIZARD_WIDTH = 300
static final int WIZARD_HEIGHT = 600
Detailed Description
Author
Kevin Li
Arjun Jain
Chris Bernt
Wesley Valentine
Safkat Islam
Definition at line 26 of file AddActionHandler.java.
Member Function Documentation
List<Object> authoring.eventhandlers.AddActionHandler.convertInputParameters () private
Definition at line 89 of file AddActionHandler.java.
References errorsAndExceptions.ErrorPopUp.display().
Referenced by authoring.eventhandlers.AddActionHandler.finishAction().
void authoring.eventhandlers.AddActionHandler.createAction () private
Definition at line 48 of file AddActionHandler.java.
References errorsAndExceptions.ErrorPopUp.display(), authoring.eventhandlers.AddActionHandler.finishAction(), and authoring.view.wizards.ActionChoiceWizard.getSelectedAction().
Referenced by authoring.eventhandlers.AddActionHandler.handle().
void authoring.eventhandlers.AddActionHandler.finishAction () private
Definition at line 70 of file AddActionHandler.java.
References engine.conditions.Condition.addAction(), authoring.eventhandlers.AddActionHandler.convertInputParameters(), errorsAndExceptions.ErrorPopUp.display(), and authoring.view.wizards.Wizard.getMap().
Referenced by authoring.eventhandlers.AddActionHandler.createAction().
EventType<Event> authoring.eventhandlers.AddActionHandler.getEventType ()
Definition at line 142 of file AddActionHandler.java.
void authoring.eventhandlers.AddActionHandler.handle (Event arg0)
Definition at line 43 of file AddActionHandler.java.
References authoring.eventhandlers.AddActionHandler.createAction().
void authoring.eventhandlers.AddActionHandler.setCondition (Condition c)
Definition at line 146 of file AddActionHandler.java.
Member Data Documentation
Class<?> authoring.eventhandlers.AddActionHandler.classType private
Definition at line 37 of file AddActionHandler.java.
final String authoring.eventhandlers.AddActionHandler.CONDITION_PATH_START = "engine.actions." static private
Definition at line 28 of file AddActionHandler.java.
ActionChoiceWizard authoring.eventhandlers.AddActionHandler.myActionSelectionWizard private
Definition at line 32 of file AddActionHandler.java.
Condition authoring.eventhandlers.AddActionHandler.myCondition private
Definition at line 40 of file AddActionHandler.java.
Constructor authoring.eventhandlers.AddActionHandler.myConstructor private
Definition at line 38 of file AddActionHandler.java.
ConditionParameterWizard authoring.eventhandlers.AddActionHandler.myCPW private
Definition at line 33 of file AddActionHandler.java.
List<String> authoring.eventhandlers.AddActionHandler.myInputParameters private
Definition at line 35 of file AddActionHandler.java.
Parameter [] authoring.eventhandlers.AddActionHandler.myParameterTypes private
Definition at line 36 of file AddActionHandler.java.
final int authoring.eventhandlers.AddActionHandler.WIZARD_HEIGHT = 600 static private
Definition at line 30 of file AddActionHandler.java.
final int authoring.eventhandlers.AddActionHandler.WIZARD_WIDTH = 300 static private
Definition at line 29 of file AddActionHandler.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/voogasalad_BitsPlease/repository/src/authoring/eventhandlers/AddActionHandler.java