voogasalad_BitsPlease: authoring.eventhandlers.DeleteConditionFromLevelHandler Class Reference
authoring.eventhandlers.DeleteConditionFromLevelHandler Class Reference
Public Member Functions
DeleteConditionFromLevelHandler (Level l)
void handle (Event arg0)
EventType< Event > getEventType ()
Public Member Functions inherited from authoring.eventhandlers.GameHandler< Event >
void handle (T arg0)
EventType< T > getEventType ()
Private Member Functions
void deleteCondition ()
Private Attributes
Level myLevel
Wizard myDeleteConditionHandler
Detailed Description
Author
Kevin Li
Arjun Jain
Chris Bernt
Wesley Valentine
Safkat Islam
Definition at line 16 of file DeleteConditionFromLevelHandler.java.
Constructor & Destructor Documentation
authoring.eventhandlers.DeleteConditionFromLevelHandler.DeleteConditionFromLevelHandler (Level l)
Definition at line 21 of file DeleteConditionFromLevelHandler.java.
Member Function Documentation
void authoring.eventhandlers.DeleteConditionFromLevelHandler.deleteCondition () private
Definition at line 37 of file DeleteConditionFromLevelHandler.java.
References engine.level.Level.getConditionIdentifiers(), and authoring.view.wizards.Wizard.getMap().
Referenced by authoring.eventhandlers.DeleteConditionFromLevelHandler.handle().
EventType<Event> authoring.eventhandlers.DeleteConditionFromLevelHandler.getEventType ()
Definition at line 33 of file DeleteConditionFromLevelHandler.java.
void authoring.eventhandlers.DeleteConditionFromLevelHandler.handle (Event arg0)
Definition at line 27 of file DeleteConditionFromLevelHandler.java.
References authoring.eventhandlers.DeleteConditionFromLevelHandler.deleteCondition().
Member Data Documentation
Wizard authoring.eventhandlers.DeleteConditionFromLevelHandler.myDeleteConditionHandler private
Definition at line 19 of file DeleteConditionFromLevelHandler.java.
Level authoring.eventhandlers.DeleteConditionFromLevelHandler.myLevel private
Definition at line 18 of file DeleteConditionFromLevelHandler.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/voogasalad_BitsPlease/repository/src/authoring/eventhandlers/DeleteConditionFromLevelHandler.java