voogasalad_BitsPlease: engine.render.RenderedNode Class Reference
engine.render.RenderedNode Class Reference
Public Member Functions
void setCollisionBody (Node body)
void setLabel (Label label)
void setImageView (ImageView view)
ImageView getImageView ()
Label getLabel ()
Node getCollisionBody ()
boolean intersects (Bounds localBounds)
Private Attributes
ImageView myImageView
Node myCollisionBody
Label myLabel
String myImagePath
Detailed Description
The JavaFX Component of the Game Object. Contains The Image, CollisionBody, and functionality for JavaFX GUI
Author
Will Chang
Definition at line 16 of file RenderedNode.java.
Member Function Documentation
Node engine.render.RenderedNode.getCollisionBody ()
Gets the CollisionBody
Returns
Definition at line 78 of file RenderedNode.java.
References engine.render.RenderedNode.myCollisionBody.
ImageView engine.render.RenderedNode.getImageView ()
Gets the ImageView
Returns
Definition at line 63 of file RenderedNode.java.
References engine.render.RenderedNode.myImageView.
Referenced by engine.gameObject.GameObject.setCurrentImagePath().
Label engine.render.RenderedNode.getLabel ()
Gets the Label
Definition at line 70 of file RenderedNode.java.
References engine.render.RenderedNode.myLabel.
boolean engine.render.RenderedNode.intersects (Bounds localBounds)
Definition at line 83 of file RenderedNode.java.
Referenced by engine.collision.objects.CollisionComposition.isOnXAxis().
void engine.render.RenderedNode.setCollisionBody (Node body)
Sets the CollisionBody
Parameters
body
Definition at line 27 of file RenderedNode.java.
Referenced by engine.render.GameObjectRenderer.createAndAssignRenderedNode().
void engine.render.RenderedNode.setImageView (ImageView view)
Sets the ImageView
Parameters
view
Definition at line 51 of file RenderedNode.java.
Referenced by engine.render.GameObjectRenderer.createAndAssignRenderedNode().
void engine.render.RenderedNode.setLabel (Label label)
Sets the Label
Definition at line 39 of file RenderedNode.java.
Referenced by engine.render.GameObjectRenderer.createAndAssignRenderedNode().
Member Data Documentation
Node engine.render.RenderedNode.myCollisionBody private
Definition at line 18 of file RenderedNode.java.
Referenced by engine.render.RenderedNode.getCollisionBody().
String engine.render.RenderedNode.myImagePath private
Definition at line 20 of file RenderedNode.java.
ImageView engine.render.RenderedNode.myImageView private
Definition at line 17 of file RenderedNode.java.
Referenced by engine.render.RenderedNode.getImageView().
Label engine.render.RenderedNode.myLabel private
Definition at line 19 of file RenderedNode.java.
Referenced by engine.render.RenderedNode.getLabel().
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/voogasalad_BitsPlease/repository/src/engine/render/RenderedNode.java