voogasalad_BitsPlease: engine.conditions.Condition Class Reference
engine.conditions.Condition Class Reference abstract
Public Member Functions
Condition (List< Action > actions)
List< Action > getActions ()
void setEnabled (Boolean enabled)
boolean isEnabled ()
void frameElapsed ()
void setIdentifier (Identifier myId)
Identifier getIdentifier ()
void initialize (GameManager manager)
void addAction (Action a)
Protected Member Functions
abstract void executeActions ()
void initializeActions (GameManager manager)
GameManager getGameManager ()
Protected Attributes
List< Action > myActions = new ArrayList<Action>()
transient GameManager myGameManager
Identifier myId
Private Attributes
Boolean myEnabled
Detailed Description
root class for conditions, or the event that triggers actions
Author
Davis
Definition at line 21 of file Condition.java.
Constructor & Destructor Documentation
engine.conditions.Condition.Condition (List< Action > actions)
Definition at line 28 of file Condition.java.
Member Function Documentation
void engine.conditions.Condition.addAction (Action a)
Definition at line 84 of file Condition.java.
Referenced by authoring.eventhandlers.AddActionHandler.finishAction().
abstract void engine.conditions.Condition.executeActions () abstract protected
method to call for executing the associated action/s
void engine.conditions.Condition.frameElapsed ()
method to call to increment the frame counter for conditions that are frame based
Definition at line 52 of file Condition.java.
List<Action> engine.conditions.Condition.getActions ()
Definition at line 32 of file Condition.java.
References engine.conditions.Condition.myActions.
Referenced by engine.conditions.TimeCondition.executeActions(), engine.conditions.MovementCondition.executeActions(), engine.conditions.ButtonReleaseCondition.executeActions(), engine.conditions.BoundaryConditionX.executeActions(), engine.conditions.BoundaryConditionY.executeActions(), engine.conditions.ButtonPressCondition.executeActions(), and authoring.view.propertiesview.ConditionProperties.initializeProperties().
GameManager engine.conditions.Condition.getGameManager () protected
Definition at line 80 of file Condition.java.
References engine.conditions.Condition.myGameManager.
Identifier engine.conditions.Condition.getIdentifier ()
Implements engine.gameObject.Identifiable.
Definition at line 62 of file Condition.java.
References engine.conditions.Condition.myId.
Referenced by authoring.view.conditionsview.ConditionsAccordionView.addCondition(), and authoring.model.collections.ConditionsCollection.getIdentifierList().
void engine.conditions.Condition.initialize (GameManager manager)
Implements engine.actions.Initializable.
Definition at line 67 of file Condition.java.
References engine.conditions.Condition.initializeActions().
void engine.conditions.Condition.initializeActions (GameManager manager) protected
Definition at line 72 of file Condition.java.
Referenced by engine.conditions.GameObjectCondition.initialize(), engine.conditions.TypeCollisionCondition.initialize(), and engine.conditions.Condition.initialize().
boolean engine.conditions.Condition.isEnabled ()
Definition at line 40 of file Condition.java.
References engine.conditions.Condition.myEnabled.
void engine.conditions.Condition.setEnabled (Boolean enabled)
Definition at line 36 of file Condition.java.
void engine.conditions.Condition.setIdentifier (Identifier myId)
Implements engine.gameObject.Identifiable.
Definition at line 57 of file Condition.java.
References engine.conditions.Condition.myId.
Referenced by engine.tests.MainEngineTests.createGameObject(), and authoring.eventhandlers.AddConditionHandler.finishCondition().
Member Data Documentation
List<Action> engine.conditions.Condition.myActions = new ArrayList<Action>() protected
Definition at line 23 of file Condition.java.
Referenced by engine.conditions.TypeCollisionCondition.checkCollisions(), and engine.conditions.Condition.getActions().
Boolean engine.conditions.Condition.myEnabled private
Definition at line 24 of file Condition.java.
Referenced by engine.conditions.Condition.isEnabled().
transient GameManager engine.conditions.Condition.myGameManager protected
Definition at line 25 of file Condition.java.
Referenced by engine.conditions.Condition.getGameManager().
Identifier engine.conditions.Condition.myId protected
Definition at line 26 of file Condition.java.
Referenced by engine.conditions.Condition.getIdentifier(), engine.conditions.ButtonPressCondition.getKeyIdentifier(), engine.conditions.ButtonReleaseCondition.getKeyIdentifier(), engine.conditions.Condition.setIdentifier(), engine.conditions.ButtonPressCondition.setKeyIdentifier(), and engine.conditions.ButtonReleaseCondition.setKeyIdentifier().
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/voogasalad_BitsPlease/repository/src/engine/conditions/Condition.java