voogasalad_BitsPlease: data.Observable Class Reference
data.Observable Class Reference
Public Member Functions
Observable ()
synchronized void addObserver (Observer o)
synchronized void deleteObserver (Observer o)
void notifyObservers ()
void notifyObservers (Object arg)
synchronized void deleteObservers ()
synchronized boolean hasChanged ()
synchronized int countObservers ()
Protected Member Functions
synchronized void setChanged ()
synchronized void clearChanged ()
Private Attributes
transient boolean changed = false
transient Vector< Observer > obs
Detailed Description
This class represents an observable object, or "data" in the model-view paradigm. It can be subclassed to represent an object that the application wants to have observed.
An observable object can have one or more observers. An observer may be any object that implements interface Observer. After an observable instance changes, an application calling the Observable's notifyObservers method causes all of its observers to be notified of the change by a call to their update method.
The order in which notifications will be delivered is unspecified. The default implementation provided in the Observable class will notify Observers in the order in which they registered interest, but subclasses may change this order, use no guaranteed order, deliver notifications on separate threads, or may guarantee that their subclass follows this order, as they choose.
Note that this notification mechanism has nothing to do with threads and is completely separate from the wait and notify mechanism of class Object.
When an observable object is newly created, its set of observers is empty. Two observers are considered the same if and only if the equals method returns true for them.
Author
Chris Warth
See also
java.util.Observable::notifyObservers()
java.util.Observable::notifyObservers(java.lang.Object)
java.util.Observer
java.util.Observer::update(java.util.Observable, java.lang.Object)
Since
JDK1.0
Definition at line 64 of file Observable.java.
Constructor & Destructor Documentation
data.Observable.Observable ()
Construct an Observable with zero Observers.
Definition at line 70 of file Observable.java.
Member Function Documentation
synchronized void data.Observable.addObserver (Observer o)
Adds an observer to the set of observers for this object, provided that it is not the same as some observer already in the set. The order in which notifications will be delivered to multiple observers is not specified. See the class comment.
Parameters
o an observer to be added.
Exceptions
NullPointerException if the parameter o is null.
Definition at line 83 of file Observable.java.
Referenced by authoring.eventhandlers.AddLevelHandler.createLevel(), and authoring.eventhandlers.LevelToViewHandler.handle().
synchronized void data.Observable.clearChanged () protected
Indicates that this object has no longer changed, or that it has already notified all of its observers of its most recent change, so that the hasChanged method will now return false. This method is called automatically by the notifyObservers methods.
See also
java.util.Observable::notifyObservers()
java.util.Observable::notifyObservers(java.lang.Object)
Definition at line 189 of file Observable.java.
Referenced by data.Observable.notifyObservers().
synchronized int data.Observable.countObservers ()
Returns the number of observers of this Observable object.
Returns
the number of observers of this object.
Definition at line 212 of file Observable.java.
synchronized void data.Observable.deleteObserver (Observer o)
Deletes an observer from the set of observers of this object. Passing null to this method will have no effect.
Parameters
o the observer to be deleted.
Definition at line 96 of file Observable.java.
synchronized void data.Observable.deleteObservers ()
Clears the observer list so that this object no longer has any observers.
Definition at line 167 of file Observable.java.
synchronized boolean data.Observable.hasChanged ()
Tests if this object has changed.
Returns
true if and only if the setChanged method has been called more recently than the clearChanged method on this object; false otherwise.
See also
java.util.Observable::clearChanged()
java.util.Observable::setChanged()
Definition at line 203 of file Observable.java.
References data.Observable.changed.
void data.Observable.notifyObservers ()
If this object has changed, as indicated by the hasChanged method, then notify all of its observers and then call the clearChanged method to indicate that this object has no longer changed.
Each observer has its update method called with two arguments: this observable object and null. In other words, this method is equivalent to:
notifyObservers(null)
See also
java.util.Observable::clearChanged()
java.util.Observable::hasChanged()
java.util.Observer::update(java.util.Observable, java.lang.Object)
Definition at line 116 of file Observable.java.
Referenced by authoring.model.collections.GeneralCollection< GameObject >.add(), engine.level.Level.addGameObject(), and engine.level.Level.removeGameObject().
void data.Observable.notifyObservers (Object arg)
If this object has changed, as indicated by the hasChanged method, then notify all of its observers and then call the clearChanged method to indicate that this object has no longer changed.
Each observer has its update method called with two arguments: this observable object and the arg argument.
Parameters
arg any object.
See also
java.util.Observable::clearChanged()
java.util.Observable::hasChanged()
java.util.Observer::update(java.util.Observable, java.lang.Object)
Definition at line 134 of file Observable.java.
References data.Observable.clearChanged().
synchronized void data.Observable.setChanged () protected
Marks this Observable object as having been changed; the hasChanged method will now return true.
Definition at line 175 of file Observable.java.
Referenced by authoring.model.collections.GeneralCollection< GameObject >.add(), engine.level.Level.addGameObject(), and engine.level.Level.removeGameObject().
Member Data Documentation
transient boolean data.Observable.changed = false private
Definition at line 65 of file Observable.java.
Referenced by data.Observable.hasChanged().
transient Vector<Observer> data.Observable.obs private
Definition at line 66 of file Observable.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/voogasalad_BitsPlease/repository/src/data/Observable.java