voogasalad_BitsPlease: authoring.eventhandlers.AddObjectHandler Class Reference
authoring.eventhandlers.AddObjectHandler Class Reference
Public Member Functions
AddObjectHandler (GameObjectsCollection myGameObjectCollection)
void handle (Event arg0)
EventType< Event > getEventType ()
void createGameObject ()
void updateName ()
Public Member Functions inherited from authoring.eventhandlers.GameHandler< Event >
void handle (T arg0)
EventType< T > getEventType ()
Private Attributes
GameObjectsCollection myGameObjectCollection
Wizard myWizard
NameWizard myNameWizard
GameObject myNewGameObject
Static Private Attributes
static final double NEW_GAMEOBJECT_WINDOW_HEIGHT = 400
static final double NEW_GAMEOBJECT_WINDOW_WIDTH = 400
Detailed Description
Author
Kevin Li
Arjun Jain
Chris Bernt
Wesley Valentine
Safkat Islam
Definition at line 25 of file AddObjectHandler.java.
Constructor & Destructor Documentation
authoring.eventhandlers.AddObjectHandler.AddObjectHandler (GameObjectsCollection myGameObjectCollection)
Definition at line 34 of file AddObjectHandler.java.
References authoring.eventhandlers.AddObjectHandler.myGameObjectCollection.
Member Function Documentation
void authoring.eventhandlers.AddObjectHandler.createGameObject ()
Definition at line 51 of file AddObjectHandler.java.
References authoring.view.wizards.Wizard.getMap(), engine.gameObject.GameObject.setPhysicsBody(), engine.gameObject.components.PhysicsBody.setVelocity(), and authoring.eventhandlers.AddObjectHandler.updateName().
Referenced by authoring.eventhandlers.AddObjectHandler.handle().
EventType<Event> authoring.eventhandlers.AddObjectHandler.getEventType ()
Definition at line 47 of file AddObjectHandler.java.
void authoring.eventhandlers.AddObjectHandler.handle (Event arg0)
Definition at line 39 of file AddObjectHandler.java.
References authoring.eventhandlers.AddObjectHandler.createGameObject().
void authoring.eventhandlers.AddObjectHandler.updateName ()
Definition at line 73 of file AddObjectHandler.java.
References authoring.model.collections.GeneralCollection< T >.add(), errorsAndExceptions.ErrorPopUp.display(), authoring.view.wizards.Wizard.getMap(), authoring.view.wizards.NameWizard.isDuplicated(), and engine.gameObject.GameObject.setIdentifier().
Referenced by authoring.eventhandlers.AddObjectHandler.createGameObject().
Member Data Documentation
GameObjectsCollection authoring.eventhandlers.AddObjectHandler.myGameObjectCollection private
Definition at line 27 of file AddObjectHandler.java.
Referenced by authoring.eventhandlers.AddObjectHandler.AddObjectHandler().
NameWizard authoring.eventhandlers.AddObjectHandler.myNameWizard private
Definition at line 31 of file AddObjectHandler.java.
GameObject authoring.eventhandlers.AddObjectHandler.myNewGameObject private
Definition at line 32 of file AddObjectHandler.java.
Wizard authoring.eventhandlers.AddObjectHandler.myWizard private
Definition at line 30 of file AddObjectHandler.java.
final double authoring.eventhandlers.AddObjectHandler.NEW_GAMEOBJECT_WINDOW_HEIGHT = 400 static private
Definition at line 28 of file AddObjectHandler.java.
final double authoring.eventhandlers.AddObjectHandler.NEW_GAMEOBJECT_WINDOW_WIDTH = 400 static private
Definition at line 29 of file AddObjectHandler.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/voogasalad_BitsPlease/repository/src/authoring/eventhandlers/AddObjectHandler.java