voogasalad_BitsPlease: authoring.view.levelview.SingleLevelView Class Reference
authoring.view.levelview.SingleLevelView Class Reference
Public Member Functions
SingleLevelView (File gameLoc, double width, double height, String bgImage, GameHandler...handlers)
SingleLevelView (File gameLoc, double width, double height, Level l, GameHandler...handlers)
void setPaneSize (double width, double height)
void recreateLevel (Level l)
void update (Observable o, Object arg)
void setID (String ID)
String getID ()
void moveGameObjectToLevel (ImageBasedIcon g, double x, double y)
double getViewWidth ()
double getViewHeight ()
double getPaneWidth ()
double getPaneHeight ()
Static Public Attributes
static final double OBJECT_X_OFFSET = -Main.SCREEN_WIDTH * .2
static final double OBJECT_Y_OFFSET = -Main.SCREEN_HEIGHT * .23
Private Member Functions
void setView (double width, double height)
void addGameObjectToView (GameObject gameObject, double x, double y, GameHandler...handler)
Private Attributes
Background myDefaultBackground
File myGameLocation
Rectangle myGameOutline
GameHandler[] myEvents
String myID
Pane myGamePane
String myBackgroundImage
Static Private Attributes
static final int GAME_HEIGHT = 400
static final int GAME_WIDTH = 400
static final double VIEW_HEIGHT_RATIO = .80
static final double VIEW_WIDTH_RATIO = 0.6
Detailed Description
Class that contains the visualization data of a single level.
Author
Kevin Li
Definition at line 35 of file SingleLevelView.java.
Constructor & Destructor Documentation
authoring.view.levelview.SingleLevelView.SingleLevelView (File gameLoc, double width, double height, String bgImage, GameHandler... handlers)
Definition at line 53 of file SingleLevelView.java.
References authoring.view.levelview.SingleLevelView.setView().
authoring.view.levelview.SingleLevelView.SingleLevelView (File gameLoc, double width, double height, Level l, GameHandler... handlers)
Parameters
width
height
l
handlers
Definition at line 88 of file SingleLevelView.java.
References engine.level.Level.getBackgroundImage(), and authoring.view.levelview.SingleLevelView.recreateLevel().
Member Function Documentation
void authoring.view.levelview.SingleLevelView.addGameObjectToView (GameObject gameObject, double x, double y, GameHandler... handler) private
Definition at line 132 of file SingleLevelView.java.
References engine.gameObject.GameObject.getHeight(), engine.gameObject.GameObject.getRotation(), engine.gameObject.GameObject.getWidth(), authoring.view.levelview.SingleLevelView.moveGameObjectToLevel(), and authoring.view.icons.ImageBasedIcon.setDimensions().
Referenced by authoring.view.levelview.SingleLevelView.recreateLevel().
String authoring.view.levelview.SingleLevelView.getID ()
Definition at line 157 of file SingleLevelView.java.
References authoring.view.levelview.SingleLevelView.myID.
Referenced by authoring.eventhandlers.DeleteGameObjectHandler.handle(), authoring.eventhandlers.EditGameObjectHandler.handle(), authoring.eventhandlers.GameObjectDragHandler.handle(), and authoring.eventhandlers.GameObjectDragToLevelHandler.handle().
double authoring.view.levelview.SingleLevelView.getPaneHeight ()
Definition at line 178 of file SingleLevelView.java.
Referenced by authoring.eventhandlers.GameObjGraphicDragHandler.handle(), and authoring.eventhandlers.GameObjectDragHandler.handle().
double authoring.view.levelview.SingleLevelView.getPaneWidth ()
Definition at line 174 of file SingleLevelView.java.
Referenced by authoring.eventhandlers.GameObjGraphicDragHandler.handle(), and authoring.eventhandlers.GameObjectDragHandler.handle().
double authoring.view.levelview.SingleLevelView.getViewHeight ()
Definition at line 170 of file SingleLevelView.java.
Referenced by authoring.eventhandlers.GameObjGraphicDragHandler.handle(), and authoring.eventhandlers.GameObjectDragHandler.handle().
double authoring.view.levelview.SingleLevelView.getViewWidth ()
Definition at line 166 of file SingleLevelView.java.
Referenced by authoring.eventhandlers.GameObjGraphicDragHandler.handle(), and authoring.eventhandlers.GameObjectDragHandler.handle().
void authoring.view.levelview.SingleLevelView.moveGameObjectToLevel (ImageBasedIcon g, double x, double y)
Definition at line 161 of file SingleLevelView.java.
Referenced by authoring.view.levelview.SingleLevelView.addGameObjectToView(), and authoring.eventhandlers.GameObjGraphicDragHandler.handle().
void authoring.view.levelview.SingleLevelView.recreateLevel (Level l)
Definition at line 115 of file SingleLevelView.java.
References authoring.view.levelview.SingleLevelView.addGameObjectToView(), engine.level.Level.getGameObjectsCollection(), and authoring.view.levelview.SingleLevelView.myEvents.
Referenced by authoring.view.levelview.SingleLevelView.SingleLevelView(), and authoring.view.levelview.SingleLevelView.update().
void authoring.view.levelview.SingleLevelView.setID (String ID)
public void removeGameObjectFromView(GameObject gameObject) { GameObjectGraphic g = new GameObjectGraphic(gameObject, myEvents); System.out.println(this.getChildren().contains(g)); this.getChildren().remove(g); }
Definition at line 153 of file SingleLevelView.java.
Referenced by authoring.eventhandlers.AddLevelHandler.createLevel(), and authoring.eventhandlers.LevelToViewHandler.handle().
void authoring.view.levelview.SingleLevelView.setPaneSize (double width, double height)
Definition at line 103 of file SingleLevelView.java.
Referenced by authoring.eventhandlers.AddLevelHandler.createLevel().
void authoring.view.levelview.SingleLevelView.setView (double width, double height) private
Definition at line 96 of file SingleLevelView.java.
Referenced by authoring.view.levelview.SingleLevelView.SingleLevelView().
void authoring.view.levelview.SingleLevelView.update (Observable o, Object arg)
This method is called whenever the observed object is changed. An application calls an Observable object's notifyObservers method to have all the object's observers notified of the change.
Parameters
o the observable object.
arg an argument passed to the notifyObservers method.
Implements data.Observer.
Definition at line 123 of file SingleLevelView.java.
References authoring.view.levelview.SingleLevelView.recreateLevel().
Member Data Documentation
final int authoring.view.levelview.SingleLevelView.GAME_HEIGHT = 400 static private
Definition at line 36 of file SingleLevelView.java.
final int authoring.view.levelview.SingleLevelView.GAME_WIDTH = 400 static private
Definition at line 37 of file SingleLevelView.java.
String authoring.view.levelview.SingleLevelView.myBackgroundImage private
Definition at line 51 of file SingleLevelView.java.
Background authoring.view.levelview.SingleLevelView.myDefaultBackground private
Initial value:
= new Background(new BackgroundFill(
            Color.WHITE, CornerRadii.EMPTY, Insets.EMPTY))
Definition at line 38 of file SingleLevelView.java.
GameHandler [] authoring.view.levelview.SingleLevelView.myEvents private
Definition at line 48 of file SingleLevelView.java.
Referenced by authoring.view.levelview.SingleLevelView.recreateLevel().
File authoring.view.levelview.SingleLevelView.myGameLocation private
Definition at line 46 of file SingleLevelView.java.
Rectangle authoring.view.levelview.SingleLevelView.myGameOutline private
Definition at line 47 of file SingleLevelView.java.
Pane authoring.view.levelview.SingleLevelView.myGamePane private
Definition at line 50 of file SingleLevelView.java.
String authoring.view.levelview.SingleLevelView.myID private
Definition at line 49 of file SingleLevelView.java.
Referenced by authoring.view.levelview.SingleLevelView.getID().
final double authoring.view.levelview.SingleLevelView.OBJECT_X_OFFSET = -Main.SCREEN_WIDTH * .2 static
Definition at line 44 of file SingleLevelView.java.
final double authoring.view.levelview.SingleLevelView.OBJECT_Y_OFFSET = -Main.SCREEN_HEIGHT * .23 static
Definition at line 45 of file SingleLevelView.java.
final double authoring.view.levelview.SingleLevelView.VIEW_HEIGHT_RATIO = .80 static private
Definition at line 41 of file SingleLevelView.java.
final double authoring.view.levelview.SingleLevelView.VIEW_WIDTH_RATIO = 0.6 static private
Definition at line 42 of file SingleLevelView.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/voogasalad_BitsPlease/repository/src/authoring/view/levelview/SingleLevelView.java