voogasalad_BitsPlease: authoring.view.gameobjectsview.GameObjectOptions Class Reference
authoring.view.gameobjectsview.GameObjectOptions Class Reference
Public Member Functions
GameObjectOptions (ResourceBundle language, double width, double height)
void setButtonBehavior (GameHandler handler)
Public Member Functions inherited from authoring.view.generalcollectionview.CollectionOptions
CollectionOptions (ResourceBundle language, double width, double height)
Private Member Functions
void addNewTabButton ()
Private Attributes
Button addObjectButton
Additional Inherited Members
Protected Member Functions inherited from authoring.view.generalcollectionview.CollectionOptions
Button makeButton (String property)
Protected Attributes inherited from authoring.view.generalcollectionview.CollectionOptions
ResourceBundle myLanguage
double myHeight
double myWidth
Detailed Description
Definition at line 9 of file GameObjectOptions.java.
Constructor & Destructor Documentation
authoring.view.gameobjectsview.GameObjectOptions.GameObjectOptions (ResourceBundle language, double width, double height)
Definition at line 13 of file GameObjectOptions.java.
References authoring.view.gameobjectsview.GameObjectOptions.addNewTabButton().
Member Function Documentation
void authoring.view.gameobjectsview.GameObjectOptions.addNewTabButton () private
Definition at line 18 of file GameObjectOptions.java.
References authoring.view.generalcollectionview.CollectionOptions.makeButton(), and authoring.view.generalcollectionview.CollectionOptions.myLanguage.
Referenced by authoring.view.gameobjectsview.GameObjectOptions.GameObjectOptions().
void authoring.view.gameobjectsview.GameObjectOptions.setButtonBehavior (GameHandler handler)
Definition at line 23 of file GameObjectOptions.java.
Referenced by authoring.controller.AuthoringController.initializeGameHandlers().
Member Data Documentation
Button authoring.view.gameobjectsview.GameObjectOptions.addObjectButton private
Definition at line 11 of file GameObjectOptions.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/voogasalad_BitsPlease/repository/src/authoring/view/gameobjectsview/GameObjectOptions.java