voogasalad_BitsPlease: authoring.eventhandlers.DeleteConditionHandler Class Reference
authoring.eventhandlers.DeleteConditionHandler Class Reference
Public Member Functions
DeleteConditionHandler (ConditionsCollection collection)
void handle (Event arg0)
EventType< Event > getEventType ()
Public Member Functions inherited from authoring.eventhandlers.GameHandler< Event >
void handle (T arg0)
EventType< T > getEventType ()
Private Member Functions
void deleteCondition ()
Private Attributes
ConditionsCollection myConditionsCollection
Wizard myDeleteConditionHandler
Detailed Description
Definition at line 9 of file DeleteConditionHandler.java.
Constructor & Destructor Documentation
authoring.eventhandlers.DeleteConditionHandler.DeleteConditionHandler (ConditionsCollection collection)
Definition at line 14 of file DeleteConditionHandler.java.
Member Function Documentation
void authoring.eventhandlers.DeleteConditionHandler.deleteCondition () private
Definition at line 30 of file DeleteConditionHandler.java.
References authoring.view.wizards.Wizard.getMap(), and authoring.model.collections.ConditionsCollection.removeByID().
Referenced by authoring.eventhandlers.DeleteConditionHandler.handle().
EventType<Event> authoring.eventhandlers.DeleteConditionHandler.getEventType ()
Definition at line 26 of file DeleteConditionHandler.java.
void authoring.eventhandlers.DeleteConditionHandler.handle (Event arg0)
Definition at line 19 of file DeleteConditionHandler.java.
References authoring.eventhandlers.DeleteConditionHandler.deleteCondition().
Member Data Documentation
ConditionsCollection authoring.eventhandlers.DeleteConditionHandler.myConditionsCollection private
Definition at line 11 of file DeleteConditionHandler.java.
Wizard authoring.eventhandlers.DeleteConditionHandler.myDeleteConditionHandler private
Definition at line 12 of file DeleteConditionHandler.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/voogasalad_BitsPlease/repository/src/authoring/eventhandlers/DeleteConditionHandler.java