voogasalad_BitsPlease: gamePlayer.view.PlayerView Class Reference
gamePlayer.view.PlayerView Class Reference
Public Member Functions
PlayerView (PlayerModel playerModel)
void initialize () throws IOException
Group getGroup ()
void close ()
Private Member Functions
void initializeGUIComponents ()
Private Attributes
PlayerModel myPlayerModel
Stage myStage
Scene myScene
GameCanvas myCanvas
BorderPane myRoot
Detailed Description
Author
Shreyas B
Abhishek B
Definition at line 19 of file PlayerView.java.
Constructor & Destructor Documentation
gamePlayer.view.PlayerView.PlayerView (PlayerModel playerModel)
Definition at line 27 of file PlayerView.java.
Member Function Documentation
void gamePlayer.view.PlayerView.close ()
Definition at line 64 of file PlayerView.java.
Referenced by gamePlayer.model.PlayerModel.exitFromGamePlayer().
Group gamePlayer.view.PlayerView.getGroup ()
Definition at line 60 of file PlayerView.java.
References gamePlayer.view.GameCanvas.getNode().
Referenced by gamePlayer.model.PlayerModel.loadGameData().
void gamePlayer.view.PlayerView.initialize () throws IOException
Initialize player view from the FXML file
Exceptions
IOException
Definition at line 37 of file PlayerView.java.
References gamePlayer.view.PlayerView.initializeGUIComponents(), gamePlayer.view.MenuBarController.setKeyboard(), and gamePlayer.view.MenuBarController.setModel().
Referenced by gamePlayer.model.PlayerModel.initializeView().
void gamePlayer.view.PlayerView.initializeGUIComponents () private
Set content for the stage and scene
Definition at line 49 of file PlayerView.java.
References engine.conditions.ButtonConditionManager.beginListeningToScene(), engine.conditions.ButtonConditionManager.getInstance(), and gamePlayer.view.GameCanvas.getNode().
Referenced by gamePlayer.view.PlayerView.initialize().
Member Data Documentation
GameCanvas gamePlayer.view.PlayerView.myCanvas private
Definition at line 24 of file PlayerView.java.
PlayerModel gamePlayer.view.PlayerView.myPlayerModel private
Definition at line 21 of file PlayerView.java.
BorderPane gamePlayer.view.PlayerView.myRoot private
Definition at line 25 of file PlayerView.java.
Scene gamePlayer.view.PlayerView.myScene private
Definition at line 23 of file PlayerView.java.
Stage gamePlayer.view.PlayerView.myStage private
Definition at line 22 of file PlayerView.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/voogasalad_BitsPlease/repository/src/gamePlayer/view/PlayerView.java