voogasalad_BitsPlease: authoring.view.levelview.LevelOptions Class Reference
authoring.view.levelview.LevelOptions Class Reference
Public Member Functions
LevelOptions (ResourceBundle language, double width, double height)
void setAddLevelButtonBehavior (GameHandler handler)
void setDeleteLevelButtonBehavior (GameHandler handler)
Public Member Functions inherited from authoring.view.generalcollectionview.CollectionOptions
CollectionOptions (ResourceBundle language, double width, double height)
Private Member Functions
void addNewButtons ()
Private Attributes
Button addLevelButton
Button deleteLevelButton
Additional Inherited Members
Protected Member Functions inherited from authoring.view.generalcollectionview.CollectionOptions
Button makeButton (String property)
Protected Attributes inherited from authoring.view.generalcollectionview.CollectionOptions
ResourceBundle myLanguage
double myHeight
double myWidth
Detailed Description
Author
Kevin Li
Chris Bernt
Wesley Valentine
Arjun Jain
Definition at line 20 of file LevelOptions.java.
Constructor & Destructor Documentation
authoring.view.levelview.LevelOptions.LevelOptions (ResourceBundle language, double width, double height)
Definition at line 24 of file LevelOptions.java.
References authoring.view.levelview.LevelOptions.addNewButtons().
Member Function Documentation
void authoring.view.levelview.LevelOptions.addNewButtons () private
Definition at line 29 of file LevelOptions.java.
References authoring.view.generalcollectionview.CollectionOptions.makeButton(), and authoring.view.generalcollectionview.CollectionOptions.myLanguage.
Referenced by authoring.view.levelview.LevelOptions.LevelOptions().
void authoring.view.levelview.LevelOptions.setAddLevelButtonBehavior (GameHandler handler)
Definition at line 36 of file LevelOptions.java.
Referenced by authoring.controller.AuthoringController.initializeGameHandlers().
void authoring.view.levelview.LevelOptions.setDeleteLevelButtonBehavior (GameHandler handler)
Definition at line 40 of file LevelOptions.java.
Referenced by authoring.controller.AuthoringController.initializeGameHandlers().
Member Data Documentation
Button authoring.view.levelview.LevelOptions.addLevelButton private
Definition at line 21 of file LevelOptions.java.
Button authoring.view.levelview.LevelOptions.deleteLevelButton private
Definition at line 22 of file LevelOptions.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/voogasalad_BitsPlease/repository/src/authoring/view/levelview/LevelOptions.java