voogasalad_BitsPlease: authoring.eventhandlers.AddConditionIDHandler Class Reference
authoring.eventhandlers.AddConditionIDHandler Class Reference
Public Member Functions
AddConditionIDHandler (Level level)
void handle (Event arg0)
EventType< Event > getEventType ()
void addNewCondition ()
Public Member Functions inherited from authoring.eventhandlers.GameHandler< Event >
void handle (T arg0)
EventType< T > getEventType ()
Private Attributes
Level myLevel
AddConditionIDWizard myWizard
Detailed Description
Definition at line 11 of file AddConditionIDHandler.java.
Constructor & Destructor Documentation
authoring.eventhandlers.AddConditionIDHandler.AddConditionIDHandler (Level level)
Definition at line 16 of file AddConditionIDHandler.java.
Member Function Documentation
void authoring.eventhandlers.AddConditionIDHandler.addNewCondition ()
Definition at line 30 of file AddConditionIDHandler.java.
References engine.level.Level.getConditionCollection(), and authoring.view.wizards.Wizard.getMap().
Referenced by authoring.eventhandlers.AddConditionIDHandler.handle().
EventType<Event> authoring.eventhandlers.AddConditionIDHandler.getEventType ()
Definition at line 26 of file AddConditionIDHandler.java.
void authoring.eventhandlers.AddConditionIDHandler.handle (Event arg0)
Definition at line 21 of file AddConditionIDHandler.java.
References authoring.eventhandlers.AddConditionIDHandler.addNewCondition().
Member Data Documentation
Level authoring.eventhandlers.AddConditionIDHandler.myLevel private
Definition at line 13 of file AddConditionIDHandler.java.
AddConditionIDWizard authoring.eventhandlers.AddConditionIDHandler.myWizard private
Definition at line 14 of file AddConditionIDHandler.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/voogasalad_BitsPlease/repository/src/authoring/eventhandlers/AddConditionIDHandler.java