voogasalad_BitsPlease: engine.gameObject.Identifier Class Reference
engine.gameObject.Identifier Class Reference
Public Member Functions
Identifier (String myType, String myUniqueId)
Identifier (Identifier id)
String getType ()
void setType (String myType)
String getUniqueId ()
void setUniqueId (String myUniqueId)
String getHash ()
boolean equals (Object o)
int hashCode ()
Static Public Member Functions
static Identifier valueOf (String descriptor)
Private Attributes
String myType
String myUniqueId
Random r
Detailed Description
Definition at line 5 of file Identifier.java.
Constructor & Destructor Documentation
engine.gameObject.Identifier.Identifier (String myType, String myUniqueId)
Definition at line 11 of file Identifier.java.
References engine.gameObject.Identifier.myType, and engine.gameObject.Identifier.myUniqueId.
Referenced by engine.gameObject.Identifier.equals(), and engine.gameObject.Identifier.valueOf().
engine.gameObject.Identifier.Identifier (Identifier id)
Definition at line 16 of file Identifier.java.
Member Function Documentation
boolean engine.gameObject.Identifier.equals (Object o)
Definition at line 48 of file Identifier.java.
References engine.gameObject.Identifier.getHash(), and engine.gameObject.Identifier.Identifier().
String engine.gameObject.Identifier.getHash ()
Definition at line 43 of file Identifier.java.
References engine.gameObject.Identifier.myUniqueId.
Referenced by engine.gameObject.Identifier.equals(), and engine.gameObject.components.Component.getID().
String engine.gameObject.Identifier.getType ()
Definition at line 27 of file Identifier.java.
References engine.gameObject.Identifier.myType.
Referenced by authoring.view.wizards.GameObjectTypeWizard.getIdentifierComponent(), authoring.eventhandlers.GameObjectDragToLevelHandler.handle(), and authoring.view.propertiesview.GameObjectProperties.initializeProperties().
String engine.gameObject.Identifier.getUniqueId ()
Definition at line 35 of file Identifier.java.
References engine.gameObject.Identifier.myUniqueId.
Referenced by authoring.view.levelview.LevelsView.addExistingLevel(), authoring.view.wizards.GameObjectUniqueIDWizard.getIdentifierComponent(), engine.conditions.ButtonPressCondition.getKeyIdentifier(), engine.conditions.ButtonReleaseCondition.getKeyIdentifier(), authoring.eventhandlers.LevelToViewHandler.handle(), engine.level.Level.initialize(), authoring.view.propertiesview.GameObjectProperties.initializeProperties(), and engine.render.GameObjectRenderer.renderGameObjects().
int engine.gameObject.Identifier.hashCode ()
Definition at line 60 of file Identifier.java.
void engine.gameObject.Identifier.setType (String myType)
Definition at line 31 of file Identifier.java.
References engine.gameObject.Identifier.myType.
void engine.gameObject.Identifier.setUniqueId (String myUniqueId)
Definition at line 39 of file Identifier.java.
References engine.gameObject.Identifier.myUniqueId.
Referenced by engine.conditions.ButtonPressCondition.setKeyIdentifier(), engine.conditions.ButtonReleaseCondition.setKeyIdentifier(), and authoring.eventhandlers.GameObjectDragToLevelHandler.updateName().
static Identifier engine.gameObject.Identifier.valueOf (String descriptor) static
Definition at line 22 of file Identifier.java.
References engine.gameObject.Identifier.Identifier().
Member Data Documentation
String engine.gameObject.Identifier.myType private
Definition at line 6 of file Identifier.java.
Referenced by engine.gameObject.Identifier.getType(), engine.gameObject.Identifier.Identifier(), and engine.gameObject.Identifier.setType().
String engine.gameObject.Identifier.myUniqueId private
Definition at line 7 of file Identifier.java.
Referenced by engine.gameObject.Identifier.getHash(), engine.gameObject.Identifier.getUniqueId(), engine.gameObject.Identifier.Identifier(), and engine.gameObject.Identifier.setUniqueId().
Random engine.gameObject.Identifier.r private
Definition at line 8 of file Identifier.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/voogasalad_BitsPlease/repository/src/engine/gameObject/Identifier.java