voogasalad_BitsPlease: authoring.view.propertiesview.FileProperties Class Reference
authoring.view.propertiesview.FileProperties Class Reference
Public Member Functions
FileProperties (Object o)
void initializeProperties (Object o)
Public Member Functions inherited from authoring.view.propertiesview.Properties
abstract void initializeProperties (Object o)
void addMapToView ()
Additional Inherited Members
Protected Attributes inherited from authoring.view.propertiesview.Properties
Map< String, PropertyField > myMap = new LinkedHashMap<String, PropertyField>()
Detailed Description
Author
Kevin Li
Chris Bernt
Wesley Valentine
Arjun Jain
Definition at line 15 of file FileProperties.java.
Constructor & Destructor Documentation
authoring.view.propertiesview.FileProperties.FileProperties (Object o)
Definition at line 17 of file FileProperties.java.
References authoring.view.propertiesview.FileProperties.initializeProperties().
Member Function Documentation
void authoring.view.propertiesview.FileProperties.initializeProperties (Object o)
Definition at line 22 of file FileProperties.java.
References authoring.view.icons.BaseIcon.getName().
Referenced by authoring.view.propertiesview.FileProperties.FileProperties().
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/voogasalad_BitsPlease/repository/src/authoring/view/propertiesview/FileProperties.java