voogasalad_BitsPlease: engine.conditions.TypeCollisionCondition Class Reference
engine.conditions.TypeCollisionCondition Class Reference
Public Member Functions
TypeCollisionCondition (List< Action > actions, String firstType, String secondType)
void initialize (GameManager gameManager)
Public Member Functions inherited from engine.conditions.TimeCondition
TimeCondition (List< Action > myActions, Double frameElapseCount, Boolean repeats)
void respondToFrameElapsed ()
Public Member Functions inherited from engine.conditions.Condition
Condition (List< Action > actions)
List< Action > getActions ()
void setEnabled (Boolean enabled)
boolean isEnabled ()
void setInputMap (Map< String, String > inputs)
Map< String, String > getInputMap ()
void frameElapsed ()
void setIdentifier (Identifier myId)
Identifier getIdentifier ()
void initialize (GameManager manager)
void addAction (Action a)
Protected Member Functions
void executeActions ()
Protected Member Functions inherited from engine.conditions.TimeCondition
void executeActions ()
Protected Member Functions inherited from engine.conditions.Condition
abstract void executeActions ()
abstract void respondToFrameElapsed ()
void initializeActions (GameManager manager)
GameManager getGameManager ()
Private Member Functions
void checkCollisions ()
Private Attributes
Map< String, Integer > myCollisionMap
String firstCollisionType
String secondCollisionType
GameObjectsCollection myGameObjects
Additional Inherited Members
Protected Attributes inherited from engine.conditions.Condition
List< Action > myActions = new ArrayList<Action>()
transient GameManager myGameManager
Identifier myId
Detailed Description
Author
Davis
conditions caused by collisions of two nodes
Definition at line 21 of file TypeCollisionCondition.java.
Constructor & Destructor Documentation
engine.conditions.TypeCollisionCondition.TypeCollisionCondition (List< Action > actions, String firstType, String secondType)
Definition at line 29 of file TypeCollisionCondition.java.
Member Function Documentation
void engine.conditions.TypeCollisionCondition.checkCollisions () private
Definition at line 54 of file TypeCollisionCondition.java.
References engine.conditions.Condition.myActions.
Referenced by engine.conditions.TypeCollisionCondition.executeActions().
void engine.conditions.TypeCollisionCondition.executeActions () protected
Definition at line 46 of file TypeCollisionCondition.java.
References engine.conditions.TypeCollisionCondition.checkCollisions().
void engine.conditions.TypeCollisionCondition.initialize (GameManager gameManager)
Implements engine.actions.Initializable.
Definition at line 40 of file TypeCollisionCondition.java.
References engine.level.LevelManager.getCurrentLevel(), engine.level.Level.getGameObjectsCollection(), engine.GameManager.getLevelManager(), and engine.conditions.Condition.initializeActions().
Member Data Documentation
String engine.conditions.TypeCollisionCondition.firstCollisionType private
Definition at line 24 of file TypeCollisionCondition.java.
Map<String,Integer> engine.conditions.TypeCollisionCondition.myCollisionMap private
Definition at line 23 of file TypeCollisionCondition.java.
GameObjectsCollection engine.conditions.TypeCollisionCondition.myGameObjects private
Definition at line 26 of file TypeCollisionCondition.java.
String engine.conditions.TypeCollisionCondition.secondCollisionType private
Definition at line 25 of file TypeCollisionCondition.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/voogasalad_BitsPlease/repository/src/engine/conditions/TypeCollisionCondition.java