voogasalad_BitsPlease: authoring.model.collections.GeneralCollection< T > Class Template Reference
authoring.model.collections.GeneralCollection< T > Class Template Reference abstract
Public Member Functions
GeneralCollection ()
Iterator< T > iterator ()
T get (int i)
boolean remove (T a)
void add (T a)
void addAll (GeneralCollection< T > collection)
String toString ()
int getSize ()
Public Member Functions inherited from data.Observable
Observable ()
synchronized void addObserver (Observer o)
synchronized void deleteObserver (Observer o)
void notifyObservers ()
void notifyObservers (Object arg)
synchronized void deleteObservers ()
synchronized boolean hasChanged ()
synchronized int countObservers ()
Protected Attributes
List< T > myObjects
Additional Inherited Members
Protected Member Functions inherited from data.Observable
synchronized void setChanged ()
synchronized void clearChanged ()
Detailed Description
General Collection is the abstract superclass for all collections held in the game. Uses generics to share common behavior.
Author
Arjun Jain
Parameters
<T> The generic type of object we want to make a collection of.
Definition at line 16 of file GeneralCollection.java.
Constructor & Destructor Documentation
authoring.model.collections.GeneralCollection< T >.GeneralCollection ()
Definition at line 21 of file GeneralCollection.java.
Member Function Documentation
void authoring.model.collections.GeneralCollection< T >.add (T a)
Definition at line 39 of file GeneralCollection.java.
Referenced by engine.conditions.GameObjectCondition.addGameObject(), engine.level.Level.addGameObject(), engine.level.Level.addInitialGameObjects(), authoring.model.AuthoringModel.convertFromSerializable(), authoring.model.AuthoringModel.convertToSerializable(), engine.tests.MainEngineTests.createGameObject(), games.MarioGameTest.createGameObject(), authoring.eventhandlers.FileDropHandler.handle(), authoring.eventhandlers.AddFileHandler.handle(), engine.actions.IDAction.initialize(), engine.actions.ChangeComponentIDAction.initialize(), engine.conditions.GameObjectCondition.initialize(), engine.actions.TranslateIDAction.initialize(), engine.level.Level.initialize(), engine.level.LevelManager.makeTemplates(), authoring.eventhandlers.SaveAsNewHandler.updateName(), and authoring.eventhandlers.AddObjectHandler.updateName().
void authoring.model.collections.GeneralCollection< T >.addAll (GeneralCollection< T > collection)
Definition at line 45 of file GeneralCollection.java.
Referenced by engine.tests.MainEngineTests.createGameObject(), and games.MarioGameTest.createGameObject().
T authoring.model.collections.GeneralCollection< T >.get (int i)
Definition at line 31 of file GeneralCollection.java.
Referenced by engine.tests.MainEngineTests.createGameObject(), games.MarioGameTest.createGameObject(), and engine.actions.MakeNewObjectFromList.execute().
int authoring.model.collections.GeneralCollection< T >.getSize ()
Definition at line 53 of file GeneralCollection.java.
Referenced by engine.actions.MakeNewObjectFromList.execute().
Iterator<T> authoring.model.collections.GeneralCollection< T >.iterator ()
Definition at line 27 of file GeneralCollection.java.
Referenced by gamePlayer.view.keyboardUtility.KeyboardView.comboBoxForButton(), engine.actions.DeleteTypeAction.execute(), engine.level.Level.getGameObjectIterator(), and engine.level.LevelManager.iterator().
boolean authoring.model.collections.GeneralCollection< T >.remove (T a)
Definition at line 35 of file GeneralCollection.java.
Referenced by authoring.model.AuthoringModel.convertFromSerializable(), and engine.level.Level.removeGameObject().
String authoring.model.collections.GeneralCollection< T >.toString ()
Definition at line 49 of file GeneralCollection.java.
Member Data Documentation
List<T> authoring.model.collections.GeneralCollection< T >.myObjects protected
Definition at line 19 of file GeneralCollection.java.
Referenced by authoring.model.collections.GeneralCollection< GameObject >.addAll().
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/voogasalad_BitsPlease/repository/src/authoring/model/collections/GeneralCollection.java