voogasalad_BitsPlease: gamePlayer.view.ProgressSelector Class Reference
gamePlayer.view.ProgressSelector Class Reference
Public Member Functions
ProgressSelector (File gameLocation, StringProperty progressFileName)
void loadProgressState ()
void saveProgressState (GameData saveData)
Package Attributes
ObservableList< String > myProgressList
ListView< String > myProgressListView
String selectedProgressState
File myGameLocation
File myProgressFolder
DataManager myDataManager
StringProperty myProgressFileName
Stage myProgressStage
Private Member Functions
void addListViewListener ()
void updateProgressList ()
void buildLoadWindow ()
void buildSaveWindow (GameData saveData)
Button createButton (String title, EventHandler< ActionEvent > event)
VBox setupWindow (String title)
void loadProgressEvent ()
void saveProgressEvent (TextField name, GameData saveData)
void overwriteProgressEvent (GameData saveData)
Static Private Attributes
static final int TEXT_COLUMN_COUNT = 20
Detailed Description
Class that displays names of available progress states and lets user choose progress state. Hides actual files from user.
Author
Eli Lichtenberg
Definition at line 29 of file ProgressSelector.java.
Constructor & Destructor Documentation
gamePlayer.view.ProgressSelector.ProgressSelector (File gameLocation, StringProperty progressFileName)
Definition at line 41 of file ProgressSelector.java.
References gamePlayer.view.ProgressSelector.addListViewListener(), gamePlayer.view.ProgressSelector.myProgressList, and data.DataManager.PROGRESS_FOLDER_NAME.
Member Function Documentation
void gamePlayer.view.ProgressSelector.addListViewListener () private
Definition at line 51 of file ProgressSelector.java.
Referenced by gamePlayer.view.ProgressSelector.ProgressSelector().
void gamePlayer.view.ProgressSelector.buildLoadWindow () private
Definition at line 86 of file ProgressSelector.java.
References gamePlayer.view.ProgressSelector.createButton(), gamePlayer.view.ProgressSelector.loadProgressEvent(), and gamePlayer.view.ProgressSelector.setupWindow().
Referenced by gamePlayer.view.ProgressSelector.loadProgressState().
void gamePlayer.view.ProgressSelector.buildSaveWindow (GameData saveData) private
Definition at line 92 of file ProgressSelector.java.
References gamePlayer.view.ProgressSelector.createButton(), gamePlayer.view.ProgressSelector.overwriteProgressEvent(), gamePlayer.view.ProgressSelector.saveProgressEvent(), and gamePlayer.view.ProgressSelector.setupWindow().
Referenced by gamePlayer.view.ProgressSelector.saveProgressState().
Button gamePlayer.view.ProgressSelector.createButton (String title, EventHandler< ActionEvent > event) private
Definition at line 107 of file ProgressSelector.java.
Referenced by gamePlayer.view.ProgressSelector.buildLoadWindow(), and gamePlayer.view.ProgressSelector.buildSaveWindow().
void gamePlayer.view.ProgressSelector.loadProgressEvent () private
Definition at line 125 of file ProgressSelector.java.
Referenced by gamePlayer.view.ProgressSelector.buildLoadWindow().
void gamePlayer.view.ProgressSelector.loadProgressState ()
Definition at line 76 of file ProgressSelector.java.
References gamePlayer.view.ProgressSelector.buildLoadWindow(), and gamePlayer.view.ProgressSelector.updateProgressList().
Referenced by gamePlayer.model.PlayerModel.loadGameProgress().
void gamePlayer.view.ProgressSelector.overwriteProgressEvent (GameData saveData) private
Definition at line 140 of file ProgressSelector.java.
References data.DataManager.writeProgressFile().
Referenced by gamePlayer.view.ProgressSelector.buildSaveWindow().
void gamePlayer.view.ProgressSelector.saveProgressEvent (TextField name, GameData saveData) private
Definition at line 130 of file ProgressSelector.java.
References data.DataManager.writeProgressFile().
Referenced by gamePlayer.view.ProgressSelector.buildSaveWindow().
void gamePlayer.view.ProgressSelector.saveProgressState (GameData saveData)
Definition at line 81 of file ProgressSelector.java.
References gamePlayer.view.ProgressSelector.buildSaveWindow(), and gamePlayer.view.ProgressSelector.updateProgressList().
Referenced by gamePlayer.model.PlayerModel.saveGameProgress().
VBox gamePlayer.view.ProgressSelector.setupWindow (String title) private
Definition at line 114 of file ProgressSelector.java.
Referenced by gamePlayer.view.ProgressSelector.buildLoadWindow(), and gamePlayer.view.ProgressSelector.buildSaveWindow().
void gamePlayer.view.ProgressSelector.updateProgressList () private
Definition at line 63 of file ProgressSelector.java.
Referenced by gamePlayer.view.ProgressSelector.loadProgressState(), and gamePlayer.view.ProgressSelector.saveProgressState().
Member Data Documentation
DataManager gamePlayer.view.ProgressSelector.myDataManager package
Definition at line 37 of file ProgressSelector.java.
File gamePlayer.view.ProgressSelector.myGameLocation package
Definition at line 35 of file ProgressSelector.java.
StringProperty gamePlayer.view.ProgressSelector.myProgressFileName package
Definition at line 38 of file ProgressSelector.java.
File gamePlayer.view.ProgressSelector.myProgressFolder package
Definition at line 36 of file ProgressSelector.java.
ObservableList<String> gamePlayer.view.ProgressSelector.myProgressList package
Definition at line 32 of file ProgressSelector.java.
Referenced by gamePlayer.view.ProgressSelector.ProgressSelector().
ListView<String> gamePlayer.view.ProgressSelector.myProgressListView package
Definition at line 33 of file ProgressSelector.java.
Stage gamePlayer.view.ProgressSelector.myProgressStage package
Definition at line 39 of file ProgressSelector.java.
String gamePlayer.view.ProgressSelector.selectedProgressState package
Definition at line 34 of file ProgressSelector.java.
final int gamePlayer.view.ProgressSelector.TEXT_COLUMN_COUNT = 20 static private
Definition at line 31 of file ProgressSelector.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/voogasalad_BitsPlease/repository/src/gamePlayer/view/ProgressSelector.java