voogasalad_BitsPlease: authoring.view.conditionsview.ConditionsAccordionView Class Reference
authoring.view.conditionsview.ConditionsAccordionView Class Reference
Public Member Functions
ConditionsAccordionView (ResourceBundle language, double width, double height)
void update (Observable o, Object arg)
void setIconEvents (GameHandler...gameHandlers)
void addCondition (ConditionsCollection conditions, GameHandler...gameHandlers)
Public Member Functions inherited from authoring.view.baseclasses.CollectionView
CollectionView (ResourceBundle language, double width, double height)
void setIconEvents (GameHandler...gameHandlers)
Private Attributes
VBox myVbox = new VBox()
GameHandler[] myEvents
GameHandler[] levelEvents
String myName
Static Private Attributes
static final double VIEW_HEIGHT_RATIO = .65
static final double VIEW_WIDTH_RATIO = 0.2
Additional Inherited Members
Protected Member Functions inherited from authoring.view.baseclasses.CollectionView
void setView (double width, double height)
Protected Attributes inherited from authoring.view.baseclasses.CollectionView
ResourceBundle myLanguage
double myHeight
double myWidth
GameHandler[] myIconEvents
Detailed Description
Definition at line 14 of file ConditionsAccordionView.java.
Constructor & Destructor Documentation
authoring.view.conditionsview.ConditionsAccordionView.ConditionsAccordionView (ResourceBundle language, double width, double height)
Definition at line 22 of file ConditionsAccordionView.java.
References authoring.view.baseclasses.CollectionView.setView().
Member Function Documentation
void authoring.view.conditionsview.ConditionsAccordionView.addCondition (ConditionsCollection conditions, GameHandler... gameHandlers)
Definition at line 38 of file ConditionsAccordionView.java.
Referenced by authoring.view.conditionsview.ConditionsAccordionView.update().
void authoring.view.conditionsview.ConditionsAccordionView.setIconEvents (GameHandler... gameHandlers)
Definition at line 34 of file ConditionsAccordionView.java.
Referenced by authoring.controller.AuthoringController.initializeGameHandlers().
void authoring.view.conditionsview.ConditionsAccordionView.update (Observable o, Object arg)
This method is called whenever the observed object is changed. An application calls an Observable object's notifyObservers method to have all the object's observers notified of the change.
Parameters
o the observable object.
arg an argument passed to the notifyObservers method.
Implements data.Observer.
Definition at line 30 of file ConditionsAccordionView.java.
References authoring.view.conditionsview.ConditionsAccordionView.addCondition().
Member Data Documentation
GameHandler [] authoring.view.conditionsview.ConditionsAccordionView.levelEvents private
Definition at line 19 of file ConditionsAccordionView.java.
GameHandler [] authoring.view.conditionsview.ConditionsAccordionView.myEvents private
Definition at line 18 of file ConditionsAccordionView.java.
String authoring.view.conditionsview.ConditionsAccordionView.myName private
Definition at line 20 of file ConditionsAccordionView.java.
VBox authoring.view.conditionsview.ConditionsAccordionView.myVbox = new VBox() private
Definition at line 17 of file ConditionsAccordionView.java.
final double authoring.view.conditionsview.ConditionsAccordionView.VIEW_HEIGHT_RATIO = .65 static private
Definition at line 15 of file ConditionsAccordionView.java.
final double authoring.view.conditionsview.ConditionsAccordionView.VIEW_WIDTH_RATIO = 0.2 static private
Definition at line 16 of file ConditionsAccordionView.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/voogasalad_BitsPlease/repository/src/authoring/view/conditionsview/ConditionsAccordionView.java