voogasalad_BitsPlease: authoring.view.propertiesview.PropertiesView Class Reference
authoring.view.propertiesview.PropertiesView Class Reference
Public Member Functions
PropertiesView (ResourceBundle language, double width, double height)
void displayProperties (IPropertiesMaker icon)
void displayProperties (GameObject gameObj)
GameObject getCurrentGameObject ()
GameObject getEditedGameObject ()
void setButtonBehaviors (GameHandler...gh)
Public Member Functions inherited from authoring.view.baseclasses.CollectionView
CollectionView (ResourceBundle language, double width, double height)
void setIconEvents (GameHandler...gameHandlers)
Private Attributes
VBox myContents = new VBox()
GameHandler[] myButtonBehaviors
GameObjectProperties myGameObjectsProperties
GameObject myCurrentGameObject
double myWidth
double myHeight
Static Private Attributes
static final double VIEW_HEIGHT_RATIO = .95
static final double VIEW_WIDTH_RATIO = 0.2
Additional Inherited Members
Protected Member Functions inherited from authoring.view.baseclasses.CollectionView
void setView (double width, double height)
Protected Attributes inherited from authoring.view.baseclasses.CollectionView
ResourceBundle myLanguage
double myHeight
double myWidth
GameHandler[] myIconEvents
Detailed Description
Author
Kevin Li
Chris Bernt
Wesley Valentine
Arjun Jain
Definition at line 17 of file PropertiesView.java.
Constructor & Destructor Documentation
authoring.view.propertiesview.PropertiesView.PropertiesView (ResourceBundle language, double width, double height)
Definition at line 31 of file PropertiesView.java.
References authoring.view.baseclasses.CollectionView.setView().
Member Function Documentation
void authoring.view.propertiesview.PropertiesView.displayProperties (IPropertiesMaker icon)
The icon (that must implement IPropertiesMaker) to display properties for.
Parameters
icon
Definition at line 47 of file PropertiesView.java.
References authoring.view.icons.IPropertiesMaker.makeProperties().
Referenced by authoring.eventhandlers.GameObjectClickHandler.handle(), authoring.eventhandlers.IconClickHandler.handle(), authoring.eventhandlers.EditGameObjectHandler.handle(), authoring.eventhandlers.GameObjectDragHandler.handle(), and authoring.eventhandlers.GameObjectDragToLevelHandler.handle().
void authoring.view.propertiesview.PropertiesView.displayProperties (GameObject gameObj)
This method was overloaded since it is being used in several handlers besides the click handler that only have access to a particular game object and not the game object icon. The game object can be taken from the icon, but creating an icon from solely a game object is difficult.
Parameters
gameObj The game object to make properties for.
Definition at line 61 of file PropertiesView.java.
GameObject authoring.view.propertiesview.PropertiesView.getCurrentGameObject ()
Definition at line 69 of file PropertiesView.java.
References authoring.view.propertiesview.PropertiesView.myCurrentGameObject.
Referenced by authoring.eventhandlers.DeleteGameObjectHandler.handle(), and authoring.eventhandlers.EditGameObjectHandler.handle().
GameObject authoring.view.propertiesview.PropertiesView.getEditedGameObject ()
Definition at line 73 of file PropertiesView.java.
References authoring.view.propertiesview.GameObjectProperties.edit().
Referenced by authoring.eventhandlers.EditGameObjectHandler.handle(), and authoring.eventhandlers.SaveAsNewHandler.handle().
void authoring.view.propertiesview.PropertiesView.setButtonBehaviors (GameHandler... gh)
Definition at line 77 of file PropertiesView.java.
Referenced by authoring.controller.AuthoringController.initializeGameHandlers().
Member Data Documentation
GameHandler [] authoring.view.propertiesview.PropertiesView.myButtonBehaviors private
Definition at line 23 of file PropertiesView.java.
VBox authoring.view.propertiesview.PropertiesView.myContents = new VBox() private
Definition at line 21 of file PropertiesView.java.
GameObject authoring.view.propertiesview.PropertiesView.myCurrentGameObject private
Definition at line 26 of file PropertiesView.java.
Referenced by authoring.view.propertiesview.PropertiesView.getCurrentGameObject().
GameObjectProperties authoring.view.propertiesview.PropertiesView.myGameObjectsProperties private
Definition at line 25 of file PropertiesView.java.
double authoring.view.propertiesview.PropertiesView.myHeight private
Definition at line 29 of file PropertiesView.java.
double authoring.view.propertiesview.PropertiesView.myWidth private
Definition at line 28 of file PropertiesView.java.
final double authoring.view.propertiesview.PropertiesView.VIEW_HEIGHT_RATIO = .95 static private
Definition at line 19 of file PropertiesView.java.
final double authoring.view.propertiesview.PropertiesView.VIEW_WIDTH_RATIO = 0.2 static private
Definition at line 20 of file PropertiesView.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/voogasalad_BitsPlease/repository/src/authoring/view/propertiesview/PropertiesView.java