voogasalad_BitsPlease: authoring.view.graphicsview.ImagesView Class Reference
authoring.view.graphicsview.ImagesView Class Reference
Public Member Functions
ImagesView (ResourceBundle language, double width, double height, File gameLoc)
void update (Observable o, Object arg)
void setDragOver (GameHandler handler)
void setDragDrop (GameHandler handler)
void addImage (String s)
Public Member Functions inherited from authoring.view.baseclasses.CollectionView
CollectionView (ResourceBundle language, double width, double height)
void setIconEvents (GameHandler...gameHandlers)
Private Attributes
VBox myVbox = new VBox()
File myGameLocation
Static Private Attributes
static final double VIEW_HEIGHT_RATIO = .65
static final double VIEW_WIDTH_RATIO = 0.2
Additional Inherited Members
Protected Member Functions inherited from authoring.view.baseclasses.CollectionView
void setView (double width, double height)
Protected Attributes inherited from authoring.view.baseclasses.CollectionView
ResourceBundle myLanguage
double myHeight
double myWidth
GameHandler[] myIconEvents
Detailed Description
View component that corresponds with the backend model component - GraphicsCollection. Updates if any changes occur in Graphics Collection via observer/observable.
Author
Kevin Li
Chris Bernt
Definition at line 23 of file ImagesView.java.
Constructor & Destructor Documentation
authoring.view.graphicsview.ImagesView.ImagesView (ResourceBundle language, double width, double height, File gameLoc)
Definition at line 29 of file ImagesView.java.
References authoring.view.baseclasses.CollectionView.setView().
Member Function Documentation
void authoring.view.graphicsview.ImagesView.addImage (String s)
Definition at line 50 of file ImagesView.java.
References authoring.view.baseclasses.CollectionView.myIconEvents.
Referenced by authoring.view.graphicsview.ImagesView.update().
void authoring.view.graphicsview.ImagesView.setDragDrop (GameHandler handler)
Definition at line 46 of file ImagesView.java.
Referenced by authoring.controller.AuthoringController.initializeGameHandlers().
void authoring.view.graphicsview.ImagesView.setDragOver (GameHandler handler)
Definition at line 42 of file ImagesView.java.
Referenced by authoring.controller.AuthoringController.initializeGameHandlers().
void authoring.view.graphicsview.ImagesView.update (Observable o, Object arg)
This method is called whenever the observed object is changed. An application calls an Observable object's notifyObservers method to have all the object's observers notified of the change.
Parameters
o the observable object.
arg an argument passed to the notifyObservers method.
Implements data.Observer.
Definition at line 38 of file ImagesView.java.
References authoring.view.graphicsview.ImagesView.addImage().
Member Data Documentation
File authoring.view.graphicsview.ImagesView.myGameLocation private
Definition at line 27 of file ImagesView.java.
VBox authoring.view.graphicsview.ImagesView.myVbox = new VBox() private
Definition at line 26 of file ImagesView.java.
final double authoring.view.graphicsview.ImagesView.VIEW_HEIGHT_RATIO = .65 static private
Definition at line 24 of file ImagesView.java.
final double authoring.view.graphicsview.ImagesView.VIEW_WIDTH_RATIO = 0.2 static private
Definition at line 25 of file ImagesView.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/voogasalad_BitsPlease/repository/src/authoring/view/graphicsview/ImagesView.java