voogasalad_BitsPlease: engine.actions.MakeNewRandomObjectAction Class Reference
engine.actions.MakeNewRandomObjectAction Class Reference
Public Member Functions
MakeNewRandomObjectAction (String type, Double lowerXBound, Double upperXBound, Double lowerYBound, Double upperYBound)
void execute ()
void makeRandomObject (GameObject object)
Public Member Functions inherited from engine.actions.MakeNewObjectAction
MakeNewObjectAction (String type)
void initialize (GameManager manager)
Protected Attributes
Double myLowerXBound
Double myUpperXBound
Double myLowerYBound
Double myUpperYBound
Protected Attributes inherited from engine.actions.MakeNewObjectAction
transient Level myCurrentLevel
transient GameObjectsCollection myMasterList
transient GameObjectRenderer myRenderer
String myType
transient Random r
Detailed Description
Definition at line 9 of file MakeNewRandomObjectAction.java.
Constructor & Destructor Documentation
engine.actions.MakeNewRandomObjectAction.MakeNewRandomObjectAction (String type, Double lowerXBound, Double upperXBound, Double lowerYBound, Double upperYBound)
Definition at line 16 of file MakeNewRandomObjectAction.java.
Member Function Documentation
void engine.actions.MakeNewRandomObjectAction.execute ()
Will execute the consequences resulting from applying an Action.
Parameters
action
Implements engine.actions.Action.
Definition at line 28 of file MakeNewRandomObjectAction.java.
References engine.actions.MakeNewRandomObjectAction.makeRandomObject(), engine.actions.MakeNewObjectAction.myMasterList, and engine.actions.MakeNewObjectAction.myType.
void engine.actions.MakeNewRandomObjectAction.makeRandomObject (GameObject object)
Definition at line 39 of file MakeNewRandomObjectAction.java.
References authoring.model.collections.GeneralCollection< T >.add(), engine.render.GameObjectRenderer.createAndAssignRenderedNode(), engine.level.Level.getGameObjectsCollection(), engine.actions.MakeNewObjectAction.myCurrentLevel, engine.actions.MakeNewRandomObjectAction.myLowerXBound, engine.actions.MakeNewRandomObjectAction.myLowerYBound, engine.actions.MakeNewObjectAction.myRenderer, engine.actions.MakeNewObjectAction.myType, engine.actions.MakeNewObjectAction.r, engine.gameObject.GameObject.setIdentifier(), and engine.gameObject.GameObject.setPhysicsBody().
Referenced by engine.actions.MakeNewRandomObjectAction.execute().
Member Data Documentation
Double engine.actions.MakeNewRandomObjectAction.myLowerXBound protected
Definition at line 11 of file MakeNewRandomObjectAction.java.
Referenced by engine.actions.MakeNewRandomObjectAction.makeRandomObject().
Double engine.actions.MakeNewRandomObjectAction.myLowerYBound protected
Definition at line 13 of file MakeNewRandomObjectAction.java.
Referenced by engine.actions.MakeNewRandomObjectAction.makeRandomObject().
Double engine.actions.MakeNewRandomObjectAction.myUpperXBound protected
Definition at line 12 of file MakeNewRandomObjectAction.java.
Double engine.actions.MakeNewRandomObjectAction.myUpperYBound protected
Definition at line 14 of file MakeNewRandomObjectAction.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/voogasalad_BitsPlease/repository/src/engine/actions/MakeNewRandomObjectAction.java