voogasalad_BitsPlease: authoring.view.levelview.LevelsView Class Reference
authoring.view.levelview.LevelsView Class Reference
Public Member Functions
LevelsView (ResourceBundle language, double width, double height, File gameLoc)
void update (Observable o, Object arg)
SingleLevelView getCurrentLevel ()
void moveSpriteOnLevel (ImageBasedIcon g, double x, double y)
SingleLevelView addNewLevel (String myLevelID, String bgImage)
SingleLevelView addExistingLevel (Level l, GameHandler...events)
boolean levelOpenInTabs (String id)
void setEventHandlers (GameHandler...handlers)
Public Member Functions inherited from authoring.view.baseclasses.TabView
TabView (ResourceBundle language, double width, double height)
Private Attributes
File myGameLocation
GameHandler[] myEvents
Static Private Attributes
static final double VIEW_HEIGHT_RATIO = .87
static final double VIEW_WIDTH_RATIO = 0.6
Additional Inherited Members
Protected Member Functions inherited from authoring.view.baseclasses.TabView
void setView (double width, double height)
Protected Attributes inherited from authoring.view.baseclasses.TabView
ResourceBundle myLanguage
double myHeight
double myWidth
Detailed Description
View class that contains all the levels in the program. Corresponds with backend model data - LevelsCollection. Updates if any changes occur via observer/observable.
Author
Kevin Li
Wesley Valentine
Definition at line 23 of file LevelsView.java.
Constructor & Destructor Documentation
authoring.view.levelview.LevelsView.LevelsView (ResourceBundle language, double width, double height, File gameLoc)
Definition at line 29 of file LevelsView.java.
Member Function Documentation
SingleLevelView authoring.view.levelview.LevelsView.addExistingLevel (Level l, GameHandler... events)
THIS IS REPEATED CODE WE NEED TO FIX
Parameters
l
Returns
Definition at line 100 of file LevelsView.java.
References engine.level.Level.getIdentifier(), engine.gameObject.Identifier.getUniqueId(), authoring.view.baseclasses.TabView.myHeight, and authoring.view.baseclasses.TabView.myWidth.
Referenced by authoring.eventhandlers.LevelToViewHandler.handle().
SingleLevelView authoring.view.levelview.LevelsView.addNewLevel (String myLevelID, String bgImage)
Definition at line 84 of file LevelsView.java.
References authoring.view.baseclasses.TabView.myHeight, and authoring.view.baseclasses.TabView.myWidth.
Referenced by authoring.eventhandlers.AddLevelHandler.createLevel().
SingleLevelView authoring.view.levelview.LevelsView.getCurrentLevel ()
Creates a copy of a passed in Graphic and adds it to the current level. Passes in Event Handler to the Graphic, handling drag events.
Parameters
graphic
x
y
handler
Definition at line 67 of file LevelsView.java.
Referenced by authoring.eventhandlers.DeleteGameObjectHandler.handle(), authoring.eventhandlers.EditGameObjectHandler.handle(), authoring.eventhandlers.GameObjGraphicDragHandler.handle(), authoring.eventhandlers.GameObjectDragHandler.handle(), and authoring.eventhandlers.GameObjectDragToLevelHandler.handle().
boolean authoring.view.levelview.LevelsView.levelOpenInTabs (String id)
Definition at line 111 of file LevelsView.java.
Referenced by authoring.eventhandlers.LevelToViewHandler.handle().
void authoring.view.levelview.LevelsView.moveSpriteOnLevel (ImageBasedIcon g, double x, double y)
Moves Sprite to new location on level view.
Parameters
g
x
y
Definition at line 79 of file LevelsView.java.
void authoring.view.levelview.LevelsView.setEventHandlers (GameHandler... handlers)
Definition at line 122 of file LevelsView.java.
Referenced by authoring.controller.AuthoringController.initializeGameHandlers().
void authoring.view.levelview.LevelsView.update (Observable o, Object arg)
This method is called whenever the observed object is changed. An application calls an Observable object's notifyObservers method to have all the object's observers notified of the change.
Parameters
o the observable object.
arg an argument passed to the notifyObservers method.
Implements data.Observer.
Definition at line 37 of file LevelsView.java.
Member Data Documentation
GameHandler [] authoring.view.levelview.LevelsView.myEvents private
Definition at line 27 of file LevelsView.java.
File authoring.view.levelview.LevelsView.myGameLocation private
Definition at line 26 of file LevelsView.java.
final double authoring.view.levelview.LevelsView.VIEW_HEIGHT_RATIO = .87 static private
Definition at line 24 of file LevelsView.java.
final double authoring.view.levelview.LevelsView.VIEW_WIDTH_RATIO = 0.6 static private
Definition at line 25 of file LevelsView.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/voogasalad_BitsPlease/repository/src/authoring/view/levelview/LevelsView.java