voogasalad_BitsPlease: engine.conditions.BoundaryConditionY Class Reference
engine.conditions.BoundaryConditionY Class Reference
Public Member Functions
BoundaryConditionY (List< Action > myActions, List< Identifier > myIDs, Double boundary, Boolean upTrigger)
void respondToFrameElapsed ()
Public Member Functions inherited from engine.conditions.GameObjectCondition
GameObjectCondition (List< Action > myActions, List< Identifier > myIDs)
void initialize (GameManager gameManager)
void setGameObjects (GameObjectsCollection gameObjects)
void addGameObject (GameObject object)
boolean removeGameObject (String objectId)
GameObjectsCollection getGameObjects ()
Public Member Functions inherited from engine.conditions.Condition
Condition (List< Action > actions)
List< Action > getActions ()
void setEnabled (Boolean enabled)
boolean isEnabled ()
void setInputMap (Map< String, String > inputs)
Map< String, String > getInputMap ()
void frameElapsed ()
void setIdentifier (Identifier myId)
Identifier getIdentifier ()
void initialize (GameManager manager)
void addAction (Action a)
Protected Member Functions
void executeActions ()
Protected Member Functions inherited from engine.conditions.Condition
abstract void executeActions ()
abstract void respondToFrameElapsed ()
void initializeActions (GameManager manager)
GameManager getGameManager ()
Private Attributes
Double myBoundary
Boolean myUpTrigger
Additional Inherited Members
Protected Attributes inherited from engine.conditions.GameObjectCondition
GameObjectsCollection myGameObjects
List< Identifier > myGameObjectIDs
Protected Attributes inherited from engine.conditions.Condition
List< Action > myActions = new ArrayList<Action>()
transient GameManager myGameManager
Identifier myId
Detailed Description
Definition at line 10 of file BoundaryConditionY.java.
Constructor & Destructor Documentation
engine.conditions.BoundaryConditionY.BoundaryConditionY (List< Action > myActions, List< Identifier > myIDs, Double boundary, Boolean upTrigger)
Definition at line 15 of file BoundaryConditionY.java.
Member Function Documentation
void engine.conditions.BoundaryConditionY.executeActions () protected
Definition at line 24 of file BoundaryConditionY.java.
References engine.conditions.Condition.getActions().
Referenced by engine.conditions.BoundaryConditionY.respondToFrameElapsed().
void engine.conditions.BoundaryConditionY.respondToFrameElapsed ()
Definition at line 31 of file BoundaryConditionY.java.
References engine.conditions.BoundaryConditionY.executeActions(), engine.conditions.GameObjectCondition.getGameObjects(), and engine.conditions.BoundaryConditionY.myBoundary.
Member Data Documentation
Double engine.conditions.BoundaryConditionY.myBoundary private
Definition at line 12 of file BoundaryConditionY.java.
Referenced by engine.conditions.BoundaryConditionY.respondToFrameElapsed().
Boolean engine.conditions.BoundaryConditionY.myUpTrigger private
Definition at line 13 of file BoundaryConditionY.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/voogasalad_BitsPlease/repository/src/engine/conditions/BoundaryConditionY.java