voogasalad_BitsPlease: engine.level.Level Class Reference
engine.level.Level Class Reference
Public Member Functions
Level (List< Identifier > IdList)
Level (GameObjectsCollection gameObjects)
Level (List< Identifier > objectIdList, List< Identifier > conditionIdList, boolean isStart)
Level (GameObjectsCollection gameObjects, boolean isStart)
void resetLevel ()
void update ()
Iterator< GameObject > getGameObjectIterator ()
void addGameObject (GameObject gameObject)
void addInitialGameObjects (GameObject gameObject)
boolean removeGameObject (GameObject g)
GameObjectsCollection getGameObjectsCollection ()
void setIdentifier (Identifier myId)
Identifier getIdentifier ()
void initialize (LevelManager manager)
List< Identifier > getConditionIdentifiers ()
Iterator< Identifier > getConditionIds ()
List< Identifier > getConditionCollection ()
void setGameObjectIds (List< Identifier > iDList)
void setConditionIds (List< Identifier > iDList)
void setStartIndicator (boolean indicator)
boolean isStartLevel ()
List< Identifier > getGameObjectIDs ()
void setBackgroundImage (String s)
void setBackgroundMusic (String s)
String getBackgroundImage ()
String getBackgroundMusic ()
void setWidth (int i)
void setHeight (int i)
int getHeight ()
int getWidth ()
Public Member Functions inherited from data.Observable
Observable ()
synchronized void addObserver (Observer o)
synchronized void deleteObserver (Observer o)
void notifyObservers ()
void notifyObservers (Object arg)
synchronized void deleteObservers ()
synchronized boolean hasChanged ()
synchronized int countObservers ()
Private Attributes
Identifier myId
String myBackgroundImage
String myBackgroundMusic
int myWidth
int myHeight
GameObjectsCollection myDefaultGameObjects
GameObjectsCollection myWorkingGameObjects
List< Identifier > myGameObjectIdList
List< Identifier > myConditionIdList
boolean myStartLevelIndicator
Additional Inherited Members
Protected Member Functions inherited from data.Observable
synchronized void setChanged ()
synchronized void clearChanged ()
Detailed Description
A Level of the game. Contains all GameObjects and Actions and coordinates their interactions for linear progression through the game.
Author
Will Chang
Abhishek Balakrishnan
Definition at line 20 of file Level.java.
Constructor & Destructor Documentation
engine.level.Level.Level (List< Identifier > IdList)
Constructor
Parameters
IdList list representing game objects that apply to this level
Definition at line 39 of file Level.java.
engine.level.Level.Level (GameObjectsCollection gameObjects)
Definition at line 45 of file Level.java.
engine.level.Level.Level (List< Identifier > objectIdList, List< Identifier > conditionIdList, boolean isStart)
Definition at line 50 of file Level.java.
engine.level.Level.Level (GameObjectsCollection gameObjects, boolean isStart)
Definition at line 58 of file Level.java.
Member Function Documentation
void engine.level.Level.addGameObject (GameObject gameObject)
Definition at line 89 of file Level.java.
References authoring.model.collections.GeneralCollection< T >.add(), data.Observable.notifyObservers(), and data.Observable.setChanged().
Referenced by authoring.eventhandlers.GameObjectDragToLevelHandler.updateName().
void engine.level.Level.addInitialGameObjects (GameObject gameObject)
Definition at line 95 of file Level.java.
References authoring.model.collections.GeneralCollection< T >.add().
String engine.level.Level.getBackgroundImage ()
Definition at line 170 of file Level.java.
References engine.level.Level.myBackgroundImage.
Referenced by authoring.view.propertiesview.LevelProperties.initializeProperties(), engine.render.GameObjectRenderer.setBackGroundImage(), and authoring.view.levelview.SingleLevelView.SingleLevelView().
String engine.level.Level.getBackgroundMusic ()
Definition at line 174 of file Level.java.
References engine.level.Level.myBackgroundMusic.
Referenced by engine.level.LevelManager.initializeCurrentLevel(), and authoring.view.propertiesview.LevelProperties.initializeProperties().
List<Identifier> engine.level.Level.getConditionCollection ()
Definition at line 138 of file Level.java.
References engine.level.Level.myConditionIdList.
Referenced by authoring.eventhandlers.AddConditionIDHandler.addNewCondition().
List<Identifier> engine.level.Level.getConditionIdentifiers ()
Definition at line 130 of file Level.java.
References engine.level.Level.myConditionIdList.
Referenced by authoring.eventhandlers.DeleteConditionFromLevelHandler.deleteCondition(), authoring.view.propertiesview.LevelProperties.initializeProperties(), and engine.level.LevelManager.setLevelEnabledConditions().
Iterator<Identifier> engine.level.Level.getConditionIds ()
Definition at line 134 of file Level.java.
List<Identifier> engine.level.Level.getGameObjectIDs ()
Definition at line 158 of file Level.java.
References engine.level.Level.myGameObjectIdList.
Iterator<GameObject> engine.level.Level.getGameObjectIterator ()
Returns
Iterator for GameObjectCollection
Definition at line 85 of file Level.java.
References authoring.model.collections.GeneralCollection< T >.iterator().
Referenced by engine.render.GameObjectRenderer.renderGameObjects().
GameObjectsCollection engine.level.Level.getGameObjectsCollection ()
Definition at line 106 of file Level.java.
References engine.level.Level.myWorkingGameObjects.
Referenced by engine.actions.TranslateYType.execute(), engine.actions.render.ChangeImageTypeAction.execute(), engine.actions.MakeNewObjectFromLocationAction.execute(), engine.actions.VelocityTypeAction.execute(), engine.actions.MakeNewObjectFromObjectAction.execute(), engine.actions.DeleteTypeAction.execute(), engine.actions.TranslateTypeAction.initialize(), engine.actions.PhysicsTypeAction.initialize(), engine.conditions.TypeCollisionCondition.initialize(), engine.actions.MakeNewRandomObjectAction.makeRandomObject(), and authoring.view.levelview.SingleLevelView.recreateLevel().
int engine.level.Level.getHeight ()
Definition at line 184 of file Level.java.
References engine.level.Level.myHeight.
Referenced by authoring.view.levelview.LevelsView.addExistingLevel().
Identifier engine.level.Level.getIdentifier ()
Implements engine.gameObject.Identifiable.
Definition at line 116 of file Level.java.
References engine.level.Level.myId.
Referenced by authoring.view.levelview.LevelsView.addExistingLevel(), and authoring.eventhandlers.LevelToViewHandler.handle().
int engine.level.Level.getWidth ()
Definition at line 187 of file Level.java.
References engine.level.Level.myWidth.
Referenced by authoring.view.levelview.LevelsView.addExistingLevel().
void engine.level.Level.initialize (LevelManager manager)
Definition at line 120 of file Level.java.
References authoring.model.collections.GeneralCollection< T >.add(), engine.gameObject.GameObject.getIdentifier(), engine.gameObject.Identifier.getUniqueId(), and engine.level.LevelManager.objectForIdentifier().
Referenced by engine.level.LevelManager.initializeCurrentLevel(), and engine.level.LevelManager.setCurrentLevel().
boolean engine.level.Level.isStartLevel ()
Definition at line 154 of file Level.java.
References engine.level.Level.myStartLevelIndicator.
Referenced by authoring.view.propertiesview.LevelProperties.initializeProperties().
boolean engine.level.Level.removeGameObject (GameObject g)
Definition at line 99 of file Level.java.
References data.Observable.notifyObservers(), authoring.model.collections.GeneralCollection< T >.remove(), and data.Observable.setChanged().
void engine.level.Level.resetLevel ()
Reset method for the GameObjects
Definition at line 69 of file Level.java.
Referenced by engine.actions.ResetLevelAction.execute().
void engine.level.Level.setBackgroundImage (String s)
Definition at line 162 of file Level.java.
Referenced by authoring.model.AuthoringModel.convertFromSerializable(), authoring.model.AuthoringModel.convertToSerializable(), engine.tests.MainEngineTests.createGameObject(), games.MarioGameTest.createGameObject(), and authoring.eventhandlers.AddLevelHandler.createLevel().
void engine.level.Level.setBackgroundMusic (String s)
Definition at line 166 of file Level.java.
Referenced by authoring.model.AuthoringModel.convertFromSerializable(), authoring.model.AuthoringModel.convertToSerializable(), engine.tests.MainEngineTests.createGameObject(), games.MarioGameTest.createGameObject(), and authoring.eventhandlers.AddLevelHandler.createLevel().
void engine.level.Level.setConditionIds (List< Identifier > iDList)
Definition at line 146 of file Level.java.
Referenced by authoring.model.AuthoringModel.convertFromSerializable(), and authoring.model.AuthoringModel.convertToSerializable().
void engine.level.Level.setGameObjectIds (List< Identifier > iDList)
Definition at line 142 of file Level.java.
void engine.level.Level.setHeight (int i)
Definition at line 181 of file Level.java.
Referenced by authoring.model.AuthoringModel.convertFromSerializable(), authoring.model.AuthoringModel.convertToSerializable(), and authoring.eventhandlers.AddLevelHandler.createLevel().
void engine.level.Level.setIdentifier (Identifier myId)
Implements engine.gameObject.Identifiable.
Definition at line 111 of file Level.java.
References engine.level.Level.myId.
Referenced by authoring.model.AuthoringModel.convertFromSerializable(), authoring.model.AuthoringModel.convertToSerializable(), engine.tests.MainEngineTests.createGameObject(), games.MarioGameTest.createGameObject(), and authoring.eventhandlers.AddLevelHandler.createLevel().
void engine.level.Level.setStartIndicator (boolean indicator)
Definition at line 150 of file Level.java.
Referenced by authoring.model.AuthoringModel.convertFromSerializable(), and authoring.model.AuthoringModel.convertToSerializable().
void engine.level.Level.setWidth (int i)
Definition at line 178 of file Level.java.
Referenced by authoring.model.AuthoringModel.convertFromSerializable(), authoring.model.AuthoringModel.convertToSerializable(), and authoring.eventhandlers.AddLevelHandler.createLevel().
void engine.level.Level.update ()
Updates all GameObjects.
Definition at line 76 of file Level.java.
Referenced by engine.level.LevelManager.update().
Member Data Documentation
String engine.level.Level.myBackgroundImage private
Definition at line 23 of file Level.java.
Referenced by engine.level.Level.getBackgroundImage().
String engine.level.Level.myBackgroundMusic private
Definition at line 24 of file Level.java.
Referenced by engine.level.Level.getBackgroundMusic().
List<Identifier> engine.level.Level.myConditionIdList private
Definition at line 30 of file Level.java.
Referenced by engine.level.Level.getConditionCollection(), and engine.level.Level.getConditionIdentifiers().
GameObjectsCollection engine.level.Level.myDefaultGameObjects private
Definition at line 27 of file Level.java.
List<Identifier> engine.level.Level.myGameObjectIdList private
Definition at line 29 of file Level.java.
Referenced by engine.level.Level.getGameObjectIDs().
int engine.level.Level.myHeight private
Definition at line 26 of file Level.java.
Referenced by engine.level.Level.getHeight().
Identifier engine.level.Level.myId private
Definition at line 22 of file Level.java.
Referenced by engine.level.Level.getIdentifier(), and engine.level.Level.setIdentifier().
boolean engine.level.Level.myStartLevelIndicator private
Definition at line 31 of file Level.java.
Referenced by engine.level.Level.isStartLevel().
int engine.level.Level.myWidth private
Definition at line 25 of file Level.java.
Referenced by engine.level.Level.getWidth().
GameObjectsCollection engine.level.Level.myWorkingGameObjects private
Definition at line 28 of file Level.java.
Referenced by engine.level.Level.getGameObjectsCollection().
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/voogasalad_BitsPlease/repository/src/engine/level/Level.java