voogasalad_BitsPlease: engine.sound.SoundUtility Class Reference
engine.sound.SoundUtility Class Reference
Public Member Functions
SoundUtility (LevelsCollection levels, String relativePath)
void initializeMusic ()
void setVolume (String musicPath, double value)
void playBackGroundMusic (String musicPath)
void addBackGroundMusic (String musicPath)
void playAudioClip (String audioClipPath)
void addAudioClip (String audioClipPath)
void stopBackGroundMusic (String musicPath)
void pauseBackGroundMusic (String musicPath)
void removeBackGroundMusic (String title)
void removeAudioClip (String title)
Private Member Functions
MediaPlayer makeMediaPlayer (String musicPath)
AudioClip makeAudioClip (String audioClipPath)
Private Attributes
Map< String, MediaPlayer > myMediaPlayerMap
Map< String, AudioClip > myAudioClipMap
LevelsCollection myLevels
FilePathUtility myFilePathUtility
final String SOUNDS = "sounds"
Detailed Description
Plays sounds using composition JavaFX elements in Game
Author
Will Chang
Definition at line 19 of file SoundUtility.java.
Constructor & Destructor Documentation
engine.sound.SoundUtility.SoundUtility (LevelsCollection levels, String relativePath)
Definition at line 27 of file SoundUtility.java.
References engine.sound.SoundUtility.initializeMusic().
Member Function Documentation
void engine.sound.SoundUtility.addAudioClip (String audioClipPath)
Definition at line 70 of file SoundUtility.java.
References engine.sound.SoundUtility.makeAudioClip().
Referenced by engine.actions.AudioClipAction.initialize().
void engine.sound.SoundUtility.addBackGroundMusic (String musicPath)
Definition at line 53 of file SoundUtility.java.
References engine.sound.SoundUtility.makeMediaPlayer().
Referenced by engine.sound.SoundUtility.initializeMusic().
void engine.sound.SoundUtility.initializeMusic ()
Definition at line 35 of file SoundUtility.java.
References engine.sound.SoundUtility.addBackGroundMusic().
Referenced by engine.sound.SoundUtility.SoundUtility().
AudioClip engine.sound.SoundUtility.makeAudioClip (String audioClipPath) private
Definition at line 74 of file SoundUtility.java.
References engine.FilePathUtility.getFilePath().
Referenced by engine.sound.SoundUtility.addAudioClip().
MediaPlayer engine.sound.SoundUtility.makeMediaPlayer (String musicPath) private
Definition at line 58 of file SoundUtility.java.
References engine.FilePathUtility.getFilePath().
Referenced by engine.sound.SoundUtility.addBackGroundMusic().
void engine.sound.SoundUtility.pauseBackGroundMusic (String musicPath)
Definition at line 85 of file SoundUtility.java.
Referenced by engine.actions.PauseBackgroundMusic.execute().
void engine.sound.SoundUtility.playAudioClip (String audioClipPath)
Definition at line 66 of file SoundUtility.java.
Referenced by engine.actions.PlayAudioClipAction.execute().
void engine.sound.SoundUtility.playBackGroundMusic (String musicPath)
Definition at line 47 of file SoundUtility.java.
Referenced by engine.actions.PlayBackgroundMusic.execute(), and engine.level.LevelManager.initializeCurrentLevel().
void engine.sound.SoundUtility.removeAudioClip (String title)
Definition at line 95 of file SoundUtility.java.
void engine.sound.SoundUtility.removeBackGroundMusic (String title)
Definition at line 91 of file SoundUtility.java.
void engine.sound.SoundUtility.setVolume (String musicPath, double value)
Definition at line 43 of file SoundUtility.java.
Referenced by engine.actions.SetMusicVolume.execute().
void engine.sound.SoundUtility.stopBackGroundMusic (String musicPath)
Definition at line 79 of file SoundUtility.java.
Referenced by engine.actions.StopBackgroundMusic.execute(), and engine.level.LevelManager.initializeCurrentLevel().
Member Data Documentation
Map<String,AudioClip> engine.sound.SoundUtility.myAudioClipMap private
Definition at line 22 of file SoundUtility.java.
FilePathUtility engine.sound.SoundUtility.myFilePathUtility private
Definition at line 24 of file SoundUtility.java.
LevelsCollection engine.sound.SoundUtility.myLevels private
Definition at line 23 of file SoundUtility.java.
Map<String,MediaPlayer> engine.sound.SoundUtility.myMediaPlayerMap private
Definition at line 21 of file SoundUtility.java.
final String engine.sound.SoundUtility.SOUNDS = "sounds" private
Definition at line 25 of file SoundUtility.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/voogasalad_BitsPlease/repository/src/engine/sound/SoundUtility.java