voogasalad_BitsPlease: engine.gameObject.components.PhysicsBody Class Reference
engine.gameObject.components.PhysicsBody Class Reference
Public Member Functions
PhysicsBody ()
PhysicsBody (double collisionBodyHeight, double collisionBodyWidth)
PhysicsBody (PhysicsBody body)
void setVelocity (Vector v)
void setAcceleration (Vector v)
Vector getVelocity ()
Vector getAcceleration ()
double getCollisionBodyHeight ()
double getCollisionBodyWidth ()
Scalar getScalar (String s)
void updatePhysicalCharacteristics (GameObject sprite)
Force getForce (String s)
void addForce (Force vector)
void addImpulse (Vector i)
void addScalar (Scalar a)
void reverseVelocity (boolean xAxis)
void handleCollision (GameObject thisSprite, GameObject sprite)
Private Member Functions
void initializeMap ()
void changeAcceleration ()
void changeVelocity ()
void doImpulses ()
void balanceForces ()
double collisionHelper (double centerOne, double centerTwo, double measureOne, double measureTwo)
Private Attributes
List< Impulse > myImpulses
Vector myAcceleration
Vector myVelocity
boolean haveForcesChanged
Vector myBalancedForcesMag
Map< String, Force > myActiveForces
Map< String, Scalar > myConstants
double myCollisionBodyWidth
double myCollisionBodyHeight
Static Private Attributes
static final double FRAMES_PER_SECOND = 60.0
Detailed Description
Author
Ben Reisner
ArihantJain
    This class holds Physical Information for a GameObject.
Definition at line 36 of file PhysicsBody.java.
Constructor & Destructor Documentation
engine.gameObject.components.PhysicsBody.PhysicsBody ()
Definition at line 48 of file PhysicsBody.java.
engine.gameObject.components.PhysicsBody.PhysicsBody (double collisionBodyHeight, double collisionBodyWidth)
Definition at line 52 of file PhysicsBody.java.
References engine.gameObject.components.PhysicsBody.balanceForces(), and engine.gameObject.components.PhysicsBody.initializeMap().
engine.gameObject.components.PhysicsBody.PhysicsBody (PhysicsBody body)
Definition at line 65 of file PhysicsBody.java.
References engine.gameObject.components.PhysicsBody.getCollisionBodyHeight(), and engine.gameObject.components.PhysicsBody.getCollisionBodyWidth().
Member Function Documentation
void engine.gameObject.components.PhysicsBody.addForce (Force vector)
Definition at line 230 of file PhysicsBody.java.
References engine.physics.Force.addOrChangeValue(), engine.gameObject.components.PhysicsBody.balanceForces(), engine.physics.Force.iterator(), and engine.physics.PhysicsComponent.toString().
Referenced by engine.tests.MainEngineTests.createGameObject(), games.MarioGameTest.createGameObject(), and engine.tests.PhysicsBodyTesting.main().
void engine.gameObject.components.PhysicsBody.addImpulse (Vector i)
Definition at line 240 of file PhysicsBody.java.
void engine.gameObject.components.PhysicsBody.addScalar (Scalar a)
Definition at line 244 of file PhysicsBody.java.
References engine.gameObject.components.PhysicsBody.balanceForces(), engine.physics.Scalar.iterator(), and engine.physics.PhysicsComponent.toString().
Referenced by engine.tests.MainEngineTests.createGameObject(), games.MarioGameTest.createGameObject(), authoring.view.propertiesview.GameObjectProperties.edit(), and engine.tests.PhysicsBodyTesting.main().
void engine.gameObject.components.PhysicsBody.balanceForces () private
balances forces-gives a vector of what the forces in each direction are, sets haveForcesChanged to false because this is called only when in the frame force are changed
Definition at line 219 of file PhysicsBody.java.
References engine.physics.Vector.setX(), and engine.physics.Vector.setY().
Referenced by engine.gameObject.components.PhysicsBody.addForce(), engine.gameObject.components.PhysicsBody.addScalar(), engine.gameObject.components.PhysicsBody.PhysicsBody(), and engine.gameObject.components.PhysicsBody.updatePhysicalCharacteristics().
void engine.gameObject.components.PhysicsBody.changeAcceleration () private
makes a new acceleration vector based on the magnitude of the forces and the mass
Definition at line 126 of file PhysicsBody.java.
References engine.physics.Vector.getX(), and engine.physics.Vector.getY().
Referenced by engine.gameObject.components.PhysicsBody.updatePhysicalCharacteristics().
void engine.gameObject.components.PhysicsBody.changeVelocity () private
changes velocity based on acceleration
Definition at line 135 of file PhysicsBody.java.
References engine.physics.Vector.delta(), engine.gameObject.components.PhysicsBody.FRAMES_PER_SECOND, engine.physics.Vector.getX(), and engine.physics.Vector.getY().
Referenced by engine.gameObject.components.PhysicsBody.updatePhysicalCharacteristics().
double engine.gameObject.components.PhysicsBody.collisionHelper (double centerOne, double centerTwo, double measureOne, double measureTwo) private
Parameters
centerOne -x or y of the first hitbox
centerTwo -x or y of the second hitbox
measureOne -height or width of first hitbox
measureTwo -height or width of second hitbox
Returns
double associated with collisions
Definition at line 347 of file PhysicsBody.java.
Referenced by engine.gameObject.components.PhysicsBody.handleCollision().
void engine.gameObject.components.PhysicsBody.doImpulses () private
goes through impulses, imparts them, clears all of them once they are all done
Definition at line 197 of file PhysicsBody.java.
References engine.physics.Vector.delta().
Referenced by engine.gameObject.components.PhysicsBody.updatePhysicalCharacteristics().
Vector engine.gameObject.components.PhysicsBody.getAcceleration ()
Definition at line 118 of file PhysicsBody.java.
References engine.gameObject.components.PhysicsBody.myAcceleration.
double engine.gameObject.components.PhysicsBody.getCollisionBodyHeight ()
getter for height of hitbox
Returns
height of hitbox
Definition at line 145 of file PhysicsBody.java.
References engine.gameObject.components.PhysicsBody.myCollisionBodyHeight.
Referenced by engine.render.GameObjectRenderer.createCollisionBody(), engine.collision.objects.CollisionComposition.fixedCollision(), engine.gameObject.components.PhysicsBody.handleCollision(), and engine.gameObject.components.PhysicsBody.PhysicsBody().
double engine.gameObject.components.PhysicsBody.getCollisionBodyWidth ()
getter for width of hitbox
Returns
width of hitbox
Definition at line 154 of file PhysicsBody.java.
References engine.gameObject.components.PhysicsBody.myCollisionBodyWidth.
Referenced by engine.render.GameObjectRenderer.createCollisionBody(), engine.collision.objects.CollisionComposition.fixedCollision(), engine.gameObject.components.PhysicsBody.handleCollision(), and engine.gameObject.components.PhysicsBody.PhysicsBody().
Force engine.gameObject.components.PhysicsBody.getForce (String s)
Definition at line 205 of file PhysicsBody.java.
Referenced by engine.tests.PhysicsBodyTesting.main().
Scalar engine.gameObject.components.PhysicsBody.getScalar (String s)
Definition at line 158 of file PhysicsBody.java.
Referenced by engine.collision.objects.CollisionComposition.fixedCollision(), authoring.view.propertiesview.GameObjectProperties.initializeProperties(), and engine.collision.objects.CollisionComposition.isOnXAxis().
Vector engine.gameObject.components.PhysicsBody.getVelocity ()
Returns
the velocity of the object
Definition at line 114 of file PhysicsBody.java.
References engine.gameObject.components.PhysicsBody.myVelocity.
Referenced by engine.collision.objects.CollisionComposition.fixedCollision(), engine.gameObject.components.PhysicsBody.handleCollision(), authoring.view.propertiesview.GameObjectProperties.initializeProperties(), and engine.collision.objects.CollisionComposition.isOnXAxis().
void engine.gameObject.components.PhysicsBody.handleCollision (GameObject thisSprite, GameObject sprite)
deals with collisions-axis, deals with velocities and will properly move things that are intersecting
Parameters
thisSprite -the sprite dealing with the collision
sprite -the sprite that collides with this one
Definition at line 275 of file PhysicsBody.java.
References engine.gameObject.components.PhysicsBody.collisionHelper(), engine.gameObject.components.PhysicsBody.FRAMES_PER_SECOND, engine.gameObject.components.PhysicsBody.getCollisionBodyHeight(), engine.gameObject.components.PhysicsBody.getCollisionBodyWidth(), engine.gameObject.GameObject.getCollisionConstant(), engine.physics.Vector.getMagnitude(), engine.gameObject.GameObject.getPhysicsBody(), engine.gameObject.GameObject.getPosition(), engine.gameObject.GameObject.getTranslateX(), engine.gameObject.GameObject.getTranslateY(), engine.gameObject.components.PhysicsBody.getVelocity(), engine.physics.Vector.getX(), engine.physics.Vector.getY(), engine.gameObject.GameObject.setTranslateX(), and engine.gameObject.GameObject.setTranslateY().
void engine.gameObject.components.PhysicsBody.initializeMap () private
Sets Velocity of object
Parameters
v
new Velocity of object
Definition at line 80 of file PhysicsBody.java.
Referenced by engine.gameObject.components.PhysicsBody.PhysicsBody().
void engine.gameObject.components.PhysicsBody.reverseVelocity (boolean xAxis)
Definition at line 254 of file PhysicsBody.java.
References engine.physics.Vector.getX(), engine.physics.Vector.getY(), and engine.gameObject.components.PhysicsBody.setVelocity().
Referenced by engine.collision.objects.CollisionComposition.reverseVelocites().
void engine.gameObject.components.PhysicsBody.setAcceleration (Vector v)
Definition at line 106 of file PhysicsBody.java.
void engine.gameObject.components.PhysicsBody.setVelocity (Vector v)
Definition at line 102 of file PhysicsBody.java.
Referenced by authoring.eventhandlers.AddObjectHandler.createGameObject(), authoring.view.propertiesview.GameObjectProperties.edit(), engine.collision.objects.CollisionComposition.fixedCollision(), and engine.gameObject.components.PhysicsBody.reverseVelocity().
void engine.gameObject.components.PhysicsBody.updatePhysicalCharacteristics (GameObject sprite)
updates all the physical vector characteristics for object
- Game object to change things for
Definition at line 174 of file PhysicsBody.java.
References engine.gameObject.components.PhysicsBody.balanceForces(), engine.gameObject.components.PhysicsBody.changeAcceleration(), engine.gameObject.components.PhysicsBody.changeVelocity(), engine.gameObject.components.PhysicsBody.doImpulses(), engine.gameObject.components.PhysicsBody.FRAMES_PER_SECOND, engine.gameObject.GameObject.getTranslateX(), engine.gameObject.GameObject.getTranslateY(), engine.physics.Vector.getX(), engine.physics.Vector.getY(), engine.gameObject.GameObject.setTranslateX(), and engine.gameObject.GameObject.setTranslateY().
Referenced by engine.gameObject.GameObject.update().
Member Data Documentation
final double engine.gameObject.components.PhysicsBody.FRAMES_PER_SECOND = 60.0 static private
Definition at line 37 of file PhysicsBody.java.
Referenced by engine.gameObject.components.PhysicsBody.changeVelocity(), engine.gameObject.components.PhysicsBody.handleCollision(), and engine.gameObject.components.PhysicsBody.updatePhysicalCharacteristics().
boolean engine.gameObject.components.PhysicsBody.haveForcesChanged private
Definition at line 41 of file PhysicsBody.java.
Vector engine.gameObject.components.PhysicsBody.myAcceleration private
Definition at line 39 of file PhysicsBody.java.
Referenced by engine.gameObject.components.PhysicsBody.getAcceleration().
Map<String, Force> engine.gameObject.components.PhysicsBody.myActiveForces private
Definition at line 43 of file PhysicsBody.java.
Vector engine.gameObject.components.PhysicsBody.myBalancedForcesMag private
Definition at line 42 of file PhysicsBody.java.
double engine.gameObject.components.PhysicsBody.myCollisionBodyHeight private
Definition at line 46 of file PhysicsBody.java.
Referenced by engine.gameObject.components.PhysicsBody.getCollisionBodyHeight().
double engine.gameObject.components.PhysicsBody.myCollisionBodyWidth private
Definition at line 45 of file PhysicsBody.java.
Referenced by engine.gameObject.components.PhysicsBody.getCollisionBodyWidth().
Map<String, Scalar> engine.gameObject.components.PhysicsBody.myConstants private
Definition at line 44 of file PhysicsBody.java.
List<Impulse> engine.gameObject.components.PhysicsBody.myImpulses private
Definition at line 38 of file PhysicsBody.java.
Vector engine.gameObject.components.PhysicsBody.myVelocity private
Definition at line 40 of file PhysicsBody.java.
Referenced by engine.gameObject.components.PhysicsBody.getVelocity().
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/voogasalad_BitsPlease/repository/src/engine/gameObject/components/PhysicsBody.java