voogasalad_BitsPlease: authoring.view.icons.ImageBasedIcon Class Reference
authoring.view.icons.ImageBasedIcon Class Reference abstract
Public Member Functions
ImageBasedIcon (String name, File location, GameHandler...event)
void setDimensions (double width, double height, double rotation)
void scaleDimensions ()
Public Member Functions inherited from authoring.view.icons.FileIcon
FileIcon (File gameLoc, String label, GameHandler...handler)
Public Member Functions inherited from authoring.view.icons.BaseIcon
BaseIcon (String label, GameHandler...handler)
void addLabel ()
String getName ()
Protected Member Functions
void makeIcon ()
Protected Member Functions inherited from authoring.view.icons.FileIcon
abstract void makeIcon ()
Protected Attributes
ImageView myImageView
double myWidth
double myHeight
double myRotation
Protected Attributes inherited from authoring.view.icons.FileIcon
File myGameLocation
Protected Attributes inherited from authoring.view.icons.BaseIcon
GameHandler[] myOnClick
String myLabel
Static Private Attributes
static final int DEFAULT_ROTATION = 0
static final int DEFAULT_IMAGE_HEIGHT = 50
static final int DEFAULT_IMAGE_WIDTH = 50
Detailed Description
Represents an image, but does not instantiate JavaFX object so that the object can easily be serialized if necessary.
Author
Chris Bernt
Kevin Li
Arjun Jain
Wesley Valentine
Definition at line 27 of file ImageBasedIcon.java.
Constructor & Destructor Documentation
authoring.view.icons.ImageBasedIcon.ImageBasedIcon (String name, File location, GameHandler... event)
Definition at line 37 of file ImageBasedIcon.java.
References authoring.view.icons.ImageBasedIcon.DEFAULT_IMAGE_HEIGHT, authoring.view.icons.ImageBasedIcon.DEFAULT_IMAGE_WIDTH, authoring.view.icons.ImageBasedIcon.DEFAULT_ROTATION, and authoring.view.icons.ImageBasedIcon.makeIcon().
Member Function Documentation
void authoring.view.icons.ImageBasedIcon.makeIcon () protected
creates an instance of the JavaFX object that can be displayed on the GUI. Takes in a MouseEvent so that the graphic will respond to the specified events.
Parameters
event
Definition at line 55 of file ImageBasedIcon.java.
References authoring.view.icons.FileIcon.myGameLocation, authoring.view.icons.BaseIcon.myLabel, and authoring.view.icons.BaseIcon.myOnClick.
Referenced by authoring.view.icons.ImageBasedIcon.ImageBasedIcon().
void authoring.view.icons.ImageBasedIcon.scaleDimensions ()
Method that scales the dimensions of the image uploaded so that it preserves its dimensions.
Definition at line 92 of file ImageBasedIcon.java.
Referenced by authoring.view.gameobjectsview.GameObjectsView.addGameObject(), and authoring.view.icons.ImageIcon.ImageIcon().
void authoring.view.icons.ImageBasedIcon.setDimensions (double width, double height, double rotation)
Definition at line 79 of file ImageBasedIcon.java.
Referenced by authoring.view.levelview.SingleLevelView.addGameObjectToView().
Member Data Documentation
final int authoring.view.icons.ImageBasedIcon.DEFAULT_IMAGE_HEIGHT = 50 static private
Definition at line 30 of file ImageBasedIcon.java.
Referenced by authoring.view.icons.ImageBasedIcon.ImageBasedIcon().
final int authoring.view.icons.ImageBasedIcon.DEFAULT_IMAGE_WIDTH = 50 static private
Definition at line 31 of file ImageBasedIcon.java.
Referenced by authoring.view.icons.ImageBasedIcon.ImageBasedIcon().
final int authoring.view.icons.ImageBasedIcon.DEFAULT_ROTATION = 0 static private
Definition at line 29 of file ImageBasedIcon.java.
Referenced by authoring.view.icons.ImageBasedIcon.ImageBasedIcon().
double authoring.view.icons.ImageBasedIcon.myHeight protected
Definition at line 34 of file ImageBasedIcon.java.
ImageView authoring.view.icons.ImageBasedIcon.myImageView protected
Definition at line 32 of file ImageBasedIcon.java.
double authoring.view.icons.ImageBasedIcon.myRotation protected
Definition at line 35 of file ImageBasedIcon.java.
double authoring.view.icons.ImageBasedIcon.myWidth protected
Definition at line 33 of file ImageBasedIcon.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/voogasalad_BitsPlease/repository/src/authoring/view/icons/ImageBasedIcon.java