voogasalad_BitsPlease: engine.actions.LabelIntIncrementAction Class Reference
engine.actions.LabelIntIncrementAction Class Reference
Public Member Functions
LabelIntIncrementAction (Identifier labelID)
void initialize (GameManager manager)
void execute ()
Private Attributes
Identifier myLabelID
transient GameObject obj
transient GameManager myManager
Detailed Description
Definition at line 9 of file LabelIntIncrementAction.java.
Constructor & Destructor Documentation
engine.actions.LabelIntIncrementAction.LabelIntIncrementAction (Identifier labelID)
Definition at line 14 of file LabelIntIncrementAction.java.
Member Function Documentation
void engine.actions.LabelIntIncrementAction.execute ()
Will execute the consequences resulting from applying an Action.
Parameters
action
Implements engine.actions.Action.
Definition at line 30 of file LabelIntIncrementAction.java.
References engine.render.GameObjectRenderer.createAndAssignRenderedNode(), engine.gameObject.GameObject.getLabel(), engine.GameManager.getRenderer(), engine.render.GameObjectRenderer.removeRenderedNode(), and engine.gameObject.GameObject.setLabel().
void engine.actions.LabelIntIncrementAction.initialize (GameManager manager)
Implements engine.actions.Initializable.
Definition at line 19 of file LabelIntIncrementAction.java.
References engine.GameManager.getAllGameObjects().
Member Data Documentation
Identifier engine.actions.LabelIntIncrementAction.myLabelID private
Definition at line 10 of file LabelIntIncrementAction.java.
transient GameManager engine.actions.LabelIntIncrementAction.myManager private
Definition at line 12 of file LabelIntIncrementAction.java.
transient GameObject engine.actions.LabelIntIncrementAction.obj private
Definition at line 11 of file LabelIntIncrementAction.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/voogasalad_BitsPlease/repository/src/engine/actions/LabelIntIncrementAction.java