voogasalad_BitsPlease: authoring.view.generalcollectionview.CollectionOptions Class Reference
authoring.view.generalcollectionview.CollectionOptions Class Reference
Public Member Functions
CollectionOptions (ResourceBundle language, double width, double height)
Protected Member Functions
Button makeButton (String property)
Protected Attributes
ResourceBundle myLanguage
double myHeight
double myWidth
Detailed Description
Definition at line 8 of file CollectionOptions.java.
Constructor & Destructor Documentation
authoring.view.generalcollectionview.CollectionOptions.CollectionOptions (ResourceBundle language, double width, double height)
Definition at line 13 of file CollectionOptions.java.
Member Function Documentation
Button authoring.view.generalcollectionview.CollectionOptions.makeButton (String property) protected
Definition at line 19 of file CollectionOptions.java.
Referenced by authoring.view.conditionsview.ConditionOptions.addNewButton(), authoring.view.soundsview.SoundOptions.addNewSoundButton(), authoring.view.graphicsview.GraphicOptions.addNewTabButton(), authoring.view.gameobjectsview.GameObjectOptions.addNewTabButton(), and authoring.view.levelview.LevelOptions.addNewTabButton().
Member Data Documentation
double authoring.view.generalcollectionview.CollectionOptions.myHeight protected
Definition at line 10 of file CollectionOptions.java.
ResourceBundle authoring.view.generalcollectionview.CollectionOptions.myLanguage protected
Definition at line 9 of file CollectionOptions.java.
Referenced by authoring.view.conditionsview.ConditionOptions.addNewButton(), authoring.view.soundsview.SoundOptions.addNewSoundButton(), authoring.view.graphicsview.GraphicOptions.addNewTabButton(), authoring.view.gameobjectsview.GameObjectOptions.addNewTabButton(), and authoring.view.levelview.LevelOptions.addNewTabButton().
double authoring.view.generalcollectionview.CollectionOptions.myWidth protected
Definition at line 11 of file CollectionOptions.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/voogasalad_BitsPlease/repository/src/authoring/view/generalcollectionview/CollectionOptions.java