voogasalad_BitsPlease: authoring.view.graphicsview.GraphicOptions Class Reference
authoring.view.graphicsview.GraphicOptions Class Reference
Public Member Functions
GraphicOptions (ResourceBundle language, double width, double height)
void setButtonBehavior (GameHandler handler)
Public Member Functions inherited from authoring.view.generalcollectionview.CollectionOptions
CollectionOptions (ResourceBundle language, double width, double height)
Private Member Functions
void addNewTabButton ()
Private Attributes
Button addGraphicButton
Additional Inherited Members
Protected Member Functions inherited from authoring.view.generalcollectionview.CollectionOptions
Button makeButton (String property)
Protected Attributes inherited from authoring.view.generalcollectionview.CollectionOptions
ResourceBundle myLanguage
double myHeight
double myWidth
Detailed Description
Author
Kevin Li
Chris Bernt
Wesley Valentine
Arjun Jain
Definition at line 15 of file GraphicOptions.java.
Constructor & Destructor Documentation
authoring.view.graphicsview.GraphicOptions.GraphicOptions (ResourceBundle language, double width, double height)
Definition at line 18 of file GraphicOptions.java.
References authoring.view.graphicsview.GraphicOptions.addNewTabButton().
Member Function Documentation
void authoring.view.graphicsview.GraphicOptions.addNewTabButton () private
Definition at line 23 of file GraphicOptions.java.
References authoring.view.generalcollectionview.CollectionOptions.makeButton(), and authoring.view.generalcollectionview.CollectionOptions.myLanguage.
Referenced by authoring.view.graphicsview.GraphicOptions.GraphicOptions().
void authoring.view.graphicsview.GraphicOptions.setButtonBehavior (GameHandler handler)
Definition at line 28 of file GraphicOptions.java.
Referenced by authoring.controller.AuthoringController.initializeGameHandlers().
Member Data Documentation
Button authoring.view.graphicsview.GraphicOptions.addGraphicButton private
Definition at line 16 of file GraphicOptions.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/voogasalad_BitsPlease/repository/src/authoring/view/graphicsview/GraphicOptions.java