voogasalad_BitsPlease: authoring.view.levelview.LevelsAccordionView Class Reference
authoring.view.levelview.LevelsAccordionView Class Reference
Public Member Functions
LevelsAccordionView (ResourceBundle language, double width, double height)
void update (Observable o, Object arg)
void setIconEvents (GameHandler...gameHandlers)
void setLevelEvents (GameHandler...gameHandlers)
void addLevel (Level l)
String getMyName ()
Public Member Functions inherited from authoring.view.baseclasses.CollectionView
CollectionView (ResourceBundle language, double width, double height)
void setIconEvents (GameHandler...gameHandlers)
Private Attributes
VBox myVbox = new VBox()
GameHandler[] myEvents
GameHandler[] levelEvents
String myName
Static Private Attributes
static final double VIEW_HEIGHT_RATIO = .70
static final double VIEW_WIDTH_RATIO = 0.2
Additional Inherited Members
Protected Member Functions inherited from authoring.view.baseclasses.CollectionView
void setView (double width, double height)
Protected Attributes inherited from authoring.view.baseclasses.CollectionView
ResourceBundle myLanguage
double myHeight
double myWidth
GameHandler[] myIconEvents
Detailed Description
Definition at line 15 of file LevelsAccordionView.java.
Constructor & Destructor Documentation
authoring.view.levelview.LevelsAccordionView.LevelsAccordionView (ResourceBundle language, double width, double height)
Definition at line 23 of file LevelsAccordionView.java.
References authoring.view.baseclasses.CollectionView.setView().
Member Function Documentation
void authoring.view.levelview.LevelsAccordionView.addLevel (Level l)
Definition at line 44 of file LevelsAccordionView.java.
References engine.level.Level.getIdentifier(), and engine.gameObject.Identifier.getUniqueId().
Referenced by authoring.view.levelview.LevelsAccordionView.update().
String authoring.view.levelview.LevelsAccordionView.getMyName ()
Definition at line 51 of file LevelsAccordionView.java.
References authoring.view.levelview.LevelsAccordionView.myName.
void authoring.view.levelview.LevelsAccordionView.setIconEvents (GameHandler... gameHandlers)
Definition at line 36 of file LevelsAccordionView.java.
Referenced by authoring.controller.AuthoringController.initializeGameHandlers().
void authoring.view.levelview.LevelsAccordionView.setLevelEvents (GameHandler... gameHandlers)
Definition at line 40 of file LevelsAccordionView.java.
Referenced by authoring.controller.AuthoringController.initializeGameHandlers().
void authoring.view.levelview.LevelsAccordionView.update (Observable o, Object arg)
This method is called whenever the observed object is changed. An application calls an Observable object's notifyObservers method to have all the object's observers notified of the change.
Parameters
o the observable object.
arg an argument passed to the notifyObservers method.
Implements data.Observer.
Definition at line 31 of file LevelsAccordionView.java.
References authoring.view.levelview.LevelsAccordionView.addLevel().
Member Data Documentation
GameHandler [] authoring.view.levelview.LevelsAccordionView.levelEvents private
Definition at line 20 of file LevelsAccordionView.java.
GameHandler [] authoring.view.levelview.LevelsAccordionView.myEvents private
Definition at line 19 of file LevelsAccordionView.java.
String authoring.view.levelview.LevelsAccordionView.myName private
Definition at line 21 of file LevelsAccordionView.java.
Referenced by authoring.view.levelview.LevelsAccordionView.getMyName().
VBox authoring.view.levelview.LevelsAccordionView.myVbox = new VBox() private
Definition at line 18 of file LevelsAccordionView.java.
final double authoring.view.levelview.LevelsAccordionView.VIEW_HEIGHT_RATIO = .70 static private
Definition at line 16 of file LevelsAccordionView.java.
final double authoring.view.levelview.LevelsAccordionView.VIEW_WIDTH_RATIO = 0.2 static private
Definition at line 17 of file LevelsAccordionView.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/voogasalad_BitsPlease/repository/src/authoring/view/levelview/LevelsAccordionView.java