voogasalad_BitsPlease: engine.level.LevelManager Class Reference
engine.level.LevelManager Class Reference
Public Member Functions
LevelManager (LevelsCollection levels, GameObjectsCollection gameObjects, ConditionsCollection conditions, GameObjectRenderer renderer, SoundUtility soundPlayer)
Iterator< Level > iterator ()
void changeToLevel (Identifier iD)
void update ()
void initializeCurrentLevel ()
GameObject objectForIdentifier (Identifier Id)
Level getCurrentLevel ()
GameObjectsCollection getGameObjects ()
GameObjectsCollection getTemplates ()
Private Member Functions
void findAndSetStartLevel (LevelsCollection levels)
void setCurrentLevel (Level level)
void updateFrameBasedConditions ()
void setLevelEnabledConditions ()
void enableCondition (Identifier conditionID)
void makeTemplates ()
void disableAllConditions ()
Private Attributes
LevelsCollection myLevels
GameObjectsCollection myGameObjects
GameObjectsCollection myTemplateObjects
ConditionsCollection myConditions
Level myCurrentLevel
GameObjectRenderer myRenderer
SoundUtility mySoundPlayer
Detailed Description
Manages the Levels, and progression of the Game
Author
Will Chang
Abhishek Balakrishnan
Eli Lichtenberg
Definition at line 21 of file LevelManager.java.
Constructor & Destructor Documentation
engine.level.LevelManager.LevelManager (LevelsCollection levels, GameObjectsCollection gameObjects, ConditionsCollection conditions, GameObjectRenderer renderer, SoundUtility soundPlayer)
Constructor for a level
Parameters
gameObjects
levels
conditions
renderer
detector
Definition at line 40 of file LevelManager.java.
References engine.level.LevelManager.findAndSetStartLevel(), and engine.level.LevelManager.makeTemplates().
Member Function Documentation
void engine.level.LevelManager.changeToLevel (Identifier iD)
Sets current Level and initializes
Parameters
levelIndex
Definition at line 86 of file LevelManager.java.
References engine.level.LevelManager.initializeCurrentLevel(), and engine.level.LevelManager.setCurrentLevel().
Referenced by engine.actions.ChangeLevelAction.execute().
void engine.level.LevelManager.disableAllConditions () private
Disable all conditions before enabling the correct ones
Definition at line 173 of file LevelManager.java.
Referenced by engine.level.LevelManager.initializeCurrentLevel().
void engine.level.LevelManager.enableCondition (Identifier conditionID) private
Find condition in master list and enable it
Parameters
conditionID
Definition at line 153 of file LevelManager.java.
Referenced by engine.level.LevelManager.setLevelEnabledConditions().
void engine.level.LevelManager.findAndSetStartLevel (LevelsCollection levels) private
TODO undo duplicated code...
Parameters
levels
Definition at line 58 of file LevelManager.java.
References engine.level.LevelManager.initializeCurrentLevel().
Referenced by engine.level.LevelManager.LevelManager().
Level engine.level.LevelManager.getCurrentLevel ()
Definition at line 179 of file LevelManager.java.
References engine.level.LevelManager.myCurrentLevel.
Referenced by engine.actions.ResetLevelAction.initialize(), engine.actions.TypeAction.initialize(), engine.actions.TranslateTypeAction.initialize(), engine.actions.PhysicsTypeAction.initialize(), engine.actions.MakeNewObjectAction.initialize(), and engine.conditions.TypeCollisionCondition.initialize().
GameObjectsCollection engine.level.LevelManager.getGameObjects ()
Definition at line 183 of file LevelManager.java.
References engine.level.LevelManager.myGameObjects.
Referenced by engine.actions.DeleteIdAction.initialize().
GameObjectsCollection engine.level.LevelManager.getTemplates ()
Definition at line 187 of file LevelManager.java.
References engine.level.LevelManager.myTemplateObjects.
Referenced by engine.actions.MakeNewObjectAction.initialize().
void engine.level.LevelManager.initializeCurrentLevel ()
Initializes the Current Level
Definition at line 116 of file LevelManager.java.
References engine.level.LevelManager.disableAllConditions(), engine.level.Level.getBackgroundMusic(), engine.level.Level.initialize(), engine.sound.SoundUtility.playBackGroundMusic(), engine.render.GameObjectRenderer.renderGameObjects(), engine.level.LevelManager.setLevelEnabledConditions(), and engine.sound.SoundUtility.stopBackGroundMusic().
Referenced by engine.level.LevelManager.changeToLevel(), and engine.level.LevelManager.findAndSetStartLevel().
Iterator<Level> engine.level.LevelManager.iterator ()
Iterates through the list of Levels in the managers
Definition at line 77 of file LevelManager.java.
References authoring.model.collections.GeneralCollection< T >.iterator().
void engine.level.LevelManager.makeTemplates () private
Definition at line 161 of file LevelManager.java.
References authoring.model.collections.GeneralCollection< T >.add().
Referenced by engine.level.LevelManager.LevelManager().
GameObject engine.level.LevelManager.objectForIdentifier (Identifier Id)
Definition at line 139 of file LevelManager.java.
Referenced by engine.level.Level.initialize(), and engine.GameManager.objectForIdentifier().
void engine.level.LevelManager.setCurrentLevel (Level level) private
Definition at line 69 of file LevelManager.java.
References engine.level.Level.initialize().
Referenced by engine.level.LevelManager.changeToLevel().
void engine.level.LevelManager.setLevelEnabledConditions () private
Iterate through all level's condition IDs and turn on the corresponding condition from master list
Definition at line 133 of file LevelManager.java.
References engine.level.LevelManager.enableCondition(), and engine.level.Level.getConditionIdentifiers().
Referenced by engine.level.LevelManager.initializeCurrentLevel().
void engine.level.LevelManager.update ()
Update call, updates the current level Happens every frame
Definition at line 99 of file LevelManager.java.
References engine.level.Level.update(), and engine.level.LevelManager.updateFrameBasedConditions().
Referenced by engine.GameManager.processFrame().
void engine.level.LevelManager.updateFrameBasedConditions () private
update the conditions that rely on frame calculations
Definition at line 107 of file LevelManager.java.
Referenced by engine.level.LevelManager.update().
Member Data Documentation
ConditionsCollection engine.level.LevelManager.myConditions private
Definition at line 25 of file LevelManager.java.
Level engine.level.LevelManager.myCurrentLevel private
Definition at line 26 of file LevelManager.java.
Referenced by engine.level.LevelManager.getCurrentLevel().
GameObjectsCollection engine.level.LevelManager.myGameObjects private
Definition at line 23 of file LevelManager.java.
Referenced by engine.level.LevelManager.getGameObjects().
LevelsCollection engine.level.LevelManager.myLevels private
Definition at line 22 of file LevelManager.java.
GameObjectRenderer engine.level.LevelManager.myRenderer private
Definition at line 28 of file LevelManager.java.
SoundUtility engine.level.LevelManager.mySoundPlayer private
Definition at line 29 of file LevelManager.java.
GameObjectsCollection engine.level.LevelManager.myTemplateObjects private
Definition at line 24 of file LevelManager.java.
Referenced by engine.level.LevelManager.getTemplates().
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/voogasalad_BitsPlease/repository/src/engine/level/LevelManager.java