voogasalad_BitsPlease: gamePlayer.model.PlayerModel Class Reference
gamePlayer.model.PlayerModel Class Reference
Public Member Functions
PlayerModel ()
void initializeView () throws IOException
void loadGameFile ()
void saveGameToWeb ()
void fetchGameFromWeb ()
ConditionsCollection getButtonConditions ()
void exitFromGame ()
void exitFromGamePlayer ()
void pauseGame ()
void saveGameProgress ()
void loadGameProgress ()
Private Member Functions
void addFileNameChangeListener ()
void loadGameData ()
void extractButtonConditions ()
Private Attributes
GameData myGameData
DataManager myDataManager
PlayerView myPlayerView
GameManager myGameManager
ConditionsCollection myButtonConditions
FileSelectionWizard myFileSelector
File myGameLocation
ProgressSelector myProgressSelector
StringProperty progressFileName
Detailed Description
Author
Abhishek B
Shreyas B
Eli Lichtenberg
Definition at line 30 of file PlayerModel.java.
Constructor & Destructor Documentation
gamePlayer.model.PlayerModel.PlayerModel ()
Definition at line 42 of file PlayerModel.java.
References gamePlayer.model.PlayerModel.addFileNameChangeListener().
Member Function Documentation
void gamePlayer.model.PlayerModel.addFileNameChangeListener () private
Definition at line 52 of file PlayerModel.java.
References errorsAndExceptions.ErrorPopUp.display(), gamePlayer.model.PlayerModel.loadGameData(), and data.DataManager.readProgressFile().
Referenced by gamePlayer.model.PlayerModel.PlayerModel().
void gamePlayer.model.PlayerModel.exitFromGame ()
Definition at line 107 of file PlayerModel.java.
References engine.GameManager.clear(), and gamePlayer.model.PlayerModel.exitFromGamePlayer().
void gamePlayer.model.PlayerModel.exitFromGamePlayer ()
Clear the game and close this stage Return to the splash screen
Definition at line 116 of file PlayerModel.java.
References gamePlayer.view.PlayerView.close(), and application.SplashScreen.show().
Referenced by gamePlayer.model.PlayerModel.exitFromGame(), and gamePlayer.view.MenuBarController.exitFromGamePlayer().
void gamePlayer.model.PlayerModel.extractButtonConditions () private
Definition at line 126 of file PlayerModel.java.
References authoring.model.collections.ConditionsCollection.add(), and authoring.model.GameData.getConditions().
Referenced by gamePlayer.model.PlayerModel.loadGameData().
void gamePlayer.model.PlayerModel.fetchGameFromWeb ()
Definition at line 99 of file PlayerModel.java.
Referenced by gamePlayer.view.MenuBarController.fetchGameFromWeb().
ConditionsCollection gamePlayer.model.PlayerModel.getButtonConditions ()
Definition at line 103 of file PlayerModel.java.
References gamePlayer.model.PlayerModel.myButtonConditions.
Referenced by gamePlayer.view.MenuBarController.setKeyboard().
void gamePlayer.model.PlayerModel.initializeView () throws IOException
Definition at line 68 of file PlayerModel.java.
References gamePlayer.view.PlayerView.initialize().
Referenced by application.SplashScreen.play().
void gamePlayer.model.PlayerModel.loadGameData () private
Definition at line 87 of file PlayerModel.java.
References gamePlayer.model.PlayerModel.extractButtonConditions(), authoring.model.GameData.getConditions(), authoring.model.GameData.getGameObjects(), gamePlayer.view.PlayerView.getGroup(), authoring.model.GameData.getLevels(), and engine.GameManager.initialize().
Referenced by gamePlayer.model.PlayerModel.addFileNameChangeListener(), and gamePlayer.model.PlayerModel.loadGameFile().
void gamePlayer.model.PlayerModel.loadGameFile ()
Definition at line 72 of file PlayerModel.java.
References errorsAndExceptions.ErrorPopUp.display(), gamePlayer.model.PlayerModel.loadGameData(), data.DataManager.readGameFile(), and gamePlayer.view.FileSelectionWizard.selectFile().
Referenced by gamePlayer.view.MenuBarController.loadGameFile().
void gamePlayer.model.PlayerModel.loadGameProgress ()
This will load a file with file selector
Definition at line 144 of file PlayerModel.java.
References gamePlayer.view.ProgressSelector.loadProgressState().
Referenced by gamePlayer.view.MenuBarController.loadGameProgress().
void gamePlayer.model.PlayerModel.pauseGame ()
Definition at line 122 of file PlayerModel.java.
References engine.GameManager.togglePause().
Referenced by gamePlayer.view.MenuBarController.keyCombos(), and gamePlayer.view.MenuBarController.pauseGame().
void gamePlayer.model.PlayerModel.saveGameProgress ()
This will save a file with file selector
Definition at line 137 of file PlayerModel.java.
References gamePlayer.view.ProgressSelector.saveProgressState().
Referenced by gamePlayer.view.MenuBarController.saveGameProgress().
void gamePlayer.model.PlayerModel.saveGameToWeb ()
Definition at line 95 of file PlayerModel.java.
Referenced by gamePlayer.view.MenuBarController.saveGameToWeb().
Member Data Documentation
ConditionsCollection gamePlayer.model.PlayerModel.myButtonConditions private
Definition at line 36 of file PlayerModel.java.
Referenced by gamePlayer.model.PlayerModel.getButtonConditions().
DataManager gamePlayer.model.PlayerModel.myDataManager private
Definition at line 33 of file PlayerModel.java.
FileSelectionWizard gamePlayer.model.PlayerModel.myFileSelector private
Definition at line 37 of file PlayerModel.java.
GameData gamePlayer.model.PlayerModel.myGameData private
Definition at line 32 of file PlayerModel.java.
File gamePlayer.model.PlayerModel.myGameLocation private
Definition at line 38 of file PlayerModel.java.
GameManager gamePlayer.model.PlayerModel.myGameManager private
Definition at line 35 of file PlayerModel.java.
PlayerView gamePlayer.model.PlayerModel.myPlayerView private
Definition at line 34 of file PlayerModel.java.
ProgressSelector gamePlayer.model.PlayerModel.myProgressSelector private
Definition at line 39 of file PlayerModel.java.
StringProperty gamePlayer.model.PlayerModel.progressFileName private
Definition at line 40 of file PlayerModel.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/voogasalad_BitsPlease/repository/src/gamePlayer/model/PlayerModel.java