voogasalad_BitsPlease: authoring.eventhandlers.GameObjGraphicDragHandler Class Reference
authoring.eventhandlers.GameObjGraphicDragHandler Class Reference
Public Member Functions
GameObjGraphicDragHandler (LevelsView levelView)
void handle (MouseEvent event)
EventType< MouseEvent > getEventType ()
Public Member Functions inherited from authoring.eventhandlers.GameHandler< MouseEvent >
void handle (T arg0)
EventType< T > getEventType ()
Private Attributes
LevelsView myLevelView
Detailed Description
Event handler for animation of dragging graphics on the level view. Properties are not updated until drag is released.
Author
Eli Lichtenberg
Wesley Valentine
Definition at line 18 of file GameObjGraphicDragHandler.java.
Constructor & Destructor Documentation
authoring.eventhandlers.GameObjGraphicDragHandler.GameObjGraphicDragHandler (LevelsView levelView)
Definition at line 22 of file GameObjGraphicDragHandler.java.
Member Function Documentation
EventType<MouseEvent> authoring.eventhandlers.GameObjGraphicDragHandler.getEventType ()
Definition at line 41 of file GameObjGraphicDragHandler.java.
void authoring.eventhandlers.GameObjGraphicDragHandler.handle (MouseEvent event)
Definition at line 27 of file GameObjGraphicDragHandler.java.
References authoring.view.levelview.LevelsView.getCurrentLevel(), authoring.view.levelview.SingleLevelView.getPaneHeight(), authoring.view.levelview.SingleLevelView.getPaneWidth(), authoring.view.levelview.SingleLevelView.getViewHeight(), authoring.view.levelview.SingleLevelView.getViewWidth(), and authoring.view.levelview.SingleLevelView.moveGameObjectToLevel().
Member Data Documentation
LevelsView authoring.eventhandlers.GameObjGraphicDragHandler.myLevelView private
Definition at line 20 of file GameObjGraphicDragHandler.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/voogasalad_BitsPlease/repository/src/authoring/eventhandlers/GameObjGraphicDragHandler.java