voogasalad_BitsPlease: engine.actions.render.ChangeImageIDAction Class Reference
engine.actions.render.ChangeImageIDAction Class Reference
Public Member Functions
ChangeImageIDAction (List< Identifier > ids, String pathName)
void initialize (GameManager manager)
void execute ()
Public Member Functions inherited from engine.actions.IDAction
IDAction (List< Identifier > ids)
void initialize (GameManager manager)
Private Attributes
String myPathName
transient GameObjectRenderer myRenderer
Additional Inherited Members
Protected Attributes inherited from engine.actions.IDAction
List< Identifier > myIDs
transient GameObjectsCollection myGameObjects
Detailed Description
Definition at line 11 of file ChangeImageIDAction.java.
Constructor & Destructor Documentation
engine.actions.render.ChangeImageIDAction.ChangeImageIDAction (List< Identifier > ids, String pathName)
Definition at line 16 of file ChangeImageIDAction.java.
Member Function Documentation
void engine.actions.render.ChangeImageIDAction.execute ()
Will execute the consequences resulting from applying an Action.
Parameters
action
Implements engine.actions.Action.
Definition at line 29 of file ChangeImageIDAction.java.
References engine.render.GameObjectRenderer.createAndAssignRenderedNode(), engine.actions.IDAction.myGameObjects, and engine.render.GameObjectRenderer.removeRenderedNode().
void engine.actions.render.ChangeImageIDAction.initialize (GameManager manager)
Implements engine.actions.Initializable.
Definition at line 23 of file ChangeImageIDAction.java.
References engine.GameManager.getRenderer().
Member Data Documentation
String engine.actions.render.ChangeImageIDAction.myPathName private
Definition at line 13 of file ChangeImageIDAction.java.
transient GameObjectRenderer engine.actions.render.ChangeImageIDAction.myRenderer private
Definition at line 14 of file ChangeImageIDAction.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/voogasalad_BitsPlease/repository/src/engine/actions/render/ChangeImageIDAction.java