voogasalad_BitsPlease: authoring.view.soundsview.SoundsView Class Reference
authoring.view.soundsview.SoundsView Class Reference
Public Member Functions
SoundsView (ResourceBundle language, double width, double height, File gameLoc)
void setDragOver (GameHandler< Event > handler)
void setDragDrop (GameHandler< Event > handler)
void update (Observable o, Object arg)
Public Member Functions inherited from authoring.view.baseclasses.CollectionView
CollectionView (ResourceBundle language, double width, double height)
void setIconEvents (GameHandler...gameHandlers)
Private Member Functions
void addSound (String arg)
Private Attributes
File myGameLocation
VBox myContents = new VBox()
Static Private Attributes
static final double VIEW_HEIGHT_RATIO = .65
static final double VIEW_WIDTH_RATIO = 0.2
Additional Inherited Members
Protected Member Functions inherited from authoring.view.baseclasses.CollectionView
void setView (double width, double height)
Protected Attributes inherited from authoring.view.baseclasses.CollectionView
ResourceBundle myLanguage
double myHeight
double myWidth
GameHandler[] myIconEvents
Detailed Description
View component that corresponds with backend model data - SoundCollection. Updates via observer whenever a change occurs in SoundCollection.
Author
Kevin Li
Chris Bernt
Wesley Valentine
Arjun Jain
Definition at line 23 of file SoundsView.java.
Constructor & Destructor Documentation
authoring.view.soundsview.SoundsView.SoundsView (ResourceBundle language, double width, double height, File gameLoc)
Definition at line 30 of file SoundsView.java.
References authoring.view.baseclasses.CollectionView.setView().
Member Function Documentation
void authoring.view.soundsview.SoundsView.addSound (String arg) private
Definition at line 38 of file SoundsView.java.
References authoring.view.baseclasses.CollectionView.myIconEvents.
Referenced by authoring.view.soundsview.SoundsView.update().
void authoring.view.soundsview.SoundsView.setDragDrop (GameHandler< Event > handler)
Definition at line 47 of file SoundsView.java.
Referenced by authoring.controller.AuthoringController.initializeGameHandlers().
void authoring.view.soundsview.SoundsView.setDragOver (GameHandler< Event > handler)
Definition at line 43 of file SoundsView.java.
Referenced by authoring.controller.AuthoringController.initializeGameHandlers().
void authoring.view.soundsview.SoundsView.update (Observable o, Object arg)
This method is called whenever the observed object is changed. An application calls an Observable object's notifyObservers method to have all the object's observers notified of the change.
Parameters
o the observable object.
arg an argument passed to the notifyObservers method.
Implements data.Observer.
Definition at line 52 of file SoundsView.java.
References authoring.view.soundsview.SoundsView.addSound().
Member Data Documentation
VBox authoring.view.soundsview.SoundsView.myContents = new VBox() private
Definition at line 28 of file SoundsView.java.
File authoring.view.soundsview.SoundsView.myGameLocation private
Definition at line 27 of file SoundsView.java.
final double authoring.view.soundsview.SoundsView.VIEW_HEIGHT_RATIO = .65 static private
Definition at line 24 of file SoundsView.java.
final double authoring.view.soundsview.SoundsView.VIEW_WIDTH_RATIO = 0.2 static private
Definition at line 25 of file SoundsView.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/voogasalad_BitsPlease/repository/src/authoring/view/soundsview/SoundsView.java