voogasalad_BitsPlease: engine.gameObject.GameObject Class Reference
engine.gameObject.GameObject Class Reference
Public Member Functions
GameObject ()
GameObject (String iD)
GameObject (List< Component > components, String imageName, double x, double y, double height, double width, double rotation, String iD)
GameObject (GameObject g)
GameObject (GameObject g, double x, double y, String type)
void setTranslateX (double xCoord)
void setTranslateY (double yCoord)
double getTranslateX ()
double getTranslateY ()
void setX (double x)
void setY (double y)
void setWidth (double width)
void setHeight (double height)
void setOrientation (double orientation)
double getOrientation ()
double getRotation ()
DoubleProperty getXPositionProperty ()
DoubleProperty getYPositionProperty ()
Point2D getPosition ()
double getX ()
double getY ()
String getID ()
void setID (String s)
void update ()
void setRenderedNode (RenderedNode node)
RenderedNode getRenderedNode ()
Component getComponent (Identifier iD)
List< Component > getComponents ()
void addComponent (Component comp)
void removeComponent (Component comp)
String getCurrentImageName ()
void setCurrentImagePath (String imageName)
Iterator< Component > iterator ()
void saveCurrentState ()
void setPhysicsBody (PhysicsBody physicsBody)
PhysicsBody getPhysicsBody ()
double getHeight ()
double getWidth ()
void enableCollision ()
void disableCollision ()
boolean isCollisionEnabled ()
void enable ()
void disable ()
boolean isEnabled ()
boolean getCollisionConstant ()
String toString ()
void reset ()
void setLabel (String label)
String getLabel ()
void setIdentifier (Identifier myId)
Identifier getIdentifier ()
Private Member Functions
void setDefaultData ()
Private Attributes
List< Component > myComponents
double myRotation
String myCurrentImageName
String myID
PhysicsBody myPhysicsBody
String myLabel
double myHeight
double myWidth
double myXCoord
double myYCoord
transient RenderedNode myRenderedNode
transient ScrollingUtility myScrollingUtility
boolean myCollision
boolean enabled
DefaultData myDefaultData
Identifier myId
boolean collisionEnabled
Detailed Description
This class initiates a list of components which are characteristics of the GameObject.
Author
Arihant Jain
Will Chang
Definition at line 19 of file GameObject.java.
Constructor & Destructor Documentation
engine.gameObject.GameObject.GameObject ()
Constructors
Definition at line 52 of file GameObject.java.
engine.gameObject.GameObject.GameObject (String iD)
Definition at line 56 of file GameObject.java.
engine.gameObject.GameObject.GameObject (List< Component > components, String imageName, double x, double y, double height, double width, double rotation, String iD)
Definition at line 60 of file GameObject.java.
References engine.gameObject.GameObject.setDefaultData().
engine.gameObject.GameObject.GameObject (GameObject g)
Definition at line 74 of file GameObject.java.
References engine.gameObject.GameObject.getComponents(), engine.gameObject.GameObject.getCurrentImageName(), engine.gameObject.GameObject.getHeight(), engine.gameObject.GameObject.getID(), engine.gameObject.GameObject.getPhysicsBody(), engine.gameObject.GameObject.getRotation(), engine.gameObject.GameObject.getWidth(), engine.gameObject.GameObject.getX(), engine.gameObject.GameObject.getY(), and engine.gameObject.GameObject.setPhysicsBody().
engine.gameObject.GameObject.GameObject (GameObject g, double x, double y, String type)
Definition at line 79 of file GameObject.java.
References engine.gameObject.GameObject.getComponents(), engine.gameObject.GameObject.getCurrentImageName(), engine.gameObject.GameObject.getHeight(), engine.gameObject.GameObject.getRotation(), and engine.gameObject.GameObject.getWidth().
Member Function Documentation
void engine.gameObject.GameObject.addComponent (Component comp)
Definition at line 251 of file GameObject.java.
void engine.gameObject.GameObject.disable ()
Implements engine.gameObject.IEnabled.
Definition at line 311 of file GameObject.java.
void engine.gameObject.GameObject.disableCollision ()
Definition at line 299 of file GameObject.java.
void engine.gameObject.GameObject.enable ()
Implements engine.gameObject.IEnabled.
Definition at line 307 of file GameObject.java.
void engine.gameObject.GameObject.enableCollision ()
Definition at line 295 of file GameObject.java.
boolean engine.gameObject.GameObject.getCollisionConstant ()
Definition at line 319 of file GameObject.java.
References engine.gameObject.GameObject.myCollision.
Referenced by engine.gameObject.components.PhysicsBody.handleCollision().
Component engine.gameObject.GameObject.getComponent (Identifier iD)
Temporary Map based getter...
Parameters
iD
Returns
Definition at line 237 of file GameObject.java.
List<Component> engine.gameObject.GameObject.getComponents ()
Definition at line 247 of file GameObject.java.
References engine.gameObject.GameObject.myComponents.
Referenced by authoring.view.propertiesview.GameObjectProperties.edit(), and engine.gameObject.GameObject.GameObject().
String engine.gameObject.GameObject.getCurrentImageName ()
Definition at line 259 of file GameObject.java.
References engine.gameObject.GameObject.myCurrentImageName.
Referenced by engine.render.GameObjectRenderer.createImageAndView(), engine.gameObject.GameObject.GameObject(), authoring.view.icons.GameObjectIcon.GameObjectIcon(), and authoring.view.propertiesview.GameObjectProperties.initializeProperties().
double engine.gameObject.GameObject.getHeight ()
Definition at line 287 of file GameObject.java.
References engine.gameObject.GameObject.myHeight.
Referenced by authoring.view.levelview.SingleLevelView.addGameObjectToView(), engine.render.GameObjectRenderer.createImageAndView(), engine.render.GameObjectRenderer.createLabel(), engine.gameObject.GameObject.GameObject(), and authoring.view.propertiesview.GameObjectProperties.initializeProperties().
String engine.gameObject.GameObject.getID ()
Definition at line 200 of file GameObject.java.
References engine.gameObject.GameObject.myID.
Referenced by engine.render.GameObjectRenderer.createAndAssignRenderedNode(), authoring.view.propertiesview.GameObjectProperties.edit(), and engine.gameObject.GameObject.GameObject().
Identifier engine.gameObject.GameObject.getIdentifier ()
Implements engine.gameObject.Identifiable.
Definition at line 352 of file GameObject.java.
References engine.gameObject.GameObject.myId.
Referenced by engine.render.GameObjectRenderer.createAndAssignRenderedNode(), engine.tests.MainEngineTests.createGameObject(), games.MarioGameTest.createGameObject(), authoring.view.propertiesview.GameObjectProperties.edit(), authoring.view.wizards.GameObjectTypeWizard.getIdentifierComponent(), authoring.view.wizards.GameObjectUniqueIDWizard.getIdentifierComponent(), authoring.model.collections.GameObjectsCollection.getIdentifierList(), authoring.eventhandlers.GameObjectDragToLevelHandler.handle(), engine.level.Level.initialize(), authoring.view.propertiesview.GameObjectProperties.initializeProperties(), engine.render.GameObjectRenderer.renderGameObjects(), and authoring.eventhandlers.GameObjectDragToLevelHandler.updateName().
String engine.gameObject.GameObject.getLabel ()
Definition at line 342 of file GameObject.java.
References engine.gameObject.GameObject.myLabel.
Referenced by engine.render.GameObjectRenderer.createLabel().
double engine.gameObject.GameObject.getOrientation ()
Gets the Orientation of Sprite
Returns
Definition at line 159 of file GameObject.java.
Referenced by engine.actions.MakeNewObjectFromObjectAction.execute().
PhysicsBody engine.gameObject.GameObject.getPhysicsBody ()
Definition at line 283 of file GameObject.java.
References engine.gameObject.GameObject.myPhysicsBody.
Referenced by engine.render.GameObjectRenderer.createCollisionBody(), engine.collision.objects.CollisionComposition.fixedCollision(), engine.gameObject.GameObject.GameObject(), engine.gameObject.components.PhysicsBody.handleCollision(), authoring.view.propertiesview.GameObjectProperties.initializeProperties(), engine.collision.objects.CollisionComposition.isOnXAxis(), and engine.collision.objects.CollisionComposition.reverseVelocites().
Point2D engine.gameObject.GameObject.getPosition ()
Gets the Position of Sprite
Returns
myPosition
Definition at line 187 of file GameObject.java.
Referenced by engine.gameObject.components.PhysicsBody.handleCollision().
RenderedNode engine.gameObject.GameObject.getRenderedNode ()
Definition at line 228 of file GameObject.java.
References engine.gameObject.GameObject.myRenderedNode.
Referenced by engine.collision.objects.CollisionComposition.isOnXAxis().
double engine.gameObject.GameObject.getRotation ()
Definition at line 163 of file GameObject.java.
References engine.gameObject.GameObject.myRotation.
Referenced by authoring.view.levelview.SingleLevelView.addGameObjectToView(), engine.gameObject.GameObject.GameObject(), and authoring.view.propertiesview.GameObjectProperties.initializeProperties().
double engine.gameObject.GameObject.getTranslateX ()
Definition at line 114 of file GameObject.java.
Referenced by engine.actions.MakeNewObjectFromObjectAction.execute(), engine.collision.objects.CollisionComposition.fixedCollision(), engine.gameObject.components.PhysicsBody.handleCollision(), engine.collision.objects.CollisionComposition.isOnXAxis(), and engine.gameObject.components.PhysicsBody.updatePhysicalCharacteristics().
double engine.gameObject.GameObject.getTranslateY ()
Definition at line 118 of file GameObject.java.
Referenced by engine.actions.MakeNewObjectFromObjectAction.execute(), engine.collision.objects.CollisionComposition.fixedCollision(), engine.gameObject.components.PhysicsBody.handleCollision(), engine.collision.objects.CollisionComposition.isOnXAxis(), and engine.gameObject.components.PhysicsBody.updatePhysicalCharacteristics().
double engine.gameObject.GameObject.getWidth ()
Definition at line 291 of file GameObject.java.
References engine.gameObject.GameObject.myWidth.
Referenced by authoring.view.levelview.SingleLevelView.addGameObjectToView(), engine.render.GameObjectRenderer.createImageAndView(), engine.render.GameObjectRenderer.createLabel(), engine.gameObject.GameObject.GameObject(), and authoring.view.propertiesview.GameObjectProperties.initializeProperties().
double engine.gameObject.GameObject.getX ()
Definition at line 192 of file GameObject.java.
References engine.gameObject.GameObject.myXCoord.
Referenced by engine.render.GameObjectRenderer.createAndAssignRenderedNode(), engine.gameObject.GameObject.GameObject(), and authoring.view.propertiesview.GameObjectProperties.initializeProperties().
DoubleProperty engine.gameObject.GameObject.getXPositionProperty ()
Deprecated, all transforms are performed on the node Gets the x position property of the sprite (for listeners)
Definition at line 171 of file GameObject.java.
double engine.gameObject.GameObject.getY ()
Definition at line 196 of file GameObject.java.
References engine.gameObject.GameObject.myYCoord.
Referenced by engine.render.GameObjectRenderer.createAndAssignRenderedNode(), engine.gameObject.GameObject.GameObject(), and authoring.view.propertiesview.GameObjectProperties.initializeProperties().
DoubleProperty engine.gameObject.GameObject.getYPositionProperty ()
Deprecated, all transforms are performed on the node Gets the y position property of the sprite (for listeners)
Definition at line 179 of file GameObject.java.
boolean engine.gameObject.GameObject.isCollisionEnabled ()
Definition at line 303 of file GameObject.java.
References engine.gameObject.GameObject.collisionEnabled.
boolean engine.gameObject.GameObject.isEnabled ()
Implements engine.gameObject.IEnabled.
Definition at line 315 of file GameObject.java.
References engine.gameObject.GameObject.enabled.
Iterator<Component> engine.gameObject.GameObject.iterator ()
Definition at line 269 of file GameObject.java.
void engine.gameObject.GameObject.removeComponent (Component comp)
Definition at line 255 of file GameObject.java.
void engine.gameObject.GameObject.reset ()
Definition at line 327 of file GameObject.java.
References engine.gameObject.DefaultData.getComponents(), engine.gameObject.DefaultData.getImageName(), engine.gameObject.DefaultData.getRotation(), engine.gameObject.DefaultData.getXCoordinate(), and engine.gameObject.DefaultData.getYCoordinate().
void engine.gameObject.GameObject.saveCurrentState ()
Definition at line 273 of file GameObject.java.
void engine.gameObject.GameObject.setCurrentImagePath (String imageName)
Definition at line 263 of file GameObject.java.
References engine.render.RenderedNode.getImageView().
Referenced by engine.states.State.enter().
void engine.gameObject.GameObject.setDefaultData () private
Definition at line 84 of file GameObject.java.
Referenced by engine.gameObject.GameObject.GameObject().
void engine.gameObject.GameObject.setHeight (double height)
Definition at line 143 of file GameObject.java.
void engine.gameObject.GameObject.setID (String s)
Definition at line 204 of file GameObject.java.
void engine.gameObject.GameObject.setIdentifier (Identifier myId)
Implements engine.gameObject.Identifiable.
Definition at line 347 of file GameObject.java.
References engine.gameObject.GameObject.myId.
Referenced by engine.tests.MainEngineTests.createGameObject(), games.MarioGameTest.createGameObject(), authoring.view.propertiesview.GameObjectProperties.edit(), engine.actions.MakeNewObjectFromLocationAction.execute(), engine.actions.MakeNewObjectFromObjectAction.execute(), authoring.eventhandlers.GameObjectDragToLevelHandler.handle(), engine.actions.MakeNewRandomObjectAction.makeRandomObject(), authoring.eventhandlers.SaveAsNewHandler.updateName(), and authoring.eventhandlers.AddObjectHandler.updateName().
void engine.gameObject.GameObject.setLabel (String label)
Definition at line 338 of file GameObject.java.
Referenced by engine.tests.MainEngineTests.createGameObject().
void engine.gameObject.GameObject.setOrientation (double orientation)
Sets Orientation of Sprite
Parameters
orientation
Definition at line 151 of file GameObject.java.
Referenced by engine.actions.MakeNewObjectFromObjectAction.execute().
void engine.gameObject.GameObject.setPhysicsBody (PhysicsBody physicsBody)
Definition at line 279 of file GameObject.java.
Referenced by authoring.eventhandlers.AddObjectHandler.createGameObject(), engine.tests.MainEngineTests.createGameObject(), games.MarioGameTest.createGameObject(), authoring.view.propertiesview.GameObjectProperties.edit(), engine.actions.MakeNewObjectFromLocationAction.execute(), engine.actions.MakeNewObjectFromObjectAction.execute(), engine.gameObject.GameObject.GameObject(), and engine.actions.MakeNewRandomObjectAction.makeRandomObject().
void engine.gameObject.GameObject.setRenderedNode (RenderedNode node)
Definition at line 224 of file GameObject.java.
Referenced by engine.render.GameObjectRenderer.createAndAssignRenderedNode().
void engine.gameObject.GameObject.setTranslateX (double xCoord)
Sets X-Coordinate of Object
Parameters
x - New X coordinate of Object
Definition at line 102 of file GameObject.java.
Referenced by engine.collision.objects.CollisionComposition.fixedCollision(), engine.gameObject.components.PhysicsBody.handleCollision(), engine.collision.objects.CollisionComposition.isOnXAxis(), and engine.gameObject.components.PhysicsBody.updatePhysicalCharacteristics().
void engine.gameObject.GameObject.setTranslateY (double yCoord)
Sets Y-Coordinate of Object
Parameters
y - New Y coordinate of Object
Definition at line 110 of file GameObject.java.
Referenced by engine.collision.objects.CollisionComposition.fixedCollision(), engine.gameObject.components.PhysicsBody.handleCollision(), engine.collision.objects.CollisionComposition.isOnXAxis(), and engine.gameObject.components.PhysicsBody.updatePhysicalCharacteristics().
void engine.gameObject.GameObject.setWidth (double width)
Link this with the physics body in the future
Parameters
width
Definition at line 139 of file GameObject.java.
void engine.gameObject.GameObject.setX (double x)
Sets Initial Location of GameObject
Parameters
point - new Location Point
Definition at line 126 of file GameObject.java.
Referenced by authoring.eventhandlers.GameObjectDragHandler.handle(), and authoring.eventhandlers.GameObjectDragToLevelHandler.handle().
void engine.gameObject.GameObject.setY (double y)
Definition at line 130 of file GameObject.java.
Referenced by authoring.eventhandlers.GameObjectDragHandler.handle(), and authoring.eventhandlers.GameObjectDragToLevelHandler.handle().
String engine.gameObject.GameObject.toString ()
Definition at line 323 of file GameObject.java.
References engine.gameObject.GameObject.myID.
void engine.gameObject.GameObject.update ()
Updates all components of GameObject TODO Check if necessary...
Definition at line 213 of file GameObject.java.
References engine.gameObject.components.PhysicsBody.updatePhysicalCharacteristics().
Member Data Documentation
boolean engine.gameObject.GameObject.collisionEnabled private
Definition at line 46 of file GameObject.java.
Referenced by engine.gameObject.GameObject.isCollisionEnabled().
boolean engine.gameObject.GameObject.enabled private
Definition at line 37 of file GameObject.java.
Referenced by engine.gameObject.GameObject.isEnabled().
boolean engine.gameObject.GameObject.myCollision private
Definition at line 35 of file GameObject.java.
Referenced by engine.gameObject.GameObject.getCollisionConstant().
List<Component> engine.gameObject.GameObject.myComponents private
Definition at line 20 of file GameObject.java.
Referenced by engine.gameObject.GameObject.getComponents().
String engine.gameObject.GameObject.myCurrentImageName private
Definition at line 22 of file GameObject.java.
Referenced by engine.gameObject.GameObject.getCurrentImageName().
DefaultData engine.gameObject.GameObject.myDefaultData private
Definition at line 40 of file GameObject.java.
double engine.gameObject.GameObject.myHeight private
Definition at line 27 of file GameObject.java.
Referenced by engine.gameObject.GameObject.getHeight().
String engine.gameObject.GameObject.myID private
Definition at line 23 of file GameObject.java.
Referenced by engine.gameObject.GameObject.getID(), and engine.gameObject.GameObject.toString().
Identifier engine.gameObject.GameObject.myId private
Definition at line 43 of file GameObject.java.
Referenced by engine.gameObject.GameObject.getIdentifier(), and engine.gameObject.GameObject.setIdentifier().
String engine.gameObject.GameObject.myLabel private
Definition at line 25 of file GameObject.java.
Referenced by engine.gameObject.GameObject.getLabel().
PhysicsBody engine.gameObject.GameObject.myPhysicsBody private
Definition at line 24 of file GameObject.java.
Referenced by engine.gameObject.GameObject.getPhysicsBody().
transient RenderedNode engine.gameObject.GameObject.myRenderedNode private
Definition at line 32 of file GameObject.java.
Referenced by engine.gameObject.GameObject.getRenderedNode().
double engine.gameObject.GameObject.myRotation private
Definition at line 21 of file GameObject.java.
Referenced by engine.gameObject.GameObject.getRotation().
transient ScrollingUtility engine.gameObject.GameObject.myScrollingUtility private
Definition at line 33 of file GameObject.java.
double engine.gameObject.GameObject.myWidth private
Definition at line 28 of file GameObject.java.
Referenced by engine.gameObject.GameObject.getWidth().
double engine.gameObject.GameObject.myXCoord private
Definition at line 30 of file GameObject.java.
Referenced by engine.gameObject.GameObject.getX().
double engine.gameObject.GameObject.myYCoord private
Definition at line 31 of file GameObject.java.
Referenced by engine.gameObject.GameObject.getY().
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/voogasalad_BitsPlease/repository/src/engine/gameObject/GameObject.java