voogasalad_BitsPlease: authoring.controller.AuthoringController Class Reference
authoring.controller.AuthoringController Class Reference
Public Member Functions
AuthoringController (AuthoringView view, AuthoringModel model, double width, double height, ResourceBundle language, File gameLoc)
void saveData ()
void loadData (GameData input)
Private Member Functions
void initializeView ()
void initializeObs ()
void initializeViewComponents ()
void initializeGameHandlers ()
BorderPane intitializeCenter ()
AccordionContainer initializeLeft ()
TitledPane initializeRight ()
Private Attributes
AuthoringView myView
AuthoringModel myModel
ResourceBundle myLanguage
double myWidth
double myHeight
LevelsView myLevels
LevelOptions myLevelOptions
GameObjectsView myGameObjects
GameObjectOptions myObjectOptions
ImagesView myGraphics
GraphicOptions myGraphicOptions
SoundsView mySounds
SoundOptions mySoundOptions
PropertiesView myProperties
LevelsAccordionView myLevelsAccordionView
ConditionsAccordionView myConditionsAccordionView
ConditionOptions myConditionOptions
File myGameLocation
Static Private Attributes
static final double LEFT_ACCORDION_HEIGHT_RATIO = .70
static final double LEFT_ACCORDION_WIDTH_RATIO = .2
static final double CENTER_HEIGHT_RATIO = .92
static final double CENTER_WIDTH_RATIO = .6
Detailed Description
Controller class that interacts between model and view. Holds and constructs all the view components in order to allow communication between them. Allows the Model and View to exchange data without knowledge of each other.
Author
Kevin Li
Wesley Valentine
Chris Bernt
Arjun Jain
Eli Lichtenberg
Definition at line 59 of file AuthoringController.java.
Constructor & Destructor Documentation
authoring.controller.AuthoringController.AuthoringController (AuthoringView view, AuthoringModel model, double width, double height, ResourceBundle language, File gameLoc)
Definition at line 86 of file AuthoringController.java.
References authoring.controller.AuthoringController.initializeView().
Member Function Documentation
void authoring.controller.AuthoringController.initializeGameHandlers () private
Method that initializes and assigns the proper eventhandlers to each view component.
Definition at line 159 of file AuthoringController.java.
References authoring.model.AuthoringModel.getConditions(), authoring.model.AuthoringModel.getGameObjectCollection(), authoring.model.AuthoringModel.getImages(), authoring.model.AuthoringModel.getLevels(), authoring.model.AuthoringModel.getSounds(), authoring.controller.AuthoringController.myGameLocation, authoring.controller.AuthoringController.myLevels, authoring.controller.AuthoringController.myProperties, authoring.view.conditionsview.ConditionOptions.setAddConditionButtonBehavior(), authoring.view.levelview.LevelOptions.setAddLevelButtonBehavior(), authoring.view.graphicsview.GraphicOptions.setButtonBehavior(), authoring.view.soundsview.SoundOptions.setButtonBehavior(), authoring.view.gameobjectsview.GameObjectOptions.setButtonBehavior(), authoring.view.propertiesview.PropertiesView.setButtonBehaviors(), authoring.view.conditionsview.ConditionOptions.setDeleteConditionButtonBehavior(), authoring.view.levelview.LevelOptions.setDeleteLevelButtonBehavior(), authoring.view.soundsview.SoundsView.setDragDrop(), authoring.view.graphicsview.ImagesView.setDragDrop(), authoring.view.soundsview.SoundsView.setDragOver(), authoring.view.graphicsview.ImagesView.setDragOver(), authoring.view.levelview.LevelsView.setEventHandlers(), authoring.view.baseclasses.CollectionView.setIconEvents(), authoring.view.conditionsview.ConditionsAccordionView.setIconEvents(), authoring.view.levelview.LevelsAccordionView.setIconEvents(), and authoring.view.levelview.LevelsAccordionView.setLevelEvents().
Referenced by authoring.controller.AuthoringController.initializeView().
AccordionContainer authoring.controller.AuthoringController.initializeLeft () private
Places the correct view components into the left of the BorderPane
Returns
AccordianContainer to be displayed on the left side of the AuthoringView
Definition at line 239 of file AuthoringController.java.
References authoring.controller.AuthoringController.myLevelsAccordionView.
Referenced by authoring.controller.AuthoringController.initializeView().
void authoring.controller.AuthoringController.initializeObs () private
Method that initializes the observer/observable interaction between model and view components.
Definition at line 116 of file AuthoringController.java.
References authoring.model.AuthoringModel.getConditions(), authoring.model.AuthoringModel.getGameObjectCollection(), authoring.model.AuthoringModel.getImages(), authoring.model.AuthoringModel.getLevels(), and authoring.model.AuthoringModel.getSounds().
Referenced by authoring.controller.AuthoringController.initializeView().
TitledPane authoring.controller.AuthoringController.initializeRight () private
Places the correct view components into the right of the BorderPane
Returns
TitledPane to be displayed on the right side of the AuthoringView
Definition at line 291 of file AuthoringController.java.
References authoring.controller.AuthoringController.myProperties.
Referenced by authoring.controller.AuthoringController.initializeView().
void authoring.controller.AuthoringController.initializeView () private
Sets the contents of the AuthoringView - which is essentially an empty BorderPane.
Definition at line 102 of file AuthoringController.java.
References authoring.controller.AuthoringController.initializeGameHandlers(), authoring.controller.AuthoringController.initializeLeft(), authoring.controller.AuthoringController.initializeObs(), authoring.controller.AuthoringController.initializeRight(), authoring.controller.AuthoringController.initializeViewComponents(), and authoring.controller.AuthoringController.intitializeCenter().
Referenced by authoring.controller.AuthoringController.AuthoringController().
void authoring.controller.AuthoringController.initializeViewComponents () private
Initializes all the view components that have a 1 to 1 relationship with back end data components. Provides event handlers for View objects to handle sending data to the back end.
Definition at line 132 of file AuthoringController.java.
Referenced by authoring.controller.AuthoringController.initializeView().
BorderPane authoring.controller.AuthoringController.intitializeCenter () private
Places the correct view components into the center of the BorderPane
Returns
BorderPane to be displayed on the left side of the AuthoringView
Definition at line 223 of file AuthoringController.java.
Referenced by authoring.controller.AuthoringController.initializeView().
void authoring.controller.AuthoringController.loadData (GameData input)
Method to load the data stored in the model from a GSON File.
Definition at line 310 of file AuthoringController.java.
References authoring.model.AuthoringModel.load().
void authoring.controller.AuthoringController.saveData ()
Method to save the data stored in the model out to a GSON File.
Definition at line 302 of file AuthoringController.java.
References authoring.model.AuthoringModel.save().
Member Data Documentation
final double authoring.controller.AuthoringController.CENTER_HEIGHT_RATIO = .92 static private
Definition at line 62 of file AuthoringController.java.
final double authoring.controller.AuthoringController.CENTER_WIDTH_RATIO = .6 static private
Definition at line 63 of file AuthoringController.java.
final double authoring.controller.AuthoringController.LEFT_ACCORDION_HEIGHT_RATIO = .70 static private
Definition at line 60 of file AuthoringController.java.
final double authoring.controller.AuthoringController.LEFT_ACCORDION_WIDTH_RATIO = .2 static private
Definition at line 61 of file AuthoringController.java.
ConditionOptions authoring.controller.AuthoringController.myConditionOptions private
Definition at line 83 of file AuthoringController.java.
ConditionsAccordionView authoring.controller.AuthoringController.myConditionsAccordionView private
Definition at line 82 of file AuthoringController.java.
File authoring.controller.AuthoringController.myGameLocation private
Definition at line 84 of file AuthoringController.java.
Referenced by authoring.controller.AuthoringController.initializeGameHandlers().
GameObjectsView authoring.controller.AuthoringController.myGameObjects private
Definition at line 71 of file AuthoringController.java.
GraphicOptions authoring.controller.AuthoringController.myGraphicOptions private
Definition at line 75 of file AuthoringController.java.
ImagesView authoring.controller.AuthoringController.myGraphics private
Definition at line 74 of file AuthoringController.java.
double authoring.controller.AuthoringController.myHeight private
Definition at line 68 of file AuthoringController.java.
ResourceBundle authoring.controller.AuthoringController.myLanguage private
Definition at line 66 of file AuthoringController.java.
LevelOptions authoring.controller.AuthoringController.myLevelOptions private
Definition at line 70 of file AuthoringController.java.
LevelsView authoring.controller.AuthoringController.myLevels private
Definition at line 69 of file AuthoringController.java.
Referenced by authoring.controller.AuthoringController.initializeGameHandlers().
LevelsAccordionView authoring.controller.AuthoringController.myLevelsAccordionView private
Definition at line 81 of file AuthoringController.java.
Referenced by authoring.controller.AuthoringController.initializeLeft().
AuthoringModel authoring.controller.AuthoringController.myModel private
Definition at line 65 of file AuthoringController.java.
GameObjectOptions authoring.controller.AuthoringController.myObjectOptions private
Definition at line 72 of file AuthoringController.java.
PropertiesView authoring.controller.AuthoringController.myProperties private
Definition at line 80 of file AuthoringController.java.
Referenced by authoring.controller.AuthoringController.initializeGameHandlers(), and authoring.controller.AuthoringController.initializeRight().
SoundOptions authoring.controller.AuthoringController.mySoundOptions private
Definition at line 78 of file AuthoringController.java.
SoundsView authoring.controller.AuthoringController.mySounds private
Definition at line 77 of file AuthoringController.java.
AuthoringView authoring.controller.AuthoringController.myView private
Definition at line 64 of file AuthoringController.java.
double authoring.controller.AuthoringController.myWidth private
Definition at line 67 of file AuthoringController.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/voogasalad_BitsPlease/repository/src/authoring/controller/AuthoringController.java