voogasalad_BitsPlease: gamePlayer.view.MenuBarController Class Reference
gamePlayer.view.MenuBarController Class Reference
Public Member Functions
void setModel (PlayerModel model)
void setKeyboard ()
void initialize (URL location, ResourceBundle resources)
Private Member Functions
void loadGameFile (final ActionEvent event)
void exitFromGame (final ActionEvent event)
void fetchGameFromWeb (final ActionEvent event)
void saveGameToWeb (final ActionEvent event)
void saveGameProgress (final ActionEvent event)
void loadGameProgress (final ActionEvent event)
void pauseGame (final ActionEvent event)
void keyCombos (final ActionEvent event)
Private Attributes
PlayerModel myPlayerModel
KeyboardView myKeyboard
Tab gameSelector
Tab gameOptions
Tab gamePreferences
Detailed Description
Author
Shreyas B
Abhishek B
Definition at line 21 of file MenuBarController.java.
Member Function Documentation
void gamePlayer.view.MenuBarController.exitFromGame (final ActionEvent event) private
Definition at line 52 of file MenuBarController.java.
References gamePlayer.model.PlayerModel.exitFromGame().
void gamePlayer.view.MenuBarController.fetchGameFromWeb (final ActionEvent event) private
Definition at line 59 of file MenuBarController.java.
References gamePlayer.model.PlayerModel.fetchGameFromWeb().
void gamePlayer.view.MenuBarController.initialize (URL location, ResourceBundle resources)
Definition at line 85 of file MenuBarController.java.
void gamePlayer.view.MenuBarController.keyCombos (final ActionEvent event) private
Definition at line 90 of file MenuBarController.java.
References gamePlayer.view.keyboardUtility.KeyboardView.createKeyboardView(), and gamePlayer.model.PlayerModel.pauseGame().
void gamePlayer.view.MenuBarController.loadGameFile (final ActionEvent event) private
Definition at line 44 of file MenuBarController.java.
References gamePlayer.model.PlayerModel.loadGameFile().
void gamePlayer.view.MenuBarController.loadGameProgress (final ActionEvent event) private
Definition at line 74 of file MenuBarController.java.
References gamePlayer.model.PlayerModel.loadGameProgress().
void gamePlayer.view.MenuBarController.pauseGame (final ActionEvent event) private
Definition at line 79 of file MenuBarController.java.
References gamePlayer.model.PlayerModel.pauseGame().
void gamePlayer.view.MenuBarController.saveGameProgress (final ActionEvent event) private
Definition at line 69 of file MenuBarController.java.
References gamePlayer.model.PlayerModel.saveGameProgress().
void gamePlayer.view.MenuBarController.saveGameToWeb (final ActionEvent event) private
Definition at line 64 of file MenuBarController.java.
References gamePlayer.model.PlayerModel.saveGameToWeb().
void gamePlayer.view.MenuBarController.setKeyboard ()
Definition at line 39 of file MenuBarController.java.
References gamePlayer.model.PlayerModel.getButtonConditions().
Referenced by gamePlayer.view.PlayerView.initialize().
void gamePlayer.view.MenuBarController.setModel (PlayerModel model)
Definition at line 35 of file MenuBarController.java.
Referenced by gamePlayer.view.PlayerView.initialize().
Member Data Documentation
Tab gamePlayer.view.MenuBarController.gameOptions private
Definition at line 30 of file MenuBarController.java.
Tab gamePlayer.view.MenuBarController.gamePreferences private
Definition at line 33 of file MenuBarController.java.
Tab gamePlayer.view.MenuBarController.gameSelector private
Definition at line 27 of file MenuBarController.java.
KeyboardView gamePlayer.view.MenuBarController.myKeyboard private
Definition at line 24 of file MenuBarController.java.
PlayerModel gamePlayer.view.MenuBarController.myPlayerModel private
Definition at line 23 of file MenuBarController.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/voogasalad_BitsPlease/repository/src/gamePlayer/view/MenuBarController.java