voogasalad_BitsPlease: authoring.view.gameobjectsview.GameObjectsView Class Reference
authoring.view.gameobjectsview.GameObjectsView Class Reference
Public Member Functions
GameObjectsView (ResourceBundle language, double width, double height, File gameLoc)
void update (Observable o, Object arg)
Public Member Functions inherited from authoring.view.baseclasses.CollectionView
CollectionView (ResourceBundle language, double width, double height)
void setIconEvents (GameHandler...gameHandlers)
Private Member Functions
void addGameObject (GameObject gameObject, GameHandler...handler)
Private Attributes
VBox myVbox = new VBox()
File myGameLocation
Static Private Attributes
static final double VIEW_HEIGHT_RATIO = .65
static final double VIEW_WIDTH_RATIO = 0.2
Additional Inherited Members
Protected Member Functions inherited from authoring.view.baseclasses.CollectionView
void setView (double width, double height)
Protected Attributes inherited from authoring.view.baseclasses.CollectionView
ResourceBundle myLanguage
double myHeight
double myWidth
GameHandler[] myIconEvents
Detailed Description
View component for the backend model data - SpritesCollection. Updates automatically if changes occur in SpritesCollection via observer.
Author
Kevin Li
Chris Bernt
Wesley Valentine
Arjun Jain
Definition at line 23 of file GameObjectsView.java.
Constructor & Destructor Documentation
authoring.view.gameobjectsview.GameObjectsView.GameObjectsView (ResourceBundle language, double width, double height, File gameLoc)
Definition at line 30 of file GameObjectsView.java.
References authoring.view.baseclasses.CollectionView.setView().
Member Function Documentation
void authoring.view.gameobjectsview.GameObjectsView.addGameObject (GameObject gameObject, GameHandler... handler) private
Definition at line 44 of file GameObjectsView.java.
References authoring.view.icons.ImageBasedIcon.scaleDimensions().
Referenced by authoring.view.gameobjectsview.GameObjectsView.update().
void authoring.view.gameobjectsview.GameObjectsView.update (Observable o, Object arg)
This method is called whenever the observed object is changed. An application calls an Observable object's notifyObservers method to have all the object's observers notified of the change.
Parameters
o the observable object.
arg an argument passed to the notifyObservers method.
Implements data.Observer.
Definition at line 39 of file GameObjectsView.java.
References authoring.view.gameobjectsview.GameObjectsView.addGameObject(), and authoring.view.baseclasses.CollectionView.myIconEvents.
Member Data Documentation
File authoring.view.gameobjectsview.GameObjectsView.myGameLocation private
Definition at line 28 of file GameObjectsView.java.
VBox authoring.view.gameobjectsview.GameObjectsView.myVbox = new VBox() private
Definition at line 27 of file GameObjectsView.java.
final double authoring.view.gameobjectsview.GameObjectsView.VIEW_HEIGHT_RATIO = .65 static private
Definition at line 25 of file GameObjectsView.java.
final double authoring.view.gameobjectsview.GameObjectsView.VIEW_WIDTH_RATIO = 0.2 static private
Definition at line 26 of file GameObjectsView.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/voogasalad_BitsPlease/repository/src/authoring/view/gameobjectsview/GameObjectsView.java