voogasalad_BitsPlease: authoring.view.propertiesview.LevelProperties Class Reference
authoring.view.propertiesview.LevelProperties Class Reference
Public Member Functions
LevelProperties (Object o, GameHandler...handlers)
void initializeProperties (Object o)
Public Member Functions inherited from authoring.view.propertiesview.Properties
abstract void initializeProperties (Object o)
void addMapToView ()
Private Attributes
GameHandler[] myConditionHandlers
Additional Inherited Members
Protected Attributes inherited from authoring.view.propertiesview.Properties
Map< String, PropertyField > myMap = new LinkedHashMap<String, PropertyField>()
Detailed Description
Definition at line 11 of file LevelProperties.java.
Constructor & Destructor Documentation
authoring.view.propertiesview.LevelProperties.LevelProperties (Object o, GameHandler... handlers)
Definition at line 15 of file LevelProperties.java.
References authoring.view.propertiesview.LevelProperties.initializeProperties().
Member Function Documentation
void authoring.view.propertiesview.LevelProperties.initializeProperties (Object o)
Definition at line 21 of file LevelProperties.java.
References engine.level.Level.getBackgroundImage(), engine.level.Level.getBackgroundMusic(), engine.level.Level.getConditionCollection(), authoring.view.icons.LevelIcon.getLevel(), authoring.view.icons.BaseIcon.getName(), engine.level.Level.isStartLevel(), and authoring.view.propertiesview.Properties.myMap.
Referenced by authoring.view.propertiesview.LevelProperties.LevelProperties().
Member Data Documentation
GameHandler [] authoring.view.propertiesview.LevelProperties.myConditionHandlers private
Definition at line 13 of file LevelProperties.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/voogasalad_BitsPlease/repository/src/authoring/view/propertiesview/LevelProperties.java